// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgentDefinitionsByKnowledgeBase = `-- name: CountAgentDefinitionsByKnowledgeBase :one
SELECT (
    SELECT count(*) FROM agent_definitions
    WHERE agent_definitions.tenant_id = $1
      AND (
        agent_definitions.knowledge_base_ids ? $2::text
        OR EXISTS (
            SELECT 1 FROM jsonb_array_elements(agent_definitions.sub_agents) member
            WHERE COALESCE(member->'knowledge_base_ids', '[]'::jsonb) ? $2::text
        )
      )
) + (
    SELECT count(*) FROM agent_definition_versions
    WHERE agent_definition_versions.tenant_id = $1
      AND (
        agent_definition_versions.knowledge_base_ids ? $2::text
        OR EXISTS (
            SELECT 1 FROM jsonb_array_elements(agent_definition_versions.sub_agents) member
            WHERE COALESCE(member->'knowledge_base_ids', '[]'::jsonb) ? $2::text
        )
      )
)
`

type CountAgentDefinitionsByKnowledgeBaseParams struct {
	TenantID        string `json:"tenant_id"`
	KnowledgeBaseID string `json:"knowledge_base_id"`
}

func (q *Queries) CountAgentDefinitionsByKnowledgeBase(ctx context.Context, arg CountAgentDefinitionsByKnowledgeBaseParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAgentDefinitionsByKnowledgeBase, arg.TenantID, arg.KnowledgeBaseID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countAgentDefinitionsByModel = `-- name: CountAgentDefinitionsByModel :one
SELECT (
    SELECT count(*) FROM agent_definitions
    WHERE agent_definitions.tenant_id = $1
      AND (
        agent_definitions.model_id = $2
        OR EXISTS (
            SELECT 1 FROM jsonb_array_elements(agent_definitions.sub_agents) member
            WHERE member->>'model_id' = $2
        )
      )
) + (
    SELECT count(*) FROM agent_definition_versions
    WHERE agent_definition_versions.tenant_id = $1
      AND EXISTS (
        SELECT 1 FROM jsonb_array_elements(agent_definition_versions.sub_agents) member
        WHERE member->>'model_id' = $2
      )
)
`

type CountAgentDefinitionsByModelParams struct {
	TenantID string `json:"tenant_id"`
	ModelID  string `json:"model_id"`
}

func (q *Queries) CountAgentDefinitionsByModel(ctx context.Context, arg CountAgentDefinitionsByModelParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAgentDefinitionsByModel, arg.TenantID, arg.ModelID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAgentDefinition = `-- name: DeleteAgentDefinition :one
DELETE FROM agent_definitions
WHERE tenant_id = $1
  AND id = $2
RETURNING id, tenant_id, name, description, emoji, category, model_id, main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, status, visibility, visibility_targets, timeout_seconds, version, published_version, usage_total_runs, usage_success_runs, usage_failed_runs, usage_avg_latency_ms, usage_last_run_at, usage_top_prompts, created_by_account_id, updated_by_account_id, created_at, updated_at
`

type DeleteAgentDefinitionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteAgentDefinition(ctx context.Context, arg DeleteAgentDefinitionParams) (AgentDefinition, error) {
	row := q.db.QueryRow(ctx, deleteAgentDefinition, arg.TenantID, arg.ID)
	var i AgentDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Emoji,
		&i.Category,
		&i.ModelID,
		&i.MainAgentRole,
		&i.SubAgents,
		&i.SystemPrompt,
		&i.WelcomeMessage,
		&i.SuggestedQuestions,
		&i.Tools,
		&i.KnowledgeBaseIds,
		&i.Status,
		&i.Visibility,
		&i.VisibilityTargets,
		&i.TimeoutSeconds,
		&i.Version,
		&i.PublishedVersion,
		&i.UsageTotalRuns,
		&i.UsageSuccessRuns,
		&i.UsageFailedRuns,
		&i.UsageAvgLatencyMs,
		&i.UsageLastRunAt,
		&i.UsageTopPrompts,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentExternalTool = `-- name: DeleteAgentExternalTool :one
DELETE FROM agent_external_tools
WHERE tenant_id = $1
  AND id = $2
RETURNING id, tenant_id, name, description, kind, transport, endpoint_url, auth_type, auth_header_name, auth_username, auth_secret_ciphertext, created_by_account_id, created_at
`

type DeleteAgentExternalToolParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteAgentExternalTool(ctx context.Context, arg DeleteAgentExternalToolParams) (AgentExternalTool, error) {
	row := q.db.QueryRow(ctx, deleteAgentExternalTool, arg.TenantID, arg.ID)
	var i AgentExternalTool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Transport,
		&i.EndpointUrl,
		&i.AuthType,
		&i.AuthHeaderName,
		&i.AuthUsername,
		&i.AuthSecretCiphertext,
		&i.CreatedByAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgentModel = `-- name: DeleteAgentModel :one
DELETE FROM agent_models
WHERE tenant_id = $1
  AND id = $2
RETURNING id, tenant_id, name, provider, model_name, litellm_model, api_base_url, api_key_ciphertext, api_key_preview, rate_limit_rpm, status, timeout_seconds, monthly_quota, used_quota, last_tested_at, last_test_status, last_test_message, sync_status, last_synced_at, last_sync_error, synced_config_hash, created_at, updated_at
`

type DeleteAgentModelParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteAgentModel(ctx context.Context, arg DeleteAgentModelParams) (AgentModel, error) {
	row := q.db.QueryRow(ctx, deleteAgentModel, arg.TenantID, arg.ID)
	var i AgentModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Provider,
		&i.ModelName,
		&i.LitellmModel,
		&i.ApiBaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyPreview,
		&i.RateLimitRpm,
		&i.Status,
		&i.TimeoutSeconds,
		&i.MonthlyQuota,
		&i.UsedQuota,
		&i.LastTestedAt,
		&i.LastTestStatus,
		&i.LastTestMessage,
		&i.SyncStatus,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.SyncedConfigHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentDefinition = `-- name: GetAgentDefinition :one
SELECT id, tenant_id, name, description, emoji, category, model_id, main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, status, visibility, visibility_targets, timeout_seconds, version, published_version, usage_total_runs, usage_success_runs, usage_failed_runs, usage_avg_latency_ms, usage_last_run_at, usage_top_prompts, created_by_account_id, updated_by_account_id, created_at, updated_at FROM agent_definitions
WHERE tenant_id = $1
  AND id = $2
`

type GetAgentDefinitionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetAgentDefinition(ctx context.Context, arg GetAgentDefinitionParams) (AgentDefinition, error) {
	row := q.db.QueryRow(ctx, getAgentDefinition, arg.TenantID, arg.ID)
	var i AgentDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Emoji,
		&i.Category,
		&i.ModelID,
		&i.MainAgentRole,
		&i.SubAgents,
		&i.SystemPrompt,
		&i.WelcomeMessage,
		&i.SuggestedQuestions,
		&i.Tools,
		&i.KnowledgeBaseIds,
		&i.Status,
		&i.Visibility,
		&i.VisibilityTargets,
		&i.TimeoutSeconds,
		&i.Version,
		&i.PublishedVersion,
		&i.UsageTotalRuns,
		&i.UsageSuccessRuns,
		&i.UsageFailedRuns,
		&i.UsageAvgLatencyMs,
		&i.UsageLastRunAt,
		&i.UsageTopPrompts,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentDefinitionVersion = `-- name: GetAgentDefinitionVersion :one
SELECT id, tenant_id, agent_id, version, main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, model_id, note, created_by_account_id, created_at FROM agent_definition_versions
WHERE tenant_id = $1
  AND agent_id = $2
  AND version = $3
`

type GetAgentDefinitionVersionParams struct {
	TenantID string `json:"tenant_id"`
	AgentID  string `json:"agent_id"`
	Version  int32  `json:"version"`
}

func (q *Queries) GetAgentDefinitionVersion(ctx context.Context, arg GetAgentDefinitionVersionParams) (AgentDefinitionVersion, error) {
	row := q.db.QueryRow(ctx, getAgentDefinitionVersion, arg.TenantID, arg.AgentID, arg.Version)
	var i AgentDefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentID,
		&i.Version,
		&i.MainAgentRole,
		&i.SubAgents,
		&i.SystemPrompt,
		&i.WelcomeMessage,
		&i.SuggestedQuestions,
		&i.Tools,
		&i.KnowledgeBaseIds,
		&i.ModelID,
		&i.Note,
		&i.CreatedByAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentModel = `-- name: GetAgentModel :one
SELECT id, tenant_id, name, provider, model_name, litellm_model, api_base_url, api_key_ciphertext, api_key_preview, rate_limit_rpm, status, timeout_seconds, monthly_quota, used_quota, last_tested_at, last_test_status, last_test_message, sync_status, last_synced_at, last_sync_error, synced_config_hash, created_at, updated_at FROM agent_models
WHERE tenant_id = $1
  AND id = $2
`

type GetAgentModelParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetAgentModel(ctx context.Context, arg GetAgentModelParams) (AgentModel, error) {
	row := q.db.QueryRow(ctx, getAgentModel, arg.TenantID, arg.ID)
	var i AgentModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Provider,
		&i.ModelName,
		&i.LitellmModel,
		&i.ApiBaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyPreview,
		&i.RateLimitRpm,
		&i.Status,
		&i.TimeoutSeconds,
		&i.MonthlyQuota,
		&i.UsedQuota,
		&i.LastTestedAt,
		&i.LastTestStatus,
		&i.LastTestMessage,
		&i.SyncStatus,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.SyncedConfigHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgentDefinitionVersion = `-- name: InsertAgentDefinitionVersion :one
INSERT INTO agent_definition_versions (
    id, tenant_id, agent_id, version, main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, model_id, note,
    created_by_account_id, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6::jsonb, $7, $8, $9::jsonb, $10::jsonb, $11::jsonb, $12, $13,
    $14, $15
)
RETURNING id, tenant_id, agent_id, version, main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, model_id, note, created_by_account_id, created_at
`

type InsertAgentDefinitionVersionParams struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	AgentID            string             `json:"agent_id"`
	Version            int32              `json:"version"`
	MainAgentRole      string             `json:"main_agent_role"`
	SubAgents          []byte             `json:"sub_agents"`
	SystemPrompt       string             `json:"system_prompt"`
	WelcomeMessage     string             `json:"welcome_message"`
	SuggestedQuestions []byte             `json:"suggested_questions"`
	Tools              []byte             `json:"tools"`
	KnowledgeBaseIds   []byte             `json:"knowledge_base_ids"`
	ModelID            string             `json:"model_id"`
	Note               string             `json:"note"`
	CreatedByAccountID pgtype.Text        `json:"created_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAgentDefinitionVersion(ctx context.Context, arg InsertAgentDefinitionVersionParams) (AgentDefinitionVersion, error) {
	row := q.db.QueryRow(ctx, insertAgentDefinitionVersion,
		arg.ID,
		arg.TenantID,
		arg.AgentID,
		arg.Version,
		arg.MainAgentRole,
		arg.SubAgents,
		arg.SystemPrompt,
		arg.WelcomeMessage,
		arg.SuggestedQuestions,
		arg.Tools,
		arg.KnowledgeBaseIds,
		arg.ModelID,
		arg.Note,
		arg.CreatedByAccountID,
		arg.CreatedAt,
	)
	var i AgentDefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentID,
		&i.Version,
		&i.MainAgentRole,
		&i.SubAgents,
		&i.SystemPrompt,
		&i.WelcomeMessage,
		&i.SuggestedQuestions,
		&i.Tools,
		&i.KnowledgeBaseIds,
		&i.ModelID,
		&i.Note,
		&i.CreatedByAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const insertAgentExternalTool = `-- name: InsertAgentExternalTool :one
INSERT INTO agent_external_tools (
    id, tenant_id, name, description, kind, transport, endpoint_url,
    auth_type, auth_header_name, auth_username, auth_secret_ciphertext,
    created_by_account_id, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13
)
RETURNING id, tenant_id, name, description, kind, transport, endpoint_url, auth_type, auth_header_name, auth_username, auth_secret_ciphertext, created_by_account_id, created_at
`

type InsertAgentExternalToolParams struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	Name                 string             `json:"name"`
	Description          string             `json:"description"`
	Kind                 string             `json:"kind"`
	Transport            string             `json:"transport"`
	EndpointUrl          string             `json:"endpoint_url"`
	AuthType             string             `json:"auth_type"`
	AuthHeaderName       string             `json:"auth_header_name"`
	AuthUsername         string             `json:"auth_username"`
	AuthSecretCiphertext string             `json:"auth_secret_ciphertext"`
	CreatedByAccountID   pgtype.Text        `json:"created_by_account_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAgentExternalTool(ctx context.Context, arg InsertAgentExternalToolParams) (AgentExternalTool, error) {
	row := q.db.QueryRow(ctx, insertAgentExternalTool,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.Transport,
		arg.EndpointUrl,
		arg.AuthType,
		arg.AuthHeaderName,
		arg.AuthUsername,
		arg.AuthSecretCiphertext,
		arg.CreatedByAccountID,
		arg.CreatedAt,
	)
	var i AgentExternalTool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Transport,
		&i.EndpointUrl,
		&i.AuthType,
		&i.AuthHeaderName,
		&i.AuthUsername,
		&i.AuthSecretCiphertext,
		&i.CreatedByAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentDefinitionVersions = `-- name: ListAgentDefinitionVersions :many
SELECT id, tenant_id, agent_id, version, main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, model_id, note, created_by_account_id, created_at FROM agent_definition_versions
WHERE tenant_id = $1
  AND agent_id = $2
ORDER BY version DESC
`

type ListAgentDefinitionVersionsParams struct {
	TenantID string `json:"tenant_id"`
	AgentID  string `json:"agent_id"`
}

func (q *Queries) ListAgentDefinitionVersions(ctx context.Context, arg ListAgentDefinitionVersionsParams) ([]AgentDefinitionVersion, error) {
	rows, err := q.db.Query(ctx, listAgentDefinitionVersions, arg.TenantID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentDefinitionVersion
	for rows.Next() {
		var i AgentDefinitionVersion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentID,
			&i.Version,
			&i.MainAgentRole,
			&i.SubAgents,
			&i.SystemPrompt,
			&i.WelcomeMessage,
			&i.SuggestedQuestions,
			&i.Tools,
			&i.KnowledgeBaseIds,
			&i.ModelID,
			&i.Note,
			&i.CreatedByAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentDefinitions = `-- name: ListAgentDefinitions :many
SELECT id, tenant_id, name, description, emoji, category, model_id, main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, status, visibility, visibility_targets, timeout_seconds, version, published_version, usage_total_runs, usage_success_runs, usage_failed_runs, usage_avg_latency_ms, usage_last_run_at, usage_top_prompts, created_by_account_id, updated_by_account_id, created_at, updated_at FROM agent_definitions
WHERE tenant_id = $1
ORDER BY status ASC, updated_at DESC, id ASC
`

func (q *Queries) ListAgentDefinitions(ctx context.Context, tenantID string) ([]AgentDefinition, error) {
	rows, err := q.db.Query(ctx, listAgentDefinitions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentDefinition
	for rows.Next() {
		var i AgentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Emoji,
			&i.Category,
			&i.ModelID,
			&i.MainAgentRole,
			&i.SubAgents,
			&i.SystemPrompt,
			&i.WelcomeMessage,
			&i.SuggestedQuestions,
			&i.Tools,
			&i.KnowledgeBaseIds,
			&i.Status,
			&i.Visibility,
			&i.VisibilityTargets,
			&i.TimeoutSeconds,
			&i.Version,
			&i.PublishedVersion,
			&i.UsageTotalRuns,
			&i.UsageSuccessRuns,
			&i.UsageFailedRuns,
			&i.UsageAvgLatencyMs,
			&i.UsageLastRunAt,
			&i.UsageTopPrompts,
			&i.CreatedByAccountID,
			&i.UpdatedByAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentExternalTools = `-- name: ListAgentExternalTools :many
SELECT id, tenant_id, name, description, kind, transport, endpoint_url, auth_type, auth_header_name, auth_username, auth_secret_ciphertext, created_by_account_id, created_at FROM agent_external_tools
WHERE tenant_id = $1
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListAgentExternalTools(ctx context.Context, tenantID string) ([]AgentExternalTool, error) {
	rows, err := q.db.Query(ctx, listAgentExternalTools, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentExternalTool
	for rows.Next() {
		var i AgentExternalTool
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.Transport,
			&i.EndpointUrl,
			&i.AuthType,
			&i.AuthHeaderName,
			&i.AuthUsername,
			&i.AuthSecretCiphertext,
			&i.CreatedByAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentModels = `-- name: ListAgentModels :many
SELECT id, tenant_id, name, provider, model_name, litellm_model, api_base_url, api_key_ciphertext, api_key_preview, rate_limit_rpm, status, timeout_seconds, monthly_quota, used_quota, last_tested_at, last_test_status, last_test_message, sync_status, last_synced_at, last_sync_error, synced_config_hash, created_at, updated_at FROM agent_models
WHERE tenant_id = $1
ORDER BY updated_at DESC, id ASC
`

func (q *Queries) ListAgentModels(ctx context.Context, tenantID string) ([]AgentModel, error) {
	rows, err := q.db.Query(ctx, listAgentModels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentModel
	for rows.Next() {
		var i AgentModel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Provider,
			&i.ModelName,
			&i.LitellmModel,
			&i.ApiBaseUrl,
			&i.ApiKeyCiphertext,
			&i.ApiKeyPreview,
			&i.RateLimitRpm,
			&i.Status,
			&i.TimeoutSeconds,
			&i.MonthlyQuota,
			&i.UsedQuota,
			&i.LastTestedAt,
			&i.LastTestStatus,
			&i.LastTestMessage,
			&i.SyncStatus,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.SyncedConfigHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedAgentDefinitions = `-- name: ListPublishedAgentDefinitions :many
SELECT id, tenant_id, name, description, emoji, category, model_id, main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, status, visibility, visibility_targets, timeout_seconds, version, published_version, usage_total_runs, usage_success_runs, usage_failed_runs, usage_avg_latency_ms, usage_last_run_at, usage_top_prompts, created_by_account_id, updated_by_account_id, created_at, updated_at FROM agent_definitions
WHERE tenant_id = $1
  AND status = 'published'
ORDER BY updated_at DESC, id ASC
`

func (q *Queries) ListPublishedAgentDefinitions(ctx context.Context, tenantID string) ([]AgentDefinition, error) {
	rows, err := q.db.Query(ctx, listPublishedAgentDefinitions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentDefinition
	for rows.Next() {
		var i AgentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Emoji,
			&i.Category,
			&i.ModelID,
			&i.MainAgentRole,
			&i.SubAgents,
			&i.SystemPrompt,
			&i.WelcomeMessage,
			&i.SuggestedQuestions,
			&i.Tools,
			&i.KnowledgeBaseIds,
			&i.Status,
			&i.Visibility,
			&i.VisibilityTargets,
			&i.TimeoutSeconds,
			&i.Version,
			&i.PublishedVersion,
			&i.UsageTotalRuns,
			&i.UsageSuccessRuns,
			&i.UsageFailedRuns,
			&i.UsageAvgLatencyMs,
			&i.UsageLastRunAt,
			&i.UsageTopPrompts,
			&i.CreatedByAccountID,
			&i.UpdatedByAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentDefinitionUsage = `-- name: UpdateAgentDefinitionUsage :one
UPDATE agent_definitions
SET usage_total_runs = usage_total_runs + 1,
    usage_success_runs = usage_success_runs + CASE WHEN $1::boolean THEN 1 ELSE 0 END,
    usage_failed_runs = usage_failed_runs + CASE WHEN $1::boolean THEN 0 ELSE 1 END,
    usage_avg_latency_ms = CASE
        WHEN $2::int <= 0 THEN usage_avg_latency_ms
        ELSE ((usage_avg_latency_ms::bigint * usage_total_runs) + $2::int) / (usage_total_runs + 1)
    END,
    usage_last_run_at = $3,
    usage_top_prompts = CASE
        WHEN $4::text = '' THEN usage_top_prompts
        ELSE (
            SELECT COALESCE(jsonb_agg(to_jsonb(value)), '[]'::jsonb)
            FROM (
                SELECT value
                FROM (
                    SELECT jsonb_array_elements_text(
                        jsonb_build_array($4::text) || COALESCE(usage_top_prompts, '[]'::jsonb)
                    ) AS value
                ) ranked
                LIMIT 5
            ) limited
        )
    END,
    updated_at = $3
WHERE tenant_id = $5
  AND id = $6
RETURNING id, tenant_id, name, description, emoji, category, model_id, main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, status, visibility, visibility_targets, timeout_seconds, version, published_version, usage_total_runs, usage_success_runs, usage_failed_runs, usage_avg_latency_ms, usage_last_run_at, usage_top_prompts, created_by_account_id, updated_by_account_id, created_at, updated_at
`

type UpdateAgentDefinitionUsageParams struct {
	Success   bool               `json:"success"`
	LatencyMs int32              `json:"latency_ms"`
	RunAt     pgtype.Timestamptz `json:"run_at"`
	Prompt    string             `json:"prompt"`
	TenantID  string             `json:"tenant_id"`
	ID        string             `json:"id"`
}

func (q *Queries) UpdateAgentDefinitionUsage(ctx context.Context, arg UpdateAgentDefinitionUsageParams) (AgentDefinition, error) {
	row := q.db.QueryRow(ctx, updateAgentDefinitionUsage,
		arg.Success,
		arg.LatencyMs,
		arg.RunAt,
		arg.Prompt,
		arg.TenantID,
		arg.ID,
	)
	var i AgentDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Emoji,
		&i.Category,
		&i.ModelID,
		&i.MainAgentRole,
		&i.SubAgents,
		&i.SystemPrompt,
		&i.WelcomeMessage,
		&i.SuggestedQuestions,
		&i.Tools,
		&i.KnowledgeBaseIds,
		&i.Status,
		&i.Visibility,
		&i.VisibilityTargets,
		&i.TimeoutSeconds,
		&i.Version,
		&i.PublishedVersion,
		&i.UsageTotalRuns,
		&i.UsageSuccessRuns,
		&i.UsageFailedRuns,
		&i.UsageAvgLatencyMs,
		&i.UsageLastRunAt,
		&i.UsageTopPrompts,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentModelSyncResult = `-- name: UpdateAgentModelSyncResult :one
UPDATE agent_models
SET sync_status = $1,
    last_synced_at = $2,
    last_sync_error = $3,
    synced_config_hash = $4,
    updated_at = $5
WHERE tenant_id = $6
  AND id = $7
RETURNING id, tenant_id, name, provider, model_name, litellm_model, api_base_url, api_key_ciphertext, api_key_preview, rate_limit_rpm, status, timeout_seconds, monthly_quota, used_quota, last_tested_at, last_test_status, last_test_message, sync_status, last_synced_at, last_sync_error, synced_config_hash, created_at, updated_at
`

type UpdateAgentModelSyncResultParams struct {
	SyncStatus       string             `json:"sync_status"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	LastSyncError    string             `json:"last_sync_error"`
	SyncedConfigHash string             `json:"synced_config_hash"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	TenantID         string             `json:"tenant_id"`
	ID               string             `json:"id"`
}

func (q *Queries) UpdateAgentModelSyncResult(ctx context.Context, arg UpdateAgentModelSyncResultParams) (AgentModel, error) {
	row := q.db.QueryRow(ctx, updateAgentModelSyncResult,
		arg.SyncStatus,
		arg.LastSyncedAt,
		arg.LastSyncError,
		arg.SyncedConfigHash,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	var i AgentModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Provider,
		&i.ModelName,
		&i.LitellmModel,
		&i.ApiBaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyPreview,
		&i.RateLimitRpm,
		&i.Status,
		&i.TimeoutSeconds,
		&i.MonthlyQuota,
		&i.UsedQuota,
		&i.LastTestedAt,
		&i.LastTestStatus,
		&i.LastTestMessage,
		&i.SyncStatus,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.SyncedConfigHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentModelTestResult = `-- name: UpdateAgentModelTestResult :one
UPDATE agent_models
SET last_tested_at = $1,
    last_test_status = $2,
    last_test_message = $3,
    updated_at = $4
WHERE tenant_id = $5
  AND id = $6
RETURNING id, tenant_id, name, provider, model_name, litellm_model, api_base_url, api_key_ciphertext, api_key_preview, rate_limit_rpm, status, timeout_seconds, monthly_quota, used_quota, last_tested_at, last_test_status, last_test_message, sync_status, last_synced_at, last_sync_error, synced_config_hash, created_at, updated_at
`

type UpdateAgentModelTestResultParams struct {
	LastTestedAt    pgtype.Timestamptz `json:"last_tested_at"`
	LastTestStatus  string             `json:"last_test_status"`
	LastTestMessage string             `json:"last_test_message"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TenantID        string             `json:"tenant_id"`
	ID              string             `json:"id"`
}

func (q *Queries) UpdateAgentModelTestResult(ctx context.Context, arg UpdateAgentModelTestResultParams) (AgentModel, error) {
	row := q.db.QueryRow(ctx, updateAgentModelTestResult,
		arg.LastTestedAt,
		arg.LastTestStatus,
		arg.LastTestMessage,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	var i AgentModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Provider,
		&i.ModelName,
		&i.LitellmModel,
		&i.ApiBaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyPreview,
		&i.RateLimitRpm,
		&i.Status,
		&i.TimeoutSeconds,
		&i.MonthlyQuota,
		&i.UsedQuota,
		&i.LastTestedAt,
		&i.LastTestStatus,
		&i.LastTestMessage,
		&i.SyncStatus,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.SyncedConfigHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentDefinition = `-- name: UpsertAgentDefinition :one
INSERT INTO agent_definitions (
    id, tenant_id, name, description, emoji, category, model_id,
    main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, status, visibility, visibility_targets, timeout_seconds,
    version, published_version, usage_total_runs, usage_success_runs, usage_failed_runs, usage_avg_latency_ms,
    usage_last_run_at, usage_top_prompts, created_by_account_id, updated_by_account_id,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9::jsonb, $10, $11, $12::jsonb, $13::jsonb, $14::jsonb, $15, $16,
    $17::jsonb, $18, $19, $20,
    $21, $22, $23,
    $24, $25, $26::jsonb,
    $27, $28,
    $29, $30
)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    emoji = EXCLUDED.emoji,
    category = EXCLUDED.category,
    model_id = EXCLUDED.model_id,
	main_agent_role = EXCLUDED.main_agent_role,
    sub_agents = EXCLUDED.sub_agents,
    system_prompt = EXCLUDED.system_prompt,
    welcome_message = EXCLUDED.welcome_message,
    suggested_questions = EXCLUDED.suggested_questions,
    tools = EXCLUDED.tools,
    knowledge_base_ids = EXCLUDED.knowledge_base_ids,
    status = EXCLUDED.status,
    visibility = EXCLUDED.visibility,
    visibility_targets = EXCLUDED.visibility_targets,
    timeout_seconds = EXCLUDED.timeout_seconds,
    version = EXCLUDED.version,
	published_version = EXCLUDED.published_version,
    usage_total_runs = EXCLUDED.usage_total_runs,
    usage_success_runs = EXCLUDED.usage_success_runs,
    usage_failed_runs = EXCLUDED.usage_failed_runs,
    usage_avg_latency_ms = EXCLUDED.usage_avg_latency_ms,
    usage_last_run_at = EXCLUDED.usage_last_run_at,
    usage_top_prompts = EXCLUDED.usage_top_prompts,
    created_by_account_id = EXCLUDED.created_by_account_id,
    updated_by_account_id = EXCLUDED.updated_by_account_id,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, tenant_id, name, description, emoji, category, model_id, main_agent_role, sub_agents, system_prompt, welcome_message, suggested_questions, tools, knowledge_base_ids, status, visibility, visibility_targets, timeout_seconds, version, published_version, usage_total_runs, usage_success_runs, usage_failed_runs, usage_avg_latency_ms, usage_last_run_at, usage_top_prompts, created_by_account_id, updated_by_account_id, created_at, updated_at
`

type UpsertAgentDefinitionParams struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	Emoji              string             `json:"emoji"`
	Category           string             `json:"category"`
	ModelID            string             `json:"model_id"`
	MainAgentRole      string             `json:"main_agent_role"`
	SubAgents          []byte             `json:"sub_agents"`
	SystemPrompt       string             `json:"system_prompt"`
	WelcomeMessage     string             `json:"welcome_message"`
	SuggestedQuestions []byte             `json:"suggested_questions"`
	Tools              []byte             `json:"tools"`
	KnowledgeBaseIds   []byte             `json:"knowledge_base_ids"`
	Status             string             `json:"status"`
	Visibility         string             `json:"visibility"`
	VisibilityTargets  []byte             `json:"visibility_targets"`
	TimeoutSeconds     int32              `json:"timeout_seconds"`
	Version            int32              `json:"version"`
	PublishedVersion   int32              `json:"published_version"`
	UsageTotalRuns     int64              `json:"usage_total_runs"`
	UsageSuccessRuns   int64              `json:"usage_success_runs"`
	UsageFailedRuns    int64              `json:"usage_failed_runs"`
	UsageAvgLatencyMs  int32              `json:"usage_avg_latency_ms"`
	UsageLastRunAt     pgtype.Timestamptz `json:"usage_last_run_at"`
	UsageTopPrompts    []byte             `json:"usage_top_prompts"`
	CreatedByAccountID pgtype.Text        `json:"created_by_account_id"`
	UpdatedByAccountID pgtype.Text        `json:"updated_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAgentDefinition(ctx context.Context, arg UpsertAgentDefinitionParams) (AgentDefinition, error) {
	row := q.db.QueryRow(ctx, upsertAgentDefinition,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Emoji,
		arg.Category,
		arg.ModelID,
		arg.MainAgentRole,
		arg.SubAgents,
		arg.SystemPrompt,
		arg.WelcomeMessage,
		arg.SuggestedQuestions,
		arg.Tools,
		arg.KnowledgeBaseIds,
		arg.Status,
		arg.Visibility,
		arg.VisibilityTargets,
		arg.TimeoutSeconds,
		arg.Version,
		arg.PublishedVersion,
		arg.UsageTotalRuns,
		arg.UsageSuccessRuns,
		arg.UsageFailedRuns,
		arg.UsageAvgLatencyMs,
		arg.UsageLastRunAt,
		arg.UsageTopPrompts,
		arg.CreatedByAccountID,
		arg.UpdatedByAccountID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AgentDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Emoji,
		&i.Category,
		&i.ModelID,
		&i.MainAgentRole,
		&i.SubAgents,
		&i.SystemPrompt,
		&i.WelcomeMessage,
		&i.SuggestedQuestions,
		&i.Tools,
		&i.KnowledgeBaseIds,
		&i.Status,
		&i.Visibility,
		&i.VisibilityTargets,
		&i.TimeoutSeconds,
		&i.Version,
		&i.PublishedVersion,
		&i.UsageTotalRuns,
		&i.UsageSuccessRuns,
		&i.UsageFailedRuns,
		&i.UsageAvgLatencyMs,
		&i.UsageLastRunAt,
		&i.UsageTopPrompts,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentModel = `-- name: UpsertAgentModel :one
INSERT INTO agent_models (
    id, tenant_id, name, provider, model_name, litellm_model,
    api_base_url, api_key_ciphertext, api_key_preview, rate_limit_rpm,
    status, timeout_seconds,
    monthly_quota, used_quota, last_tested_at, last_test_status,
    last_test_message, sync_status, last_synced_at, last_sync_error,
    synced_config_hash, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12,
    $13, $14, $15,
    $16, $17,
    $18, $19, $20,
    $21,
    $22, $23
)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    name = EXCLUDED.name,
    provider = EXCLUDED.provider,
    model_name = EXCLUDED.model_name,
    litellm_model = EXCLUDED.litellm_model,
    api_base_url = EXCLUDED.api_base_url,
    api_key_ciphertext = EXCLUDED.api_key_ciphertext,
    api_key_preview = EXCLUDED.api_key_preview,
    rate_limit_rpm = EXCLUDED.rate_limit_rpm,
    status = EXCLUDED.status,
    timeout_seconds = EXCLUDED.timeout_seconds,
    monthly_quota = EXCLUDED.monthly_quota,
    used_quota = EXCLUDED.used_quota,
    last_tested_at = EXCLUDED.last_tested_at,
    last_test_status = EXCLUDED.last_test_status,
    last_test_message = EXCLUDED.last_test_message,
    sync_status = EXCLUDED.sync_status,
    last_synced_at = EXCLUDED.last_synced_at,
    last_sync_error = EXCLUDED.last_sync_error,
    synced_config_hash = EXCLUDED.synced_config_hash,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, tenant_id, name, provider, model_name, litellm_model, api_base_url, api_key_ciphertext, api_key_preview, rate_limit_rpm, status, timeout_seconds, monthly_quota, used_quota, last_tested_at, last_test_status, last_test_message, sync_status, last_synced_at, last_sync_error, synced_config_hash, created_at, updated_at
`

type UpsertAgentModelParams struct {
	ID               string             `json:"id"`
	TenantID         string             `json:"tenant_id"`
	Name             string             `json:"name"`
	Provider         string             `json:"provider"`
	ModelName        string             `json:"model_name"`
	LitellmModel     string             `json:"litellm_model"`
	ApiBaseUrl       string             `json:"api_base_url"`
	ApiKeyCiphertext string             `json:"api_key_ciphertext"`
	ApiKeyPreview    string             `json:"api_key_preview"`
	RateLimitRpm     int32              `json:"rate_limit_rpm"`
	Status           string             `json:"status"`
	TimeoutSeconds   int32              `json:"timeout_seconds"`
	MonthlyQuota     int64              `json:"monthly_quota"`
	UsedQuota        int64              `json:"used_quota"`
	LastTestedAt     pgtype.Timestamptz `json:"last_tested_at"`
	LastTestStatus   string             `json:"last_test_status"`
	LastTestMessage  string             `json:"last_test_message"`
	SyncStatus       string             `json:"sync_status"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	LastSyncError    string             `json:"last_sync_error"`
	SyncedConfigHash string             `json:"synced_config_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAgentModel(ctx context.Context, arg UpsertAgentModelParams) (AgentModel, error) {
	row := q.db.QueryRow(ctx, upsertAgentModel,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Provider,
		arg.ModelName,
		arg.LitellmModel,
		arg.ApiBaseUrl,
		arg.ApiKeyCiphertext,
		arg.ApiKeyPreview,
		arg.RateLimitRpm,
		arg.Status,
		arg.TimeoutSeconds,
		arg.MonthlyQuota,
		arg.UsedQuota,
		arg.LastTestedAt,
		arg.LastTestStatus,
		arg.LastTestMessage,
		arg.SyncStatus,
		arg.LastSyncedAt,
		arg.LastSyncError,
		arg.SyncedConfigHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AgentModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Provider,
		&i.ModelName,
		&i.LitellmModel,
		&i.ApiBaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyPreview,
		&i.RateLimitRpm,
		&i.Status,
		&i.TimeoutSeconds,
		&i.MonthlyQuota,
		&i.UsedQuota,
		&i.LastTestedAt,
		&i.LastTestStatus,
		&i.LastTestMessage,
		&i.SyncStatus,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.SyncedConfigHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
