// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAgentRunsBySession = `-- name: CountActiveAgentRunsBySession :one
SELECT count(*) FROM agent_runs
WHERE tenant_id = $1
  AND session_id = $2
  AND status IN ('queued', 'running')
`

type CountActiveAgentRunsBySessionParams struct {
	TenantID  string      `json:"tenant_id"`
	SessionID pgtype.Text `json:"session_id"`
}

func (q *Queries) CountActiveAgentRunsBySession(ctx context.Context, arg CountActiveAgentRunsBySessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAgentRunsBySession, arg.TenantID, arg.SessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAgentMemory = `-- name: DeleteAgentMemory :one
DELETE FROM agent_memories
WHERE tenant_id = $1
  AND id = $2
RETURNING id, tenant_id, account_id, agent_id, session_id, key, content, source, importance, expires_at, created_at, updated_at
`

type DeleteAgentMemoryParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteAgentMemory(ctx context.Context, arg DeleteAgentMemoryParams) (AgentMemory, error) {
	row := q.db.QueryRow(ctx, deleteAgentMemory, arg.TenantID, arg.ID)
	var i AgentMemory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.SessionID,
		&i.Key,
		&i.Content,
		&i.Source,
		&i.Importance,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentSession = `-- name: DeleteAgentSession :one
DELETE FROM agent_sessions
WHERE tenant_id = $1
  AND id = $2
RETURNING id, tenant_id, account_id, agent_id, title, status, context_version, last_message_at, created_at, updated_at
`

type DeleteAgentSessionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteAgentSession(ctx context.Context, arg DeleteAgentSessionParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, deleteAgentSession, arg.TenantID, arg.ID)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.Title,
		&i.Status,
		&i.ContextVersion,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentMemory = `-- name: GetAgentMemory :one
SELECT id, tenant_id, account_id, agent_id, session_id, key, content, source, importance, expires_at, created_at, updated_at FROM agent_memories
WHERE tenant_id = $1
  AND id = $2
`

type GetAgentMemoryParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetAgentMemory(ctx context.Context, arg GetAgentMemoryParams) (AgentMemory, error) {
	row := q.db.QueryRow(ctx, getAgentMemory, arg.TenantID, arg.ID)
	var i AgentMemory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.SessionID,
		&i.Key,
		&i.Content,
		&i.Source,
		&i.Importance,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentSession = `-- name: GetAgentSession :one
SELECT id, tenant_id, account_id, agent_id, title, status, context_version, last_message_at, created_at, updated_at FROM agent_sessions
WHERE tenant_id = $1
  AND id = $2
`

type GetAgentSessionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetAgentSession(ctx context.Context, arg GetAgentSessionParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, getAgentSession, arg.TenantID, arg.ID)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.Title,
		&i.Status,
		&i.ContextVersion,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentSessionForUpdate = `-- name: GetAgentSessionForUpdate :one
SELECT id, tenant_id, account_id, agent_id, title, status, context_version, last_message_at, created_at, updated_at FROM agent_sessions
WHERE tenant_id = $1
  AND id = $2
FOR UPDATE
`

type GetAgentSessionForUpdateParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetAgentSessionForUpdate(ctx context.Context, arg GetAgentSessionForUpdateParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, getAgentSessionForUpdate, arg.TenantID, arg.ID)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.Title,
		&i.Status,
		&i.ContextVersion,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgentSessionMessage = `-- name: InsertAgentSessionMessage :one
INSERT INTO agent_session_messages (
    id, tenant_id, session_id, role, content, run_id, context_version, metadata, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8::jsonb, $9
)
RETURNING id, tenant_id, session_id, role, content, run_id, context_version, metadata, created_at
`

type InsertAgentSessionMessageParams struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	SessionID      string             `json:"session_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	RunID          pgtype.Text        `json:"run_id"`
	ContextVersion int64              `json:"context_version"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAgentSessionMessage(ctx context.Context, arg InsertAgentSessionMessageParams) (AgentSessionMessage, error) {
	row := q.db.QueryRow(ctx, insertAgentSessionMessage,
		arg.ID,
		arg.TenantID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.RunID,
		arg.ContextVersion,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i AgentSessionMessage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.RunID,
		&i.ContextVersion,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentMemoriesByAccount = `-- name: ListAgentMemoriesByAccount :many
SELECT id, tenant_id, account_id, agent_id, session_id, key, content, source, importance, expires_at, created_at, updated_at FROM agent_memories
WHERE tenant_id = $1
  AND account_id = $2
  AND ($3::text = '' OR agent_id = $3 OR agent_id IS NULL OR agent_id = '')
  AND ($4::text = '' OR session_id = $4)
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY importance DESC, updated_at DESC, id DESC
LIMIT $5::int
`

type ListAgentMemoriesByAccountParams struct {
	TenantID   string `json:"tenant_id"`
	AccountID  string `json:"account_id"`
	AgentID    string `json:"agent_id"`
	SessionID  string `json:"session_id"`
	LimitCount int32  `json:"limit_count"`
}

func (q *Queries) ListAgentMemoriesByAccount(ctx context.Context, arg ListAgentMemoriesByAccountParams) ([]AgentMemory, error) {
	rows, err := q.db.Query(ctx, listAgentMemoriesByAccount,
		arg.TenantID,
		arg.AccountID,
		arg.AgentID,
		arg.SessionID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentMemory
	for rows.Next() {
		var i AgentMemory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.AgentID,
			&i.SessionID,
			&i.Key,
			&i.Content,
			&i.Source,
			&i.Importance,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessionMessages = `-- name: ListAgentSessionMessages :many
SELECT messages.id, messages.tenant_id, messages.session_id, messages.role, messages.content, messages.run_id, messages.context_version, messages.metadata, messages.created_at
FROM agent_session_messages messages
JOIN agent_sessions sessions
  ON sessions.tenant_id = messages.tenant_id
 AND sessions.id = messages.session_id
WHERE messages.tenant_id = $1
  AND messages.session_id = $2
  AND messages.context_version = sessions.context_version
ORDER BY messages.created_at ASC, messages.id ASC
`

type ListAgentSessionMessagesParams struct {
	TenantID  string `json:"tenant_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) ListAgentSessionMessages(ctx context.Context, arg ListAgentSessionMessagesParams) ([]AgentSessionMessage, error) {
	rows, err := q.db.Query(ctx, listAgentSessionMessages, arg.TenantID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSessionMessage
	for rows.Next() {
		var i AgentSessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.RunID,
			&i.ContextVersion,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessionsByAccount = `-- name: ListAgentSessionsByAccount :many
SELECT id, tenant_id, account_id, agent_id, title, status, context_version, last_message_at, created_at, updated_at FROM agent_sessions
WHERE tenant_id = $1
  AND account_id = $2
  AND ($3::text = '' OR status = $3)
  AND ($4::text = '' OR agent_id = $4)
ORDER BY COALESCE(last_message_at, updated_at) DESC, id DESC
`

type ListAgentSessionsByAccountParams struct {
	TenantID  string `json:"tenant_id"`
	AccountID string `json:"account_id"`
	Status    string `json:"status"`
	AgentID   string `json:"agent_id"`
}

func (q *Queries) ListAgentSessionsByAccount(ctx context.Context, arg ListAgentSessionsByAccountParams) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listAgentSessionsByAccount,
		arg.TenantID,
		arg.AccountID,
		arg.Status,
		arg.AgentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSession
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.AgentID,
			&i.Title,
			&i.Status,
			&i.ContextVersion,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAgentSessionMessages = `-- name: ListRecentAgentSessionMessages :many
SELECT id, tenant_id, session_id, role, content, run_id, context_version, metadata, created_at FROM (
    SELECT messages.id, messages.tenant_id, messages.session_id, messages.role, messages.content, messages.run_id, messages.context_version, messages.metadata, messages.created_at
    FROM agent_session_messages messages
    JOIN agent_sessions sessions
      ON sessions.tenant_id = messages.tenant_id
     AND sessions.id = messages.session_id
    WHERE messages.tenant_id = $1
      AND messages.session_id = $2
      AND messages.context_version = sessions.context_version
    ORDER BY messages.created_at DESC, messages.id DESC
    LIMIT $3::int
) recent
ORDER BY created_at ASC, id ASC
`

type ListRecentAgentSessionMessagesParams struct {
	TenantID   string `json:"tenant_id"`
	SessionID  string `json:"session_id"`
	LimitCount int32  `json:"limit_count"`
}

func (q *Queries) ListRecentAgentSessionMessages(ctx context.Context, arg ListRecentAgentSessionMessagesParams) ([]AgentSessionMessage, error) {
	rows, err := q.db.Query(ctx, listRecentAgentSessionMessages, arg.TenantID, arg.SessionID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSessionMessage
	for rows.Next() {
		var i AgentSessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.RunID,
			&i.ContextVersion,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentMemory = `-- name: UpsertAgentMemory :one
INSERT INTO agent_memories (
    id, tenant_id, account_id, agent_id, session_id, key, content,
    source, importance, expires_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12
)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    account_id = EXCLUDED.account_id,
    agent_id = EXCLUDED.agent_id,
    session_id = EXCLUDED.session_id,
    key = EXCLUDED.key,
    content = EXCLUDED.content,
    source = EXCLUDED.source,
    importance = EXCLUDED.importance,
    expires_at = EXCLUDED.expires_at,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, tenant_id, account_id, agent_id, session_id, key, content, source, importance, expires_at, created_at, updated_at
`

type UpsertAgentMemoryParams struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	AccountID  string             `json:"account_id"`
	AgentID    pgtype.Text        `json:"agent_id"`
	SessionID  pgtype.Text        `json:"session_id"`
	Key        string             `json:"key"`
	Content    string             `json:"content"`
	Source     string             `json:"source"`
	Importance int32              `json:"importance"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAgentMemory(ctx context.Context, arg UpsertAgentMemoryParams) (AgentMemory, error) {
	row := q.db.QueryRow(ctx, upsertAgentMemory,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.AgentID,
		arg.SessionID,
		arg.Key,
		arg.Content,
		arg.Source,
		arg.Importance,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AgentMemory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.SessionID,
		&i.Key,
		&i.Content,
		&i.Source,
		&i.Importance,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentSession = `-- name: UpsertAgentSession :one
INSERT INTO agent_sessions (
    id, tenant_id, account_id, agent_id, title, status,
    context_version, last_message_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10
)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    account_id = EXCLUDED.account_id,
    agent_id = EXCLUDED.agent_id,
    title = EXCLUDED.title,
    status = EXCLUDED.status,
    context_version = EXCLUDED.context_version,
    last_message_at = EXCLUDED.last_message_at,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, tenant_id, account_id, agent_id, title, status, context_version, last_message_at, created_at, updated_at
`

type UpsertAgentSessionParams struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	AgentID        pgtype.Text        `json:"agent_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	ContextVersion int64              `json:"context_version"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAgentSession(ctx context.Context, arg UpsertAgentSessionParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, upsertAgentSession,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.AgentID,
		arg.Title,
		arg.Status,
		arg.ContextVersion,
		arg.LastMessageAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.Title,
		&i.Status,
		&i.ContextVersion,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
