// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendExecutionStepV2 = `-- name: AppendExecutionStepV2 :one
WITH locked_execution AS (
    SELECT id, tenant_id
    FROM conversation_executions
    WHERE conversation_executions.tenant_id = $10
      AND conversation_executions.id = $11
    FOR UPDATE
), next_sequence AS (
    SELECT locked_execution.id AS execution_id,
           locked_execution.tenant_id,
           COALESCE(max(steps.sequence_no), 0)::integer + 1 AS sequence_no
    FROM locked_execution
    LEFT JOIN conversation_execution_steps steps
      ON steps.tenant_id = locked_execution.tenant_id
     AND steps.execution_id = locked_execution.id
    GROUP BY locked_execution.id, locked_execution.tenant_id
)
INSERT INTO conversation_execution_steps (
    id, tenant_id, execution_id, parent_step_id, sequence_no, step_type,
    name, model_connection_id, external_tool_id, status,
    input_summary, output_summary, input_tokens, cached_tokens, output_tokens,
    started_at, completed_at, error_code, created_at
)
SELECT
    $1, next_sequence.tenant_id, next_sequence.execution_id,
    NULLIF($2::text, ''), next_sequence.sequence_no,
    $3, $4,
    NULLIF($5::text, ''),
    NULLIF($6::text, ''),
    'running', $7::jsonb, '{}'::jsonb,
    0, 0, 0, $8, NULL, '', $9
FROM next_sequence
RETURNING id, tenant_id, execution_id, parent_step_id, sequence_no, step_type, name, model_connection_id, external_tool_id, status, input_summary, output_summary, input_tokens, cached_tokens, output_tokens, started_at, completed_at, error_code, created_at
`

type AppendExecutionStepV2Params struct {
	ID                string             `json:"id"`
	ParentStepID      string             `json:"parent_step_id"`
	StepType          string             `json:"step_type"`
	Name              string             `json:"name"`
	ModelConnectionID string             `json:"model_connection_id"`
	ExternalToolID    string             `json:"external_tool_id"`
	InputSummary      []byte             `json:"input_summary"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	TenantID          string             `json:"tenant_id"`
	ExecutionID       string             `json:"execution_id"`
}

func (q *Queries) AppendExecutionStepV2(ctx context.Context, arg AppendExecutionStepV2Params) (ConversationExecutionStep, error) {
	row := q.db.QueryRow(ctx, appendExecutionStepV2,
		arg.ID,
		arg.ParentStepID,
		arg.StepType,
		arg.Name,
		arg.ModelConnectionID,
		arg.ExternalToolID,
		arg.InputSummary,
		arg.StartedAt,
		arg.CreatedAt,
		arg.TenantID,
		arg.ExecutionID,
	)
	var i ConversationExecutionStep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.ParentStepID,
		&i.SequenceNo,
		&i.StepType,
		&i.Name,
		&i.ModelConnectionID,
		&i.ExternalToolID,
		&i.Status,
		&i.InputSummary,
		&i.OutputSummary,
		&i.InputTokens,
		&i.CachedTokens,
		&i.OutputTokens,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const claimAgentConfirmationV2 = `-- name: ClaimAgentConfirmationV2 :one
WITH expired AS (
    UPDATE agent_confirmations confirmations
    SET status = 'expired', consumed_at = $1, updated_at = $1
    FROM conversations
    WHERE confirmations.tenant_id = $2
      AND confirmations.account_id = $3
      AND confirmations.id = $4
      AND confirmations.status = 'pending'
      AND confirmations.expires_at <= $1
      AND conversations.tenant_id = confirmations.tenant_id
      AND conversations.id = confirmations.conversation_id
      AND conversations.current_segment_id = confirmations.segment_id
    RETURNING confirmations.id, confirmations.tenant_id, confirmations.account_id, confirmations.conversation_id, confirmations.segment_id, confirmations.execution_id, confirmations.source_message_id, confirmations.kind, confirmations.title, confirmations.action, confirmations.public_payload, confirmations.action_payload, confirmations.result_payload, confirmations.status, confirmations.last_error, confirmations.expires_at, confirmations.consumed_at, confirmations.created_at, confirmations.updated_at
), claimed AS (
    UPDATE agent_confirmations confirmations
    SET status = 'executing', updated_at = $1
    FROM conversations
    WHERE confirmations.tenant_id = $2
      AND confirmations.account_id = $3
      AND confirmations.id = $4
      AND confirmations.status = 'pending'
      AND confirmations.expires_at > $1
      AND conversations.tenant_id = confirmations.tenant_id
      AND conversations.id = confirmations.conversation_id
      AND conversations.current_segment_id = confirmations.segment_id
    RETURNING confirmations.id, confirmations.tenant_id, confirmations.account_id, confirmations.conversation_id, confirmations.segment_id, confirmations.execution_id, confirmations.source_message_id, confirmations.kind, confirmations.title, confirmations.action, confirmations.public_payload, confirmations.action_payload, confirmations.result_payload, confirmations.status, confirmations.last_error, confirmations.expires_at, confirmations.consumed_at, confirmations.created_at, confirmations.updated_at
)
SELECT id, tenant_id, account_id, conversation_id, segment_id, execution_id, source_message_id, kind, title, action, public_payload, action_payload, result_payload, status, last_error, expires_at, consumed_at, created_at, updated_at FROM expired
UNION ALL
SELECT id, tenant_id, account_id, conversation_id, segment_id, execution_id, source_message_id, kind, title, action, public_payload, action_payload, result_payload, status, last_error, expires_at, consumed_at, created_at, updated_at FROM claimed
LIMIT 1
`

type ClaimAgentConfirmationV2Params struct {
	NowAt     pgtype.Timestamptz `json:"now_at"`
	TenantID  string             `json:"tenant_id"`
	AccountID string             `json:"account_id"`
	ID        string             `json:"id"`
}

type ClaimAgentConfirmationV2Row struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	ConversationID  string             `json:"conversation_id"`
	SegmentID       string             `json:"segment_id"`
	ExecutionID     pgtype.Text        `json:"execution_id"`
	SourceMessageID pgtype.Text        `json:"source_message_id"`
	Kind            string             `json:"kind"`
	Title           string             `json:"title"`
	Action          string             `json:"action"`
	PublicPayload   []byte             `json:"public_payload"`
	ActionPayload   []byte             `json:"action_payload"`
	ResultPayload   []byte             `json:"result_payload"`
	Status          string             `json:"status"`
	LastError       string             `json:"last_error"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ClaimAgentConfirmationV2(ctx context.Context, arg ClaimAgentConfirmationV2Params) (ClaimAgentConfirmationV2Row, error) {
	row := q.db.QueryRow(ctx, claimAgentConfirmationV2,
		arg.NowAt,
		arg.TenantID,
		arg.AccountID,
		arg.ID,
	)
	var i ClaimAgentConfirmationV2Row
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.ConversationID,
		&i.SegmentID,
		&i.ExecutionID,
		&i.SourceMessageID,
		&i.Kind,
		&i.Title,
		&i.Action,
		&i.PublicPayload,
		&i.ActionPayload,
		&i.ResultPayload,
		&i.Status,
		&i.LastError,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveAgentRunsBySession = `-- name: CountActiveAgentRunsBySession :one
SELECT count(*)
FROM conversation_executions
WHERE tenant_id = $1
  AND conversation_id = $2
  AND status IN ('queued', 'running')
`

type CountActiveAgentRunsBySessionParams struct {
	TenantID  string `json:"tenant_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) CountActiveAgentRunsBySession(ctx context.Context, arg CountActiveAgentRunsBySessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAgentRunsBySession, arg.TenantID, arg.SessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgentUsageByAccount = `-- name: CountAgentUsageByAccount :one
SELECT count(*)::bigint
FROM accounts
WHERE tenant_id = $1
  AND ($2::text = '' OR lower(display_name || ' ' || email || ' ' || id) LIKE '%' || lower($2) || '%')
  AND ($3::text = '' OR status = $3)
`

type CountAgentUsageByAccountParams struct {
	TenantID      string `json:"tenant_id"`
	SearchQuery   string `json:"search_query"`
	AccountStatus string `json:"account_status"`
}

func (q *Queries) CountAgentUsageByAccount(ctx context.Context, arg CountAgentUsageByAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentUsageByAccount, arg.TenantID, arg.SearchQuery, arg.AccountStatus)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAgentUsageSessionsByAccount = `-- name: CountAgentUsageSessionsByAccount :one
SELECT count(*)::bigint
FROM conversations
WHERE tenant_id = $1
  AND owner_account_id = $2
`

type CountAgentUsageSessionsByAccountParams struct {
	TenantID  string `json:"tenant_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) CountAgentUsageSessionsByAccount(ctx context.Context, arg CountAgentUsageSessionsByAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentUsageSessionsByAccount, arg.TenantID, arg.AccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAgentMemory = `-- name: DeleteAgentMemory :one
WITH superseded AS (
    UPDATE agent_memories
    SET status = 'superseded', updated_at = GREATEST(updated_at, now())
    WHERE tenant_id = $1
      AND id = $2
    RETURNING id, tenant_id, account_id, scope_type, agent_id, conversation_id, segment_id, key, content, source_type, source_message_id, confidence, importance, status, expires_at, created_at, updated_at
)
SELECT
    id, tenant_id, account_id, agent_id, conversation_id AS session_id, segment_id,
    scope_type AS scope, source_message_id, confidence, status,
    key, content,
    CASE WHEN source_type = 'manual' THEN 'manual' ELSE 'auto' END::text AS source,
    importance, expires_at, created_at, updated_at
FROM superseded
`

type DeleteAgentMemoryParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

type DeleteAgentMemoryRow struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	AgentID         pgtype.Text        `json:"agent_id"`
	SessionID       pgtype.Text        `json:"session_id"`
	SegmentID       pgtype.Text        `json:"segment_id"`
	Scope           string             `json:"scope"`
	SourceMessageID pgtype.Text        `json:"source_message_id"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Status          string             `json:"status"`
	Key             string             `json:"key"`
	Content         string             `json:"content"`
	Source          string             `json:"source"`
	Importance      int32              `json:"importance"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeleteAgentMemory(ctx context.Context, arg DeleteAgentMemoryParams) (DeleteAgentMemoryRow, error) {
	row := q.db.QueryRow(ctx, deleteAgentMemory, arg.TenantID, arg.ID)
	var i DeleteAgentMemoryRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.SessionID,
		&i.SegmentID,
		&i.Scope,
		&i.SourceMessageID,
		&i.Confidence,
		&i.Status,
		&i.Key,
		&i.Content,
		&i.Source,
		&i.Importance,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentSession = `-- name: DeleteAgentSession :one
WITH archived AS (
    UPDATE conversations
    SET status = 'archived',
        archived_at = COALESCE(archived_at, now()),
        updated_at = GREATEST(updated_at, now())
    WHERE conversations.tenant_id = $1
      AND conversations.id = $2
    RETURNING id, tenant_id, owner_account_id, agent_id, current_segment_id, next_message_sequence, title, status, last_message_at, created_at, updated_at, archived_at
)
SELECT
    archived.id,
    archived.tenant_id,
    archived.owner_account_id AS account_id,
    archived.agent_id,
    segments.id AS segment_id,
    archived.title,
    archived.status,
    segments.ordinal::bigint AS context_version,
    archived.last_message_at,
    archived.created_at,
    archived.updated_at
FROM archived
JOIN conversation_segments segments
  ON segments.tenant_id = archived.tenant_id
 AND segments.conversation_id = archived.id
 AND segments.id = archived.current_segment_id
`

type DeleteAgentSessionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

type DeleteAgentSessionRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	AgentID        pgtype.Text        `json:"agent_id"`
	SegmentID      string             `json:"segment_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	ContextVersion int64              `json:"context_version"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeleteAgentSession(ctx context.Context, arg DeleteAgentSessionParams) (DeleteAgentSessionRow, error) {
	row := q.db.QueryRow(ctx, deleteAgentSession, arg.TenantID, arg.ID)
	var i DeleteAgentSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.SegmentID,
		&i.Title,
		&i.Status,
		&i.ContextVersion,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentMemory = `-- name: GetAgentMemory :one
SELECT
    id, tenant_id, account_id, agent_id, conversation_id AS session_id, segment_id,
    scope_type AS scope, source_message_id, confidence, status,
    key, content,
    CASE WHEN source_type = 'manual' THEN 'manual' ELSE 'auto' END::text AS source,
    importance, expires_at, created_at, updated_at
FROM agent_memories
WHERE agent_memories.tenant_id = $1
  AND agent_memories.id = $2
`

type GetAgentMemoryParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

type GetAgentMemoryRow struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	AgentID         pgtype.Text        `json:"agent_id"`
	SessionID       pgtype.Text        `json:"session_id"`
	SegmentID       pgtype.Text        `json:"segment_id"`
	Scope           string             `json:"scope"`
	SourceMessageID pgtype.Text        `json:"source_message_id"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Status          string             `json:"status"`
	Key             string             `json:"key"`
	Content         string             `json:"content"`
	Source          string             `json:"source"`
	Importance      int32              `json:"importance"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAgentMemory(ctx context.Context, arg GetAgentMemoryParams) (GetAgentMemoryRow, error) {
	row := q.db.QueryRow(ctx, getAgentMemory, arg.TenantID, arg.ID)
	var i GetAgentMemoryRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.SessionID,
		&i.SegmentID,
		&i.Scope,
		&i.SourceMessageID,
		&i.Confidence,
		&i.Status,
		&i.Key,
		&i.Content,
		&i.Source,
		&i.Importance,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentSession = `-- name: GetAgentSession :one
SELECT
    conversations.id,
    conversations.tenant_id,
    conversations.owner_account_id AS account_id,
    conversations.agent_id,
    segments.id AS segment_id,
    conversations.title,
    conversations.status,
    segments.ordinal::bigint AS context_version,
    conversations.last_message_at,
    conversations.created_at,
    conversations.updated_at
FROM conversations
JOIN conversation_segments segments
  ON segments.tenant_id = conversations.tenant_id
 AND segments.conversation_id = conversations.id
 AND segments.id = conversations.current_segment_id
WHERE conversations.tenant_id = $1
  AND conversations.id = $2
`

type GetAgentSessionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

type GetAgentSessionRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	AgentID        pgtype.Text        `json:"agent_id"`
	SegmentID      string             `json:"segment_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	ContextVersion int64              `json:"context_version"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAgentSession(ctx context.Context, arg GetAgentSessionParams) (GetAgentSessionRow, error) {
	row := q.db.QueryRow(ctx, getAgentSession, arg.TenantID, arg.ID)
	var i GetAgentSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.SegmentID,
		&i.Title,
		&i.Status,
		&i.ContextVersion,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentSessionForUpdate = `-- name: GetAgentSessionForUpdate :one
SELECT
    conversations.id,
    conversations.tenant_id,
    conversations.owner_account_id AS account_id,
    conversations.agent_id,
    segments.id AS segment_id,
    conversations.title,
    conversations.status,
    segments.ordinal::bigint AS context_version,
    conversations.last_message_at,
    conversations.created_at,
    conversations.updated_at
FROM conversations
JOIN conversation_segments segments
  ON segments.tenant_id = conversations.tenant_id
 AND segments.conversation_id = conversations.id
 AND segments.id = conversations.current_segment_id
WHERE conversations.tenant_id = $1
  AND conversations.id = $2
FOR UPDATE OF conversations
`

type GetAgentSessionForUpdateParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

type GetAgentSessionForUpdateRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	AgentID        pgtype.Text        `json:"agent_id"`
	SegmentID      string             `json:"segment_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	ContextVersion int64              `json:"context_version"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAgentSessionForUpdate(ctx context.Context, arg GetAgentSessionForUpdateParams) (GetAgentSessionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAgentSessionForUpdate, arg.TenantID, arg.ID)
	var i GetAgentSessionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.SegmentID,
		&i.Title,
		&i.Status,
		&i.ContextVersion,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentUsageByAccount = `-- name: GetAgentUsageByAccount :one
WITH conversation_usage AS (
    SELECT owner_account_id AS account_id, count(*)::bigint AS session_count,
           max(COALESCE(last_message_at, updated_at))::timestamptz AS last_session_at
    FROM conversations
    WHERE tenant_id = $1
    GROUP BY owner_account_id
), message_usage AS (
    SELECT conversations.owner_account_id AS account_id, count(conversation_messages.id)::bigint AS message_count,
           max(conversation_messages.created_at)::timestamptz AS last_message_at
    FROM conversations
    JOIN conversation_messages ON conversation_messages.tenant_id = conversations.tenant_id AND conversation_messages.conversation_id = conversations.id
    WHERE conversations.tenant_id = $1
    GROUP BY conversations.owner_account_id
), execution_usage AS (
    SELECT account_id, sum(llm_call_count)::bigint AS llm_call_count,
           sum(input_tokens)::bigint AS input_tokens, sum(cached_tokens)::bigint AS cached_tokens,
           sum(output_tokens)::bigint AS output_tokens, sum(total_tokens)::bigint AS total_tokens,
           max(updated_at)::timestamptz AS last_execution_at
    FROM conversation_executions
    WHERE tenant_id = $1
    GROUP BY account_id
)
SELECT
    accounts.id AS account_id, accounts.display_name, accounts.email, accounts.status,
    COALESCE(conversation_usage.session_count, 0)::bigint AS session_count,
    COALESCE(message_usage.message_count, 0)::bigint AS message_count,
    COALESCE(execution_usage.llm_call_count, 0)::bigint AS llm_call_count,
    COALESCE(execution_usage.input_tokens, 0)::bigint AS input_tokens,
    COALESCE(execution_usage.cached_tokens, 0)::bigint AS cached_tokens,
    COALESCE(execution_usage.output_tokens, 0)::bigint AS output_tokens,
    COALESCE(execution_usage.total_tokens, 0)::bigint AS total_tokens,
    GREATEST(COALESCE(execution_usage.total_tokens, 0) - COALESCE(execution_usage.cached_tokens, 0), 0)::bigint AS actual_tokens,
    GREATEST(conversation_usage.last_session_at, message_usage.last_message_at, execution_usage.last_execution_at)::timestamptz AS last_active_at
FROM accounts
LEFT JOIN conversation_usage ON conversation_usage.account_id = accounts.id
LEFT JOIN message_usage ON message_usage.account_id = accounts.id
LEFT JOIN execution_usage ON execution_usage.account_id = accounts.id
WHERE accounts.tenant_id = $1
  AND accounts.id = $2
`

type GetAgentUsageByAccountParams struct {
	TenantID  string `json:"tenant_id"`
	AccountID string `json:"account_id"`
}

type GetAgentUsageByAccountRow struct {
	AccountID    string             `json:"account_id"`
	DisplayName  string             `json:"display_name"`
	Email        string             `json:"email"`
	Status       string             `json:"status"`
	SessionCount int64              `json:"session_count"`
	MessageCount int64              `json:"message_count"`
	LlmCallCount int64              `json:"llm_call_count"`
	InputTokens  int64              `json:"input_tokens"`
	CachedTokens int64              `json:"cached_tokens"`
	OutputTokens int64              `json:"output_tokens"`
	TotalTokens  int64              `json:"total_tokens"`
	ActualTokens int64              `json:"actual_tokens"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) GetAgentUsageByAccount(ctx context.Context, arg GetAgentUsageByAccountParams) (GetAgentUsageByAccountRow, error) {
	row := q.db.QueryRow(ctx, getAgentUsageByAccount, arg.TenantID, arg.AccountID)
	var i GetAgentUsageByAccountRow
	err := row.Scan(
		&i.AccountID,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.SessionCount,
		&i.MessageCount,
		&i.LlmCallCount,
		&i.InputTokens,
		&i.CachedTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.ActualTokens,
		&i.LastActiveAt,
	)
	return i, err
}

const getAgentUsageSummary = `-- name: GetAgentUsageSummary :one
WITH conversation_usage AS (
    SELECT owner_account_id AS account_id, count(*)::bigint AS session_count
    FROM conversations WHERE conversations.tenant_id = $1 GROUP BY conversations.owner_account_id
), message_usage AS (
    SELECT conversations.owner_account_id AS account_id, count(conversation_messages.id)::bigint AS message_count
    FROM conversations
    JOIN conversation_messages ON conversation_messages.tenant_id = conversations.tenant_id AND conversation_messages.conversation_id = conversations.id
    WHERE conversations.tenant_id = $1
    GROUP BY conversations.owner_account_id
), execution_usage AS (
    SELECT account_id, sum(llm_call_count)::bigint AS llm_call_count,
           sum(input_tokens)::bigint AS input_tokens, sum(cached_tokens)::bigint AS cached_tokens,
           sum(output_tokens)::bigint AS output_tokens, sum(total_tokens)::bigint AS total_tokens
    FROM conversation_executions WHERE tenant_id = $1 GROUP BY account_id
), account_usage AS (
    SELECT
        COALESCE(conversation_usage.session_count, 0)::bigint AS session_count,
        COALESCE(message_usage.message_count, 0)::bigint AS message_count,
        COALESCE(execution_usage.llm_call_count, 0)::bigint AS llm_call_count,
        COALESCE(execution_usage.input_tokens, 0)::bigint AS input_tokens,
        COALESCE(execution_usage.cached_tokens, 0)::bigint AS cached_tokens,
        COALESCE(execution_usage.output_tokens, 0)::bigint AS output_tokens,
        COALESCE(execution_usage.total_tokens, 0)::bigint AS total_tokens,
        GREATEST(COALESCE(execution_usage.total_tokens, 0) - COALESCE(execution_usage.cached_tokens, 0), 0)::bigint AS actual_tokens
    FROM accounts
    LEFT JOIN conversation_usage ON conversation_usage.account_id = accounts.id
    LEFT JOIN message_usage ON message_usage.account_id = accounts.id
    LEFT JOIN execution_usage ON execution_usage.account_id = accounts.id
    WHERE accounts.tenant_id = $1
)
SELECT
    count(*)::bigint AS user_count,
    count(*) FILTER (WHERE session_count > 0 OR message_count > 0)::bigint AS users_with_usage,
    COALESCE(sum(session_count), 0)::bigint AS session_count,
    COALESCE(sum(message_count), 0)::bigint AS message_count,
    COALESCE(sum(llm_call_count), 0)::bigint AS llm_call_count,
    COALESCE(sum(input_tokens), 0)::bigint AS input_tokens,
    COALESCE(sum(cached_tokens), 0)::bigint AS cached_tokens,
    COALESCE(sum(output_tokens), 0)::bigint AS output_tokens,
    COALESCE(sum(total_tokens), 0)::bigint AS total_tokens,
    COALESCE(sum(actual_tokens), 0)::bigint AS actual_tokens
FROM account_usage
`

type GetAgentUsageSummaryRow struct {
	UserCount      int64 `json:"user_count"`
	UsersWithUsage int64 `json:"users_with_usage"`
	SessionCount   int64 `json:"session_count"`
	MessageCount   int64 `json:"message_count"`
	LlmCallCount   int64 `json:"llm_call_count"`
	InputTokens    int64 `json:"input_tokens"`
	CachedTokens   int64 `json:"cached_tokens"`
	OutputTokens   int64 `json:"output_tokens"`
	TotalTokens    int64 `json:"total_tokens"`
	ActualTokens   int64 `json:"actual_tokens"`
}

func (q *Queries) GetAgentUsageSummary(ctx context.Context, tenantID string) (GetAgentUsageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAgentUsageSummary, tenantID)
	var i GetAgentUsageSummaryRow
	err := row.Scan(
		&i.UserCount,
		&i.UsersWithUsage,
		&i.SessionCount,
		&i.MessageCount,
		&i.LlmCallCount,
		&i.InputTokens,
		&i.CachedTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.ActualTokens,
	)
	return i, err
}

const getExecutionStepV2 = `-- name: GetExecutionStepV2 :one
SELECT id, tenant_id, execution_id, parent_step_id, sequence_no, step_type, name, model_connection_id, external_tool_id, status, input_summary, output_summary, input_tokens, cached_tokens, output_tokens, started_at, completed_at, error_code, created_at
FROM conversation_execution_steps
WHERE tenant_id = $1 AND id = $2
`

type GetExecutionStepV2Params struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetExecutionStepV2(ctx context.Context, arg GetExecutionStepV2Params) (ConversationExecutionStep, error) {
	row := q.db.QueryRow(ctx, getExecutionStepV2, arg.TenantID, arg.ID)
	var i ConversationExecutionStep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.ParentStepID,
		&i.SequenceNo,
		&i.StepType,
		&i.Name,
		&i.ModelConnectionID,
		&i.ExternalToolID,
		&i.Status,
		&i.InputSummary,
		&i.OutputSummary,
		&i.InputTokens,
		&i.CachedTokens,
		&i.OutputTokens,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const insertAgentSessionMessage = `-- name: InsertAgentSessionMessage :one
WITH allocated AS (
    UPDATE conversations
    SET next_message_sequence = next_message_sequence + 1,
        last_message_at = GREATEST(COALESCE(last_message_at, $1::timestamptz), $1::timestamptz),
        updated_at = GREATEST(updated_at, $1::timestamptz)
    WHERE conversations.tenant_id = $2
      AND conversations.id = $3
    RETURNING id, tenant_id, owner_account_id, agent_id, current_segment_id, next_message_sequence, title, status, last_message_at, created_at, updated_at, archived_at, next_message_sequence - 1 AS allocated_sequence
), inserted AS (
    INSERT INTO conversation_messages (
        id, tenant_id, conversation_id, segment_id, sequence_no, role,
        content, content_json, execution_id, execution_step_id, created_at
    )
    SELECT
        $4, allocated.tenant_id, allocated.id, allocated.current_segment_id,
        allocated.allocated_sequence, $5, $6,
        $7::jsonb,
        conversation_executions.id, NULL, $1
    FROM allocated
    LEFT JOIN conversation_executions
      ON conversation_executions.tenant_id = allocated.tenant_id
     AND conversation_executions.conversation_id = allocated.id
     AND conversation_executions.segment_id = allocated.current_segment_id
     AND conversation_executions.id = NULLIF($8::text, '')
    RETURNING id, tenant_id, conversation_id, segment_id, sequence_no, role, content, content_json, execution_id, execution_step_id, created_at
)
SELECT
    inserted.id,
    inserted.tenant_id,
    inserted.conversation_id AS session_id,
    inserted.segment_id,
    inserted.sequence_no,
    inserted.role,
    inserted.content,
    inserted.execution_id AS run_id,
    segments.ordinal::bigint AS context_version,
    COALESCE(inserted.content_json, '{}'::jsonb) AS metadata,
    inserted.created_at
FROM inserted
JOIN conversation_segments segments
  ON segments.tenant_id = inserted.tenant_id
 AND segments.conversation_id = inserted.conversation_id
 AND segments.id = inserted.segment_id
`

type InsertAgentSessionMessageParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  string             `json:"tenant_id"`
	SessionID string             `json:"session_id"`
	ID        string             `json:"id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	Metadata  []byte             `json:"metadata"`
	RunID     string             `json:"run_id"`
}

type InsertAgentSessionMessageRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	SessionID      string             `json:"session_id"`
	SegmentID      string             `json:"segment_id"`
	SequenceNo     int64              `json:"sequence_no"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	RunID          pgtype.Text        `json:"run_id"`
	ContextVersion int64              `json:"context_version"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAgentSessionMessage(ctx context.Context, arg InsertAgentSessionMessageParams) (InsertAgentSessionMessageRow, error) {
	row := q.db.QueryRow(ctx, insertAgentSessionMessage,
		arg.CreatedAt,
		arg.TenantID,
		arg.SessionID,
		arg.ID,
		arg.Role,
		arg.Content,
		arg.Metadata,
		arg.RunID,
	)
	var i InsertAgentSessionMessageRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.SegmentID,
		&i.SequenceNo,
		&i.Role,
		&i.Content,
		&i.RunID,
		&i.ContextVersion,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentMemoriesByAccount = `-- name: ListAgentMemoriesByAccount :many
SELECT
    id, tenant_id, account_id, agent_id, conversation_id AS session_id, segment_id,
    scope_type AS scope, source_message_id, confidence, status,
    key, content,
    CASE WHEN source_type = 'manual' THEN 'manual' ELSE 'auto' END::text AS source,
    importance, expires_at, created_at, updated_at
FROM agent_memories
WHERE agent_memories.tenant_id = $1
  AND agent_memories.account_id = $2
  AND agent_memories.status = 'active'
  AND (
      agent_memories.scope_type = 'global'
      OR (
          agent_memories.scope_type = 'agent'
          AND $3::text <> ''
          AND agent_memories.agent_id = $3
      )
      OR (
          agent_memories.scope_type = 'conversation'
          AND $4::text <> ''
          AND agent_memories.conversation_id = $4
          AND agent_memories.segment_id = (
              SELECT conversations.current_segment_id
              FROM conversations
              WHERE conversations.tenant_id = $1
                AND conversations.id = $4
          )
      )
  )
  AND (agent_memories.expires_at IS NULL OR agent_memories.expires_at > now())
ORDER BY agent_memories.importance DESC, agent_memories.updated_at DESC, agent_memories.id DESC
LIMIT $5::int
`

type ListAgentMemoriesByAccountParams struct {
	TenantID   string `json:"tenant_id"`
	AccountID  string `json:"account_id"`
	AgentID    string `json:"agent_id"`
	SessionID  string `json:"session_id"`
	LimitCount int32  `json:"limit_count"`
}

type ListAgentMemoriesByAccountRow struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	AgentID         pgtype.Text        `json:"agent_id"`
	SessionID       pgtype.Text        `json:"session_id"`
	SegmentID       pgtype.Text        `json:"segment_id"`
	Scope           string             `json:"scope"`
	SourceMessageID pgtype.Text        `json:"source_message_id"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Status          string             `json:"status"`
	Key             string             `json:"key"`
	Content         string             `json:"content"`
	Source          string             `json:"source"`
	Importance      int32              `json:"importance"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAgentMemoriesByAccount(ctx context.Context, arg ListAgentMemoriesByAccountParams) ([]ListAgentMemoriesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listAgentMemoriesByAccount,
		arg.TenantID,
		arg.AccountID,
		arg.AgentID,
		arg.SessionID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentMemoriesByAccountRow
	for rows.Next() {
		var i ListAgentMemoriesByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.AgentID,
			&i.SessionID,
			&i.SegmentID,
			&i.Scope,
			&i.SourceMessageID,
			&i.Confidence,
			&i.Status,
			&i.Key,
			&i.Content,
			&i.Source,
			&i.Importance,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessionMessages = `-- name: ListAgentSessionMessages :many
SELECT
    conversation_messages.id,
    conversation_messages.tenant_id,
    conversation_messages.conversation_id AS session_id,
    conversation_messages.segment_id,
    conversation_messages.sequence_no,
    conversation_messages.role,
    conversation_messages.content,
    conversation_messages.execution_id AS run_id,
    segments.ordinal::bigint AS context_version,
    COALESCE(conversation_messages.content_json, '{}'::jsonb) AS metadata,
    conversation_messages.created_at
FROM conversation_messages
JOIN conversations
  ON conversations.tenant_id = conversation_messages.tenant_id
 AND conversations.id = conversation_messages.conversation_id
JOIN conversation_segments segments
  ON segments.tenant_id = conversation_messages.tenant_id
 AND segments.conversation_id = conversation_messages.conversation_id
 AND segments.id = conversation_messages.segment_id
WHERE conversation_messages.tenant_id = $1
  AND conversation_messages.conversation_id = $2
  AND conversation_messages.segment_id = conversations.current_segment_id
  AND (
    NOT $3::boolean
    OR conversation_messages.created_at > $4::timestamptz
    OR (conversation_messages.created_at = $4::timestamptz AND conversation_messages.id > $5)
  )
ORDER BY conversation_messages.created_at ASC, conversation_messages.id ASC
LIMIT $6::int
`

type ListAgentSessionMessagesParams struct {
	TenantID        string             `json:"tenant_id"`
	SessionID       string             `json:"session_id"`
	HasCursor       bool               `json:"has_cursor"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	LimitCount      int32              `json:"limit_count"`
}

type ListAgentSessionMessagesRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	SessionID      string             `json:"session_id"`
	SegmentID      string             `json:"segment_id"`
	SequenceNo     int64              `json:"sequence_no"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	RunID          pgtype.Text        `json:"run_id"`
	ContextVersion int64              `json:"context_version"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAgentSessionMessages(ctx context.Context, arg ListAgentSessionMessagesParams) ([]ListAgentSessionMessagesRow, error) {
	rows, err := q.db.Query(ctx, listAgentSessionMessages,
		arg.TenantID,
		arg.SessionID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentSessionMessagesRow
	for rows.Next() {
		var i ListAgentSessionMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SessionID,
			&i.SegmentID,
			&i.SequenceNo,
			&i.Role,
			&i.Content,
			&i.RunID,
			&i.ContextVersion,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessionsByAccount = `-- name: ListAgentSessionsByAccount :many
SELECT
    conversations.id,
    conversations.tenant_id,
    conversations.owner_account_id AS account_id,
    conversations.agent_id,
    segments.id AS segment_id,
    conversations.title,
    conversations.status,
    segments.ordinal::bigint AS context_version,
    conversations.last_message_at,
    conversations.created_at,
    conversations.updated_at
FROM conversations
JOIN conversation_segments segments
  ON segments.tenant_id = conversations.tenant_id
 AND segments.conversation_id = conversations.id
 AND segments.id = conversations.current_segment_id
WHERE conversations.tenant_id = $1
  AND conversations.owner_account_id = $2
  AND ($3::text = '' OR conversations.status = $3)
  AND ($4::text = '' OR conversations.agent_id = $4)
  AND (
    NOT $5::boolean
    OR conversations.created_at < $6::timestamptz
    OR (conversations.created_at = $6::timestamptz AND conversations.id < $7)
  )
ORDER BY conversations.created_at DESC, conversations.id DESC
LIMIT $8::int
`

type ListAgentSessionsByAccountParams struct {
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	Status          string             `json:"status"`
	AgentID         string             `json:"agent_id"`
	HasCursor       bool               `json:"has_cursor"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	LimitCount      int32              `json:"limit_count"`
}

type ListAgentSessionsByAccountRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	AgentID        pgtype.Text        `json:"agent_id"`
	SegmentID      string             `json:"segment_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	ContextVersion int64              `json:"context_version"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAgentSessionsByAccount(ctx context.Context, arg ListAgentSessionsByAccountParams) ([]ListAgentSessionsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listAgentSessionsByAccount,
		arg.TenantID,
		arg.AccountID,
		arg.Status,
		arg.AgentID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentSessionsByAccountRow
	for rows.Next() {
		var i ListAgentSessionsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.AgentID,
			&i.SegmentID,
			&i.Title,
			&i.Status,
			&i.ContextVersion,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentUsageByAccount = `-- name: ListAgentUsageByAccount :many
WITH conversation_usage AS (
    SELECT
        owner_account_id AS account_id,
        count(*)::bigint AS session_count,
        max(COALESCE(last_message_at, updated_at))::timestamptz AS last_session_at
    FROM conversations
    WHERE conversations.tenant_id = $6
    GROUP BY conversations.owner_account_id
), message_usage AS (
    SELECT
        conversations.owner_account_id AS account_id,
        count(conversation_messages.id)::bigint AS message_count,
        max(conversation_messages.created_at)::timestamptz AS last_message_at
    FROM conversations
    JOIN conversation_messages
      ON conversation_messages.tenant_id = conversations.tenant_id
     AND conversation_messages.conversation_id = conversations.id
    WHERE conversations.tenant_id = $6
    GROUP BY conversations.owner_account_id
), execution_usage AS (
    SELECT
        account_id,
        sum(llm_call_count)::bigint AS llm_call_count,
        sum(input_tokens)::bigint AS input_tokens,
        sum(cached_tokens)::bigint AS cached_tokens,
        sum(output_tokens)::bigint AS output_tokens,
        sum(total_tokens)::bigint AS total_tokens,
        max(updated_at)::timestamptz AS last_execution_at
    FROM conversation_executions
    WHERE tenant_id = $6
    GROUP BY account_id
), account_usage AS (
    SELECT
        accounts.id AS account_id,
        accounts.display_name,
        accounts.email,
        accounts.status,
        COALESCE(conversation_usage.session_count, 0)::bigint AS session_count,
        COALESCE(message_usage.message_count, 0)::bigint AS message_count,
        COALESCE(execution_usage.llm_call_count, 0)::bigint AS llm_call_count,
        COALESCE(execution_usage.input_tokens, 0)::bigint AS input_tokens,
        COALESCE(execution_usage.cached_tokens, 0)::bigint AS cached_tokens,
        COALESCE(execution_usage.output_tokens, 0)::bigint AS output_tokens,
        COALESCE(execution_usage.total_tokens, 0)::bigint AS total_tokens,
        GREATEST(COALESCE(execution_usage.total_tokens, 0) - COALESCE(execution_usage.cached_tokens, 0), 0)::bigint AS actual_tokens,
        GREATEST(conversation_usage.last_session_at, message_usage.last_message_at, execution_usage.last_execution_at)::timestamptz AS last_active_at
    FROM accounts
    LEFT JOIN conversation_usage ON conversation_usage.account_id = accounts.id
    LEFT JOIN message_usage ON message_usage.account_id = accounts.id
    LEFT JOIN execution_usage ON execution_usage.account_id = accounts.id
    WHERE accounts.tenant_id = $6
)
SELECT account_id, display_name, email, status, session_count, message_count, llm_call_count, input_tokens, cached_tokens, output_tokens, total_tokens, actual_tokens, last_active_at
FROM account_usage
WHERE ($1::text = '' OR lower(display_name || ' ' || email || ' ' || account_id) LIKE '%' || lower($1) || '%')
  AND ($2::text = '' OR status = $2)
ORDER BY
    CASE WHEN $3::text = 'session_count_asc' THEN session_count END ASC,
    CASE WHEN $3::text IN ('usage_desc', 'session_count_desc') THEN session_count END DESC,
    CASE WHEN $3::text = 'message_count_asc' THEN message_count END ASC,
    CASE WHEN $3::text IN ('usage_desc', 'message_count_desc') THEN message_count END DESC,
    CASE WHEN $3::text = 'total_tokens_asc' THEN total_tokens END ASC,
    CASE WHEN $3::text = 'total_tokens_desc' THEN total_tokens END DESC,
    CASE WHEN $3::text = 'cached_tokens_asc' THEN cached_tokens END ASC,
    CASE WHEN $3::text = 'cached_tokens_desc' THEN cached_tokens END DESC,
    CASE WHEN $3::text = 'actual_tokens_asc' THEN actual_tokens END ASC,
    CASE WHEN $3::text = 'actual_tokens_desc' THEN actual_tokens END DESC,
    CASE WHEN $3::text = 'last_active_at_asc' THEN last_active_at END ASC NULLS LAST,
    CASE WHEN $3::text = 'last_active_at_desc' THEN last_active_at END DESC NULLS LAST,
    lower(display_name), account_id
LIMIT $5::int
OFFSET $4::int
`

type ListAgentUsageByAccountParams struct {
	SearchQuery   string `json:"search_query"`
	AccountStatus string `json:"account_status"`
	SortOrder     string `json:"sort_order"`
	OffsetCount   int32  `json:"offset_count"`
	LimitCount    int32  `json:"limit_count"`
	TenantID      string `json:"tenant_id"`
}

type ListAgentUsageByAccountRow struct {
	AccountID    string             `json:"account_id"`
	DisplayName  string             `json:"display_name"`
	Email        string             `json:"email"`
	Status       string             `json:"status"`
	SessionCount int64              `json:"session_count"`
	MessageCount int64              `json:"message_count"`
	LlmCallCount int64              `json:"llm_call_count"`
	InputTokens  int64              `json:"input_tokens"`
	CachedTokens int64              `json:"cached_tokens"`
	OutputTokens int64              `json:"output_tokens"`
	TotalTokens  int64              `json:"total_tokens"`
	ActualTokens int64              `json:"actual_tokens"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) ListAgentUsageByAccount(ctx context.Context, arg ListAgentUsageByAccountParams) ([]ListAgentUsageByAccountRow, error) {
	rows, err := q.db.Query(ctx, listAgentUsageByAccount,
		arg.SearchQuery,
		arg.AccountStatus,
		arg.SortOrder,
		arg.OffsetCount,
		arg.LimitCount,
		arg.TenantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentUsageByAccountRow
	for rows.Next() {
		var i ListAgentUsageByAccountRow
		if err := rows.Scan(
			&i.AccountID,
			&i.DisplayName,
			&i.Email,
			&i.Status,
			&i.SessionCount,
			&i.MessageCount,
			&i.LlmCallCount,
			&i.InputTokens,
			&i.CachedTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.ActualTokens,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentUsageBySession = `-- name: ListAgentUsageBySession :many
WITH account_conversations AS (
    SELECT id
    FROM conversations
    WHERE tenant_id = $1 AND owner_account_id = $2
), message_usage AS (
    SELECT conversation_messages.conversation_id, count(*)::bigint AS message_count,
           max(conversation_messages.created_at)::timestamptz AS last_message_at
    FROM conversation_messages
    JOIN account_conversations ON account_conversations.id = conversation_messages.conversation_id
    WHERE conversation_messages.tenant_id = $1
    GROUP BY conversation_messages.conversation_id
), execution_usage AS (
    SELECT conversation_executions.conversation_id, sum(llm_call_count)::bigint AS llm_call_count,
           sum(input_tokens)::bigint AS input_tokens, sum(cached_tokens)::bigint AS cached_tokens,
           sum(output_tokens)::bigint AS output_tokens, sum(total_tokens)::bigint AS total_tokens,
           max(updated_at)::timestamptz AS last_execution_at
    FROM conversation_executions
    JOIN account_conversations ON account_conversations.id = conversation_executions.conversation_id
    WHERE conversation_executions.tenant_id = $1
    GROUP BY conversation_executions.conversation_id
)
SELECT
    conversations.id AS session_id,
    conversations.owner_account_id AS account_id,
    conversations.title,
    conversations.status,
    COALESCE(message_usage.message_count, 0)::bigint AS message_count,
    COALESCE(execution_usage.llm_call_count, 0)::bigint AS llm_call_count,
    COALESCE(execution_usage.input_tokens, 0)::bigint AS input_tokens,
    COALESCE(execution_usage.cached_tokens, 0)::bigint AS cached_tokens,
    COALESCE(execution_usage.output_tokens, 0)::bigint AS output_tokens,
    COALESCE(execution_usage.total_tokens, 0)::bigint AS total_tokens,
    GREATEST(COALESCE(execution_usage.total_tokens, 0) - COALESCE(execution_usage.cached_tokens, 0), 0)::bigint AS actual_tokens,
    GREATEST(COALESCE(conversations.last_message_at, conversations.updated_at), message_usage.last_message_at, execution_usage.last_execution_at)::timestamptz AS last_active_at
FROM conversations
LEFT JOIN message_usage ON message_usage.conversation_id = conversations.id
LEFT JOIN execution_usage ON execution_usage.conversation_id = conversations.id
WHERE conversations.tenant_id = $1
  AND conversations.owner_account_id = $2
ORDER BY last_active_at DESC, conversations.id DESC
LIMIT $4::int
OFFSET $3::int
`

type ListAgentUsageBySessionParams struct {
	TenantID    string `json:"tenant_id"`
	AccountID   string `json:"account_id"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

type ListAgentUsageBySessionRow struct {
	SessionID    string             `json:"session_id"`
	AccountID    string             `json:"account_id"`
	Title        string             `json:"title"`
	Status       string             `json:"status"`
	MessageCount int64              `json:"message_count"`
	LlmCallCount int64              `json:"llm_call_count"`
	InputTokens  int64              `json:"input_tokens"`
	CachedTokens int64              `json:"cached_tokens"`
	OutputTokens int64              `json:"output_tokens"`
	TotalTokens  int64              `json:"total_tokens"`
	ActualTokens int64              `json:"actual_tokens"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) ListAgentUsageBySession(ctx context.Context, arg ListAgentUsageBySessionParams) ([]ListAgentUsageBySessionRow, error) {
	rows, err := q.db.Query(ctx, listAgentUsageBySession,
		arg.TenantID,
		arg.AccountID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentUsageBySessionRow
	for rows.Next() {
		var i ListAgentUsageBySessionRow
		if err := rows.Scan(
			&i.SessionID,
			&i.AccountID,
			&i.Title,
			&i.Status,
			&i.MessageCount,
			&i.LlmCallCount,
			&i.InputTokens,
			&i.CachedTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.ActualTokens,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionStepsV2 = `-- name: ListExecutionStepsV2 :many
SELECT id, tenant_id, execution_id, parent_step_id, sequence_no, step_type, name, model_connection_id, external_tool_id, status, input_summary, output_summary, input_tokens, cached_tokens, output_tokens, started_at, completed_at, error_code, created_at
FROM conversation_execution_steps
WHERE tenant_id = $1 AND execution_id = $2
ORDER BY sequence_no, id
`

type ListExecutionStepsV2Params struct {
	TenantID    string `json:"tenant_id"`
	ExecutionID string `json:"execution_id"`
}

func (q *Queries) ListExecutionStepsV2(ctx context.Context, arg ListExecutionStepsV2Params) ([]ConversationExecutionStep, error) {
	rows, err := q.db.Query(ctx, listExecutionStepsV2, arg.TenantID, arg.ExecutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationExecutionStep
	for rows.Next() {
		var i ConversationExecutionStep
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExecutionID,
			&i.ParentStepID,
			&i.SequenceNo,
			&i.StepType,
			&i.Name,
			&i.ModelConnectionID,
			&i.ExternalToolID,
			&i.Status,
			&i.InputSummary,
			&i.OutputSummary,
			&i.InputTokens,
			&i.CachedTokens,
			&i.OutputTokens,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAgentConfirmationsV2 = `-- name: ListPendingAgentConfirmationsV2 :many
SELECT confirmations.id, confirmations.tenant_id, confirmations.account_id, confirmations.conversation_id, confirmations.segment_id, confirmations.execution_id, confirmations.source_message_id, confirmations.kind, confirmations.title, confirmations.action, confirmations.public_payload, confirmations.action_payload, confirmations.result_payload, confirmations.status, confirmations.last_error, confirmations.expires_at, confirmations.consumed_at, confirmations.created_at, confirmations.updated_at
FROM agent_confirmations confirmations
JOIN conversations
  ON conversations.tenant_id = confirmations.tenant_id
 AND conversations.id = confirmations.conversation_id
 AND conversations.current_segment_id = confirmations.segment_id
WHERE confirmations.tenant_id = $1
  AND confirmations.account_id = $2
  AND confirmations.conversation_id = $3
  AND confirmations.segment_id = $4
  AND confirmations.status = 'pending'
  AND confirmations.expires_at > $5
ORDER BY confirmations.created_at, confirmations.id
`

type ListPendingAgentConfirmationsV2Params struct {
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	ConversationID string             `json:"conversation_id"`
	SegmentID      string             `json:"segment_id"`
	NowAt          pgtype.Timestamptz `json:"now_at"`
}

func (q *Queries) ListPendingAgentConfirmationsV2(ctx context.Context, arg ListPendingAgentConfirmationsV2Params) ([]AgentConfirmation, error) {
	rows, err := q.db.Query(ctx, listPendingAgentConfirmationsV2,
		arg.TenantID,
		arg.AccountID,
		arg.ConversationID,
		arg.SegmentID,
		arg.NowAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentConfirmation
	for rows.Next() {
		var i AgentConfirmation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.ConversationID,
			&i.SegmentID,
			&i.ExecutionID,
			&i.SourceMessageID,
			&i.Kind,
			&i.Title,
			&i.Action,
			&i.PublicPayload,
			&i.ActionPayload,
			&i.ResultPayload,
			&i.Status,
			&i.LastError,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAgentSessionMessages = `-- name: ListRecentAgentSessionMessages :many
SELECT id, tenant_id, session_id, segment_id, sequence_no, role, content, run_id, context_version, metadata, created_at FROM (
    SELECT
        conversation_messages.id,
        conversation_messages.tenant_id,
        conversation_messages.conversation_id AS session_id,
        conversation_messages.segment_id,
        conversation_messages.sequence_no,
        conversation_messages.role,
        conversation_messages.content,
        conversation_messages.execution_id AS run_id,
        segments.ordinal::bigint AS context_version,
        COALESCE(conversation_messages.content_json, '{}'::jsonb) AS metadata,
        conversation_messages.created_at
    FROM conversation_messages
    JOIN conversations
      ON conversations.tenant_id = conversation_messages.tenant_id
     AND conversations.id = conversation_messages.conversation_id
    JOIN conversation_segments segments
      ON segments.tenant_id = conversation_messages.tenant_id
     AND segments.conversation_id = conversation_messages.conversation_id
     AND segments.id = conversation_messages.segment_id
    WHERE conversation_messages.tenant_id = $1
      AND conversation_messages.conversation_id = $2
      AND conversation_messages.segment_id = conversations.current_segment_id
    ORDER BY conversation_messages.created_at DESC, conversation_messages.id DESC
    LIMIT $3::int
) recent
ORDER BY created_at ASC, id ASC
`

type ListRecentAgentSessionMessagesParams struct {
	TenantID   string `json:"tenant_id"`
	SessionID  string `json:"session_id"`
	LimitCount int32  `json:"limit_count"`
}

type ListRecentAgentSessionMessagesRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	SessionID      string             `json:"session_id"`
	SegmentID      string             `json:"segment_id"`
	SequenceNo     int64              `json:"sequence_no"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	RunID          pgtype.Text        `json:"run_id"`
	ContextVersion int64              `json:"context_version"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecentAgentSessionMessages(ctx context.Context, arg ListRecentAgentSessionMessagesParams) ([]ListRecentAgentSessionMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRecentAgentSessionMessages, arg.TenantID, arg.SessionID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentAgentSessionMessagesRow
	for rows.Next() {
		var i ListRecentAgentSessionMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SessionID,
			&i.SegmentID,
			&i.SequenceNo,
			&i.Role,
			&i.Content,
			&i.RunID,
			&i.ContextVersion,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentConfirmationV2 = `-- name: UpdateAgentConfirmationV2 :one
UPDATE agent_confirmations
SET result_payload = $1::jsonb,
    status = $2,
    last_error = $3,
    consumed_at = $4,
    updated_at = $5
WHERE tenant_id = $6
  AND account_id = $7
  AND id = $8
  AND (
    (agent_confirmations.status = 'executing' AND $2::text IN ('pending', 'completed', 'failed', 'cancelled', 'expired'))
    OR (agent_confirmations.status = 'pending' AND $2::text IN ('cancelled', 'expired'))
    OR agent_confirmations.status = $2
  )
RETURNING id, tenant_id, account_id, conversation_id, segment_id, execution_id, source_message_id, kind, title, action, public_payload, action_payload, result_payload, status, last_error, expires_at, consumed_at, created_at, updated_at
`

type UpdateAgentConfirmationV2Params struct {
	ResultPayload []byte             `json:"result_payload"`
	Status        string             `json:"status"`
	LastError     string             `json:"last_error"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	TenantID      string             `json:"tenant_id"`
	AccountID     string             `json:"account_id"`
	ID            string             `json:"id"`
}

func (q *Queries) UpdateAgentConfirmationV2(ctx context.Context, arg UpdateAgentConfirmationV2Params) (AgentConfirmation, error) {
	row := q.db.QueryRow(ctx, updateAgentConfirmationV2,
		arg.ResultPayload,
		arg.Status,
		arg.LastError,
		arg.ConsumedAt,
		arg.UpdatedAt,
		arg.TenantID,
		arg.AccountID,
		arg.ID,
	)
	var i AgentConfirmation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.ConversationID,
		&i.SegmentID,
		&i.ExecutionID,
		&i.SourceMessageID,
		&i.Kind,
		&i.Title,
		&i.Action,
		&i.PublicPayload,
		&i.ActionPayload,
		&i.ResultPayload,
		&i.Status,
		&i.LastError,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentChatExecution = `-- name: UpsertAgentChatExecution :execrows
INSERT INTO conversation_executions (
    id, tenant_id, account_id, conversation_id, segment_id, input_message_id,
    agent_id, agent_revision_id, model_connection_id,
    mode, trigger_type, status, queued_at, started_at, completed_at,
    error_code, error_category, safe_error_message,
    llm_call_count, input_tokens, cached_tokens, output_tokens, total_tokens,
    usage_complete, created_at, updated_at
)
SELECT
    $1, $2, $3,
    messages.conversation_id, messages.segment_id, messages.id,
    NULLIF($4::text, ''),
    NULLIF($5::text, ''),
    NULLIF($6::text, ''),
    $7, 'chat', $8, $9,
    CASE
        WHEN $8::text = 'queued' THEN NULL
        ELSE $10::timestamptz
    END,
    CASE
        WHEN $8::text IN ('completed', 'failed', 'cancelled')
            THEN $10::timestamptz
        ELSE NULL
    END,
    $11, $12,
    CASE WHEN $8::text = 'failed' THEN $13::text ELSE '' END,
    $14, $15, $16,
    $17, $18, $19,
    $9, $10
FROM conversation_messages messages
JOIN conversations
  ON conversations.tenant_id = messages.tenant_id
 AND conversations.id = messages.conversation_id
 AND conversations.current_segment_id = messages.segment_id
WHERE messages.tenant_id = $2
  AND messages.id = $20
  AND messages.conversation_id = $21
  AND messages.segment_id = $22
  AND messages.role = 'user'
  AND conversations.owner_account_id = $3
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    started_at = CASE
        WHEN EXCLUDED.status = 'queued' THEN conversation_executions.started_at
        ELSE COALESCE(conversation_executions.started_at, EXCLUDED.started_at)
    END,
    completed_at = EXCLUDED.completed_at,
    error_code = EXCLUDED.error_code,
    error_category = EXCLUDED.error_category,
    safe_error_message = EXCLUDED.safe_error_message,
    llm_call_count = EXCLUDED.llm_call_count,
    input_tokens = EXCLUDED.input_tokens,
    cached_tokens = EXCLUDED.cached_tokens,
    output_tokens = EXCLUDED.output_tokens,
    total_tokens = EXCLUDED.total_tokens,
    usage_complete = EXCLUDED.usage_complete,
    updated_at = EXCLUDED.updated_at
WHERE conversation_executions.tenant_id = EXCLUDED.tenant_id
`

type UpsertAgentChatExecutionParams struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	AccountID         string             `json:"account_id"`
	AgentID           string             `json:"agent_id"`
	AgentRevisionID   string             `json:"agent_revision_id"`
	ModelConnectionID string             `json:"model_connection_id"`
	Mode              string             `json:"mode"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ErrorCode         string             `json:"error_code"`
	ErrorCategory     string             `json:"error_category"`
	SafeErrorMessage  string             `json:"safe_error_message"`
	LlmCallCount      int64              `json:"llm_call_count"`
	InputTokens       int64              `json:"input_tokens"`
	CachedTokens      int64              `json:"cached_tokens"`
	OutputTokens      int64              `json:"output_tokens"`
	TotalTokens       int64              `json:"total_tokens"`
	UsageComplete     bool               `json:"usage_complete"`
	InputMessageID    string             `json:"input_message_id"`
	SessionID         string             `json:"session_id"`
	SegmentID         string             `json:"segment_id"`
}

func (q *Queries) UpsertAgentChatExecution(ctx context.Context, arg UpsertAgentChatExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertAgentChatExecution,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.AgentID,
		arg.AgentRevisionID,
		arg.ModelConnectionID,
		arg.Mode,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ErrorCode,
		arg.ErrorCategory,
		arg.SafeErrorMessage,
		arg.LlmCallCount,
		arg.InputTokens,
		arg.CachedTokens,
		arg.OutputTokens,
		arg.TotalTokens,
		arg.UsageComplete,
		arg.InputMessageID,
		arg.SessionID,
		arg.SegmentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAgentConfirmationV2 = `-- name: UpsertAgentConfirmationV2 :one
WITH inserted AS (
    INSERT INTO agent_confirmations (
        id, tenant_id, account_id, conversation_id, segment_id,
        execution_id, source_message_id, kind, title, action,
        public_payload, action_payload, result_payload, status,
        last_error, expires_at, consumed_at, created_at, updated_at
    ) VALUES (
        $1, $2, $3,
        $4, $5,
        NULLIF($6::text, ''), NULLIF($7::text, ''),
        $8, $9, $10,
        $11::jsonb, $12::jsonb,
        $13::jsonb, $14, $15,
        $16, $17, $18, $19
    )
    ON CONFLICT (id) DO NOTHING
    RETURNING id, tenant_id, account_id, conversation_id, segment_id, execution_id, source_message_id, kind, title, action, public_payload, action_payload, result_payload, status, last_error, expires_at, consumed_at, created_at, updated_at
)
SELECT id, tenant_id, account_id, conversation_id, segment_id, execution_id, source_message_id, kind, title, action, public_payload, action_payload, result_payload, status, last_error, expires_at, consumed_at, created_at, updated_at FROM inserted
UNION ALL
SELECT confirmations.id, confirmations.tenant_id, confirmations.account_id, confirmations.conversation_id, confirmations.segment_id, confirmations.execution_id, confirmations.source_message_id, confirmations.kind, confirmations.title, confirmations.action, confirmations.public_payload, confirmations.action_payload, confirmations.result_payload, confirmations.status, confirmations.last_error, confirmations.expires_at, confirmations.consumed_at, confirmations.created_at, confirmations.updated_at
FROM agent_confirmations confirmations
WHERE confirmations.tenant_id = $2
  AND confirmations.id = $1
  AND NOT EXISTS (SELECT 1 FROM inserted)
LIMIT 1
`

type UpsertAgentConfirmationV2Params struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	ConversationID  string             `json:"conversation_id"`
	SegmentID       string             `json:"segment_id"`
	ExecutionID     string             `json:"execution_id"`
	SourceMessageID string             `json:"source_message_id"`
	Kind            string             `json:"kind"`
	Title           string             `json:"title"`
	Action          string             `json:"action"`
	PublicPayload   []byte             `json:"public_payload"`
	ActionPayload   []byte             `json:"action_payload"`
	ResultPayload   []byte             `json:"result_payload"`
	Status          string             `json:"status"`
	LastError       string             `json:"last_error"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UpsertAgentConfirmationV2Row struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	ConversationID  string             `json:"conversation_id"`
	SegmentID       string             `json:"segment_id"`
	ExecutionID     pgtype.Text        `json:"execution_id"`
	SourceMessageID pgtype.Text        `json:"source_message_id"`
	Kind            string             `json:"kind"`
	Title           string             `json:"title"`
	Action          string             `json:"action"`
	PublicPayload   []byte             `json:"public_payload"`
	ActionPayload   []byte             `json:"action_payload"`
	ResultPayload   []byte             `json:"result_payload"`
	Status          string             `json:"status"`
	LastError       string             `json:"last_error"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAgentConfirmationV2(ctx context.Context, arg UpsertAgentConfirmationV2Params) (UpsertAgentConfirmationV2Row, error) {
	row := q.db.QueryRow(ctx, upsertAgentConfirmationV2,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.ConversationID,
		arg.SegmentID,
		arg.ExecutionID,
		arg.SourceMessageID,
		arg.Kind,
		arg.Title,
		arg.Action,
		arg.PublicPayload,
		arg.ActionPayload,
		arg.ResultPayload,
		arg.Status,
		arg.LastError,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UpsertAgentConfirmationV2Row
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.ConversationID,
		&i.SegmentID,
		&i.ExecutionID,
		&i.SourceMessageID,
		&i.Kind,
		&i.Title,
		&i.Action,
		&i.PublicPayload,
		&i.ActionPayload,
		&i.ResultPayload,
		&i.Status,
		&i.LastError,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentMemory = `-- name: UpsertAgentMemory :one
WITH scope_values AS (
    SELECT
        CASE
            WHEN $1::text <> '' THEN 'conversation'
            WHEN $2::text <> '' THEN 'agent'
            ELSE 'global'
        END::text AS scope_type,
        CASE WHEN $1::text = '' THEN NULLIF($2::text, '') ELSE NULL END AS agent_id,
        CASE WHEN $1::text <> '' THEN conversations.id ELSE NULL END AS conversation_id,
        CASE WHEN $1::text <> '' THEN conversations.current_segment_id ELSE NULL END AS segment_id
    FROM (SELECT 1) seed
    LEFT JOIN conversations
      ON conversations.tenant_id = $3
     AND conversations.id = NULLIF($1::text, '')
    WHERE $1::text = '' OR conversations.id IS NOT NULL
), updated_by_id AS (
    UPDATE agent_memories
    SET account_id = $4,
        scope_type = scope_values.scope_type,
        agent_id = scope_values.agent_id,
        conversation_id = scope_values.conversation_id,
        segment_id = scope_values.segment_id,
        key = $5,
        content = $6,
        source_type = CASE WHEN $7::text = 'manual' THEN 'manual' ELSE 'extracted' END,
        source_message_id = NULLIF($8::text, ''),
        confidence = $9,
        importance = LEAST(GREATEST($10::int, 1), 5),
        status = COALESCE(NULLIF($11::text, ''), 'active'),
        expires_at = $12,
        updated_at = $13
    FROM scope_values
    WHERE agent_memories.tenant_id = $3
      AND agent_memories.id = $14
    RETURNING agent_memories.id, agent_memories.tenant_id, agent_memories.account_id, agent_memories.scope_type, agent_memories.agent_id, agent_memories.conversation_id, agent_memories.segment_id, agent_memories.key, agent_memories.content, agent_memories.source_type, agent_memories.source_message_id, agent_memories.confidence, agent_memories.importance, agent_memories.status, agent_memories.expires_at, agent_memories.created_at, agent_memories.updated_at
), inserted_or_merged AS (
    INSERT INTO agent_memories (
        id, tenant_id, account_id, scope_type, agent_id, conversation_id, segment_id,
        key, content, source_type, source_message_id, confidence, importance,
        status, expires_at, created_at, updated_at
    )
    SELECT
        $14, $3, $4, scope_values.scope_type,
        scope_values.agent_id, scope_values.conversation_id, scope_values.segment_id,
        $5, $6,
        CASE WHEN $7::text = 'manual' THEN 'manual' ELSE 'extracted' END,
        NULLIF($8::text, ''), $9,
        LEAST(GREATEST($10::int, 1), 5),
        COALESCE(NULLIF($11::text, ''), 'active'),
        $12, $15, $13
    FROM scope_values
    WHERE NOT EXISTS (SELECT 1 FROM updated_by_id)
    ON CONFLICT (tenant_id, account_id, scope_type, agent_id, conversation_id, segment_id, key)
        WHERE status = 'active'
    DO UPDATE SET
        content = EXCLUDED.content,
        source_type = EXCLUDED.source_type,
        source_message_id = EXCLUDED.source_message_id,
        confidence = EXCLUDED.confidence,
        importance = EXCLUDED.importance,
        status = EXCLUDED.status,
        expires_at = EXCLUDED.expires_at,
        updated_at = EXCLUDED.updated_at
    RETURNING id, tenant_id, account_id, scope_type, agent_id, conversation_id, segment_id, key, content, source_type, source_message_id, confidence, importance, status, expires_at, created_at, updated_at
), upserted AS (
    SELECT id, tenant_id, account_id, scope_type, agent_id, conversation_id, segment_id, key, content, source_type, source_message_id, confidence, importance, status, expires_at, created_at, updated_at FROM updated_by_id
    UNION ALL
    SELECT id, tenant_id, account_id, scope_type, agent_id, conversation_id, segment_id, key, content, source_type, source_message_id, confidence, importance, status, expires_at, created_at, updated_at FROM inserted_or_merged
)
SELECT
    id, tenant_id, account_id, agent_id, conversation_id AS session_id, segment_id,
    scope_type AS scope, source_message_id, confidence, status,
    key, content,
    CASE WHEN source_type = 'manual' THEN 'manual' ELSE 'auto' END::text AS source,
    importance, expires_at, created_at, updated_at
FROM upserted
`

type UpsertAgentMemoryParams struct {
	SessionID       string             `json:"session_id"`
	AgentID         string             `json:"agent_id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	Key             string             `json:"key"`
	Content         string             `json:"content"`
	Source          string             `json:"source"`
	SourceMessageID string             `json:"source_message_id"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Importance      int32              `json:"importance"`
	Status          string             `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ID              string             `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type UpsertAgentMemoryRow struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	AgentID         pgtype.Text        `json:"agent_id"`
	SessionID       pgtype.Text        `json:"session_id"`
	SegmentID       pgtype.Text        `json:"segment_id"`
	Scope           string             `json:"scope"`
	SourceMessageID pgtype.Text        `json:"source_message_id"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Status          string             `json:"status"`
	Key             string             `json:"key"`
	Content         string             `json:"content"`
	Source          string             `json:"source"`
	Importance      int32              `json:"importance"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAgentMemory(ctx context.Context, arg UpsertAgentMemoryParams) (UpsertAgentMemoryRow, error) {
	row := q.db.QueryRow(ctx, upsertAgentMemory,
		arg.SessionID,
		arg.AgentID,
		arg.TenantID,
		arg.AccountID,
		arg.Key,
		arg.Content,
		arg.Source,
		arg.SourceMessageID,
		arg.Confidence,
		arg.Importance,
		arg.Status,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.CreatedAt,
	)
	var i UpsertAgentMemoryRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.SessionID,
		&i.SegmentID,
		&i.Scope,
		&i.SourceMessageID,
		&i.Confidence,
		&i.Status,
		&i.Key,
		&i.Content,
		&i.Source,
		&i.Importance,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentSession = `-- name: UpsertAgentSession :one

WITH upserted_conversation AS (
    INSERT INTO conversations (
        id, tenant_id, owner_account_id, agent_id, current_segment_id,
        next_message_sequence, title, status, last_message_at,
        created_at, updated_at, archived_at
    ) VALUES (
        $1, $2, $3,
        NULLIF($4::text, ''), NULL, 1,
        $5, $6, $7,
        $8, $9,
        CASE WHEN $6::text = 'archived' THEN $9::timestamptz ELSE NULL END
    )
    ON CONFLICT (id) DO UPDATE SET
        owner_account_id = EXCLUDED.owner_account_id,
        agent_id = EXCLUDED.agent_id,
        title = EXCLUDED.title,
        status = EXCLUDED.status,
        last_message_at = EXCLUDED.last_message_at,
        updated_at = EXCLUDED.updated_at,
        archived_at = EXCLUDED.archived_at
    WHERE conversations.tenant_id = EXCLUDED.tenant_id
    RETURNING id, tenant_id, owner_account_id, agent_id, current_segment_id, next_message_sequence, title, status, last_message_at, created_at, updated_at, archived_at
), inserted_segment AS (
    INSERT INTO conversation_segments (
        id, tenant_id, conversation_id, ordinal, start_reason, created_at
    )
    SELECT
        COALESCE(
            NULLIF($10::text, ''),
            $1::text || ':segment:' || GREATEST($11::bigint, 1)::text
        ),
        tenant_id,
        id,
        GREATEST($11::bigint, 1)::integer,
        CASE WHEN GREATEST($11::bigint, 1) = 1 THEN 'initial' ELSE 'context_reset' END,
        $9
    FROM upserted_conversation
    ON CONFLICT (tenant_id, conversation_id, ordinal) DO NOTHING
    RETURNING id, tenant_id, conversation_id, ordinal, start_reason, created_at
), target_segment AS (
    SELECT id, tenant_id, conversation_id, ordinal
    FROM inserted_segment
    UNION ALL
    SELECT segments.id, segments.tenant_id, segments.conversation_id, segments.ordinal
    FROM conversation_segments segments
    JOIN upserted_conversation conversations
      ON conversations.tenant_id = segments.tenant_id
     AND conversations.id = segments.conversation_id
    WHERE segments.ordinal = GREATEST($11::bigint, 1)::integer
    LIMIT 1
), updated_conversation AS (
    UPDATE conversations
    SET current_segment_id = target_segment.id
    FROM target_segment
    WHERE conversations.tenant_id = target_segment.tenant_id
      AND conversations.id = target_segment.conversation_id
    RETURNING conversations.id, conversations.tenant_id, conversations.owner_account_id, conversations.agent_id, conversations.current_segment_id, conversations.next_message_sequence, conversations.title, conversations.status, conversations.last_message_at, conversations.created_at, conversations.updated_at, conversations.archived_at
)
SELECT
    conversations.id,
    conversations.tenant_id,
    conversations.owner_account_id AS account_id,
    conversations.agent_id,
    target_segment.id AS segment_id,
    conversations.title,
    conversations.status,
    target_segment.ordinal::bigint AS context_version,
    conversations.last_message_at,
    conversations.created_at,
    conversations.updated_at
FROM updated_conversation conversations
JOIN target_segment
  ON target_segment.tenant_id = conversations.tenant_id
 AND target_segment.conversation_id = conversations.id
`

type UpsertAgentSessionParams struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	AgentID        string             `json:"agent_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SegmentID      string             `json:"segment_id"`
	ContextVersion int64              `json:"context_version"`
}

type UpsertAgentSessionRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	AgentID        pgtype.Text        `json:"agent_id"`
	SegmentID      string             `json:"segment_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	ContextVersion int64              `json:"context_version"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Legacy AgentSession compatibility over the v2 conversation/segment model.
func (q *Queries) UpsertAgentSession(ctx context.Context, arg UpsertAgentSessionParams) (UpsertAgentSessionRow, error) {
	row := q.db.QueryRow(ctx, upsertAgentSession,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.AgentID,
		arg.Title,
		arg.Status,
		arg.LastMessageAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SegmentID,
		arg.ContextVersion,
	)
	var i UpsertAgentSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AgentID,
		&i.SegmentID,
		&i.Title,
		&i.Status,
		&i.ContextVersion,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertExecutionStepV2 = `-- name: UpsertExecutionStepV2 :one
INSERT INTO conversation_execution_steps (
    id, tenant_id, execution_id, parent_step_id, sequence_no, step_type,
    name, model_connection_id, external_tool_id, status,
    input_summary, output_summary, input_tokens, cached_tokens, output_tokens,
    started_at, completed_at, error_code, created_at
) VALUES (
    $1, $2, $3, NULLIF($4::text, ''),
    $5, $6, $7,
    NULLIF($8::text, ''), NULLIF($9::text, ''),
    $10, $11::jsonb, $12::jsonb,
    $13, $14, $15,
    $16, $17, $18, $19
)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    input_summary = EXCLUDED.input_summary,
    output_summary = EXCLUDED.output_summary,
    input_tokens = EXCLUDED.input_tokens,
    cached_tokens = EXCLUDED.cached_tokens,
    output_tokens = EXCLUDED.output_tokens,
    started_at = EXCLUDED.started_at,
    completed_at = EXCLUDED.completed_at,
    error_code = EXCLUDED.error_code
WHERE conversation_execution_steps.tenant_id = EXCLUDED.tenant_id
  AND conversation_execution_steps.execution_id = EXCLUDED.execution_id
RETURNING id, tenant_id, execution_id, parent_step_id, sequence_no, step_type, name, model_connection_id, external_tool_id, status, input_summary, output_summary, input_tokens, cached_tokens, output_tokens, started_at, completed_at, error_code, created_at
`

type UpsertExecutionStepV2Params struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	ExecutionID       string             `json:"execution_id"`
	ParentStepID      string             `json:"parent_step_id"`
	SequenceNo        int32              `json:"sequence_no"`
	StepType          string             `json:"step_type"`
	Name              string             `json:"name"`
	ModelConnectionID string             `json:"model_connection_id"`
	ExternalToolID    string             `json:"external_tool_id"`
	Status            string             `json:"status"`
	InputSummary      []byte             `json:"input_summary"`
	OutputSummary     []byte             `json:"output_summary"`
	InputTokens       int64              `json:"input_tokens"`
	CachedTokens      int64              `json:"cached_tokens"`
	OutputTokens      int64              `json:"output_tokens"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ErrorCode         string             `json:"error_code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertExecutionStepV2(ctx context.Context, arg UpsertExecutionStepV2Params) (ConversationExecutionStep, error) {
	row := q.db.QueryRow(ctx, upsertExecutionStepV2,
		arg.ID,
		arg.TenantID,
		arg.ExecutionID,
		arg.ParentStepID,
		arg.SequenceNo,
		arg.StepType,
		arg.Name,
		arg.ModelConnectionID,
		arg.ExternalToolID,
		arg.Status,
		arg.InputSummary,
		arg.OutputSummary,
		arg.InputTokens,
		arg.CachedTokens,
		arg.OutputTokens,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ErrorCode,
		arg.CreatedAt,
	)
	var i ConversationExecutionStep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.ParentStepID,
		&i.SequenceNo,
		&i.StepType,
		&i.Name,
		&i.ModelConnectionID,
		&i.ExternalToolID,
		&i.Status,
		&i.InputSummary,
		&i.OutputSummary,
		&i.InputTokens,
		&i.CachedTokens,
		&i.OutputTokens,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}
