// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthzAssumableRoleSession = `-- name: CreateAuthzAssumableRoleSession :one
INSERT INTO authz_assumable_role_sessions (
    id, tenant_id, account_id, assumable_role_id, session_policy,
    expires_at, revoked_at, created_at
) VALUES (
    $1, $2, $3, $4, $5::jsonb, $6, $7, $8
)
RETURNING id, tenant_id, account_id, assumable_role_id, session_policy, expires_at, revoked_at, created_at
`

type CreateAuthzAssumableRoleSessionParams struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	AssumableRoleID string             `json:"assumable_role_id"`
	Column5         []byte             `json:"column_5"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthzAssumableRoleSession(ctx context.Context, arg CreateAuthzAssumableRoleSessionParams) (AuthzAssumableRoleSession, error) {
	row := q.db.QueryRow(ctx, createAuthzAssumableRoleSession,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.AssumableRoleID,
		arg.Column5,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.CreatedAt,
	)
	var i AuthzAssumableRoleSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AssumableRoleID,
		&i.SessionPolicy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthzAssumableRoleSessionsForRole = `-- name: DeleteAuthzAssumableRoleSessionsForRole :exec
DELETE FROM authz_assumable_role_sessions
WHERE tenant_id = $1
  AND assumable_role_id = $2
`

type DeleteAuthzAssumableRoleSessionsForRoleParams struct {
	TenantID        string `json:"tenant_id"`
	AssumableRoleID string `json:"assumable_role_id"`
}

func (q *Queries) DeleteAuthzAssumableRoleSessionsForRole(ctx context.Context, arg DeleteAuthzAssumableRoleSessionsForRoleParams) error {
	_, err := q.db.Exec(ctx, deleteAuthzAssumableRoleSessionsForRole, arg.TenantID, arg.AssumableRoleID)
	return err
}

const deleteAuthzDataScope = `-- name: DeleteAuthzDataScope :one
DELETE FROM authz_data_scopes
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, code, name, scope_type, params, created_at
`

type DeleteAuthzDataScopeParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteAuthzDataScope(ctx context.Context, arg DeleteAuthzDataScopeParams) (AuthzDataScope, error) {
	row := q.db.QueryRow(ctx, deleteAuthzDataScope, arg.TenantID, arg.ID)
	var i AuthzDataScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ScopeType,
		&i.Params,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthzFieldPolicy = `-- name: DeleteAuthzFieldPolicy :one
DELETE FROM authz_field_policies
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, application_code, resource_type, field_name, effect, mask_strategy, permission_id, created_at
`

type DeleteAuthzFieldPolicyParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteAuthzFieldPolicy(ctx context.Context, arg DeleteAuthzFieldPolicyParams) (AuthzFieldPolicy, error) {
	row := q.db.QueryRow(ctx, deleteAuthzFieldPolicy, arg.TenantID, arg.ID)
	var i AuthzFieldPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationCode,
		&i.ResourceType,
		&i.FieldName,
		&i.Effect,
		&i.MaskStrategy,
		&i.PermissionID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthzPermissionSetAssignment = `-- name: DeleteAuthzPermissionSetAssignment :one
DELETE FROM authz_permission_set_assignments
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, principal_type, principal_id, permission_set_id, effect, data_scope_id, condition_id, starts_at, expires_at, created_at
`

type DeleteAuthzPermissionSetAssignmentParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteAuthzPermissionSetAssignment(ctx context.Context, arg DeleteAuthzPermissionSetAssignmentParams) (AuthzPermissionSetAssignment, error) {
	row := q.db.QueryRow(ctx, deleteAuthzPermissionSetAssignment, arg.TenantID, arg.ID)
	var i AuthzPermissionSetAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.PermissionSetID,
		&i.Effect,
		&i.DataScopeID,
		&i.ConditionID,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthzRelationshipTuple = `-- name: DeleteAuthzRelationshipTuple :exec
DELETE FROM authz_relationship_tuples
WHERE tenant_id = $1
  AND object_type = $2
  AND object_id = $3
  AND relation = $4
  AND subject_type = $5
  AND subject_id = $6
`

type DeleteAuthzRelationshipTupleParams struct {
	TenantID    string `json:"tenant_id"`
	ObjectType  string `json:"object_type"`
	ObjectID    string `json:"object_id"`
	Relation    string `json:"relation"`
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
}

func (q *Queries) DeleteAuthzRelationshipTuple(ctx context.Context, arg DeleteAuthzRelationshipTupleParams) error {
	_, err := q.db.Exec(ctx, deleteAuthzRelationshipTuple,
		arg.TenantID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
	)
	return err
}

const getActiveAuthzAssumableRoleSession = `-- name: GetActiveAuthzAssumableRoleSession :one
SELECT id, tenant_id, account_id, assumable_role_id, session_policy, expires_at, revoked_at, created_at FROM authz_assumable_role_sessions
WHERE tenant_id = $1
  AND id = $2
  AND revoked_at IS NULL
  AND expires_at > now()
`

type GetActiveAuthzAssumableRoleSessionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetActiveAuthzAssumableRoleSession(ctx context.Context, arg GetActiveAuthzAssumableRoleSessionParams) (AuthzAssumableRoleSession, error) {
	row := q.db.QueryRow(ctx, getActiveAuthzAssumableRoleSession, arg.TenantID, arg.ID)
	var i AuthzAssumableRoleSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AssumableRoleID,
		&i.SessionPolicy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthzDataScope = `-- name: GetAuthzDataScope :one
SELECT id, tenant_id, code, name, scope_type, params, created_at FROM authz_data_scopes
WHERE tenant_id = $1 AND id = $2
`

type GetAuthzDataScopeParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetAuthzDataScope(ctx context.Context, arg GetAuthzDataScopeParams) (AuthzDataScope, error) {
	row := q.db.QueryRow(ctx, getAuthzDataScope, arg.TenantID, arg.ID)
	var i AuthzDataScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ScopeType,
		&i.Params,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthzFieldPolicy = `-- name: GetAuthzFieldPolicy :one
SELECT id, tenant_id, application_code, resource_type, field_name, effect, mask_strategy, permission_id, created_at FROM authz_field_policies
WHERE tenant_id = $1 AND id = $2
`

type GetAuthzFieldPolicyParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetAuthzFieldPolicy(ctx context.Context, arg GetAuthzFieldPolicyParams) (AuthzFieldPolicy, error) {
	row := q.db.QueryRow(ctx, getAuthzFieldPolicy, arg.TenantID, arg.ID)
	var i AuthzFieldPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationCode,
		&i.ResourceType,
		&i.FieldName,
		&i.Effect,
		&i.MaskStrategy,
		&i.PermissionID,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthzPermissionVersion = `-- name: GetAuthzPermissionVersion :one
SELECT tenant_id, version, updated_at FROM authz_permission_versions
WHERE tenant_id = $1
`

func (q *Queries) GetAuthzPermissionVersion(ctx context.Context, tenantID string) (AuthzPermissionVersion, error) {
	row := q.db.QueryRow(ctx, getAuthzPermissionVersion, tenantID)
	var i AuthzPermissionVersion
	err := row.Scan(&i.TenantID, &i.Version, &i.UpdatedAt)
	return i, err
}

const getUserIdentity = `-- name: GetUserIdentity :one
SELECT id, tenant_id, account_id, provider, subject, email, created_at FROM user_identities
WHERE tenant_id = $1 AND provider = $2 AND subject = $3
`

type GetUserIdentityParams struct {
	TenantID string `json:"tenant_id"`
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentity, arg.TenantID, arg.Provider, arg.Subject)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAuthzPermissionVersion = `-- name: IncrementAuthzPermissionVersion :one
INSERT INTO authz_permission_versions (
    tenant_id, version, updated_at
) VALUES (
    $1, 1, $2
)
ON CONFLICT (tenant_id) DO UPDATE SET
    version = authz_permission_versions.version + 1,
    updated_at = EXCLUDED.updated_at
RETURNING tenant_id, version, updated_at
`

type IncrementAuthzPermissionVersionParams struct {
	TenantID  string             `json:"tenant_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) IncrementAuthzPermissionVersion(ctx context.Context, arg IncrementAuthzPermissionVersionParams) (AuthzPermissionVersion, error) {
	row := q.db.QueryRow(ctx, incrementAuthzPermissionVersion, arg.TenantID, arg.UpdatedAt)
	var i AuthzPermissionVersion
	err := row.Scan(&i.TenantID, &i.Version, &i.UpdatedAt)
	return i, err
}

const listActiveAuthzAssumableRoleSessionsForRole = `-- name: ListActiveAuthzAssumableRoleSessionsForRole :many
SELECT id, tenant_id, account_id, assumable_role_id, session_policy, expires_at, revoked_at, created_at FROM authz_assumable_role_sessions
WHERE tenant_id = $1
  AND assumable_role_id = $2
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY created_at ASC
`

type ListActiveAuthzAssumableRoleSessionsForRoleParams struct {
	TenantID        string `json:"tenant_id"`
	AssumableRoleID string `json:"assumable_role_id"`
}

func (q *Queries) ListActiveAuthzAssumableRoleSessionsForRole(ctx context.Context, arg ListActiveAuthzAssumableRoleSessionsForRoleParams) ([]AuthzAssumableRoleSession, error) {
	rows, err := q.db.Query(ctx, listActiveAuthzAssumableRoleSessionsForRole, arg.TenantID, arg.AssumableRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthzAssumableRoleSession
	for rows.Next() {
		var i AuthzAssumableRoleSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.AssumableRoleID,
			&i.SessionPolicy,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthzDataScopes = `-- name: ListAuthzDataScopes :many
SELECT id, tenant_id, code, name, scope_type, params, created_at FROM authz_data_scopes
WHERE tenant_id = $1
ORDER BY code ASC
`

func (q *Queries) ListAuthzDataScopes(ctx context.Context, tenantID string) ([]AuthzDataScope, error) {
	rows, err := q.db.Query(ctx, listAuthzDataScopes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthzDataScope
	for rows.Next() {
		var i AuthzDataScope
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.ScopeType,
			&i.Params,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthzFieldPolicies = `-- name: ListAuthzFieldPolicies :many
SELECT id, tenant_id, application_code, resource_type, field_name, effect, mask_strategy, permission_id, created_at FROM authz_field_policies
WHERE tenant_id = $1
  AND ($2::text = '' OR application_code = $2)
  AND ($3::text = '' OR resource_type = $3)
ORDER BY field_name ASC
`

type ListAuthzFieldPoliciesParams struct {
	TenantID string `json:"tenant_id"`
	Column2  string `json:"column_2"`
	Column3  string `json:"column_3"`
}

func (q *Queries) ListAuthzFieldPolicies(ctx context.Context, arg ListAuthzFieldPoliciesParams) ([]AuthzFieldPolicy, error) {
	rows, err := q.db.Query(ctx, listAuthzFieldPolicies, arg.TenantID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthzFieldPolicy
	for rows.Next() {
		var i AuthzFieldPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ApplicationCode,
			&i.ResourceType,
			&i.FieldName,
			&i.Effect,
			&i.MaskStrategy,
			&i.PermissionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthzPermissionSetAssignments = `-- name: ListAuthzPermissionSetAssignments :many
SELECT id, tenant_id, principal_type, principal_id, permission_set_id, effect, data_scope_id, condition_id, starts_at, expires_at, created_at FROM authz_permission_set_assignments
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAuthzPermissionSetAssignments(ctx context.Context, tenantID string) ([]AuthzPermissionSetAssignment, error) {
	rows, err := q.db.Query(ctx, listAuthzPermissionSetAssignments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthzPermissionSetAssignment
	for rows.Next() {
		var i AuthzPermissionSetAssignment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.PermissionSetID,
			&i.Effect,
			&i.DataScopeID,
			&i.ConditionID,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthzPermissionSetAssignmentsForPrincipal = `-- name: ListAuthzPermissionSetAssignmentsForPrincipal :many
SELECT id, tenant_id, principal_type, principal_id, permission_set_id, effect, data_scope_id, condition_id, starts_at, expires_at, created_at FROM authz_permission_set_assignments
WHERE tenant_id = $1
  AND principal_type = $2
  AND principal_id = $3
  AND (starts_at IS NULL OR starts_at <= now())
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at ASC
`

type ListAuthzPermissionSetAssignmentsForPrincipalParams struct {
	TenantID      string `json:"tenant_id"`
	PrincipalType string `json:"principal_type"`
	PrincipalID   string `json:"principal_id"`
}

func (q *Queries) ListAuthzPermissionSetAssignmentsForPrincipal(ctx context.Context, arg ListAuthzPermissionSetAssignmentsForPrincipalParams) ([]AuthzPermissionSetAssignment, error) {
	rows, err := q.db.Query(ctx, listAuthzPermissionSetAssignmentsForPrincipal, arg.TenantID, arg.PrincipalType, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthzPermissionSetAssignment
	for rows.Next() {
		var i AuthzPermissionSetAssignment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.PermissionSetID,
			&i.Effect,
			&i.DataScopeID,
			&i.ConditionID,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthzRelationshipTuplesForObject = `-- name: ListAuthzRelationshipTuplesForObject :many
SELECT id, tenant_id, object_type, object_id, relation, subject_type, subject_id, created_at FROM authz_relationship_tuples
WHERE tenant_id = $1
  AND object_type = $2
  AND object_id = $3
ORDER BY relation ASC, subject_type ASC, subject_id ASC
`

type ListAuthzRelationshipTuplesForObjectParams struct {
	TenantID   string `json:"tenant_id"`
	ObjectType string `json:"object_type"`
	ObjectID   string `json:"object_id"`
}

func (q *Queries) ListAuthzRelationshipTuplesForObject(ctx context.Context, arg ListAuthzRelationshipTuplesForObjectParams) ([]AuthzRelationshipTuple, error) {
	rows, err := q.db.Query(ctx, listAuthzRelationshipTuplesForObject, arg.TenantID, arg.ObjectType, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthzRelationshipTuple
	for rows.Next() {
		var i AuthzRelationshipTuple
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIdentities = `-- name: ListUserIdentities :many
SELECT id, tenant_id, account_id, provider, subject, email, created_at FROM user_identities
WHERE tenant_id = $1 AND account_id = $2
ORDER BY created_at ASC
`

type ListUserIdentitiesParams struct {
	TenantID  string `json:"tenant_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) ListUserIdentities(ctx context.Context, arg ListUserIdentitiesParams) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, listUserIdentities, arg.TenantID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentity
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAuthzAssumableRoleSession = `-- name: RevokeAuthzAssumableRoleSession :one
UPDATE authz_assumable_role_sessions
SET revoked_at = $3
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, assumable_role_id, session_policy, expires_at, revoked_at, created_at
`

type RevokeAuthzAssumableRoleSessionParams struct {
	TenantID  string             `json:"tenant_id"`
	ID        string             `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAuthzAssumableRoleSession(ctx context.Context, arg RevokeAuthzAssumableRoleSessionParams) (AuthzAssumableRoleSession, error) {
	row := q.db.QueryRow(ctx, revokeAuthzAssumableRoleSession, arg.TenantID, arg.ID, arg.RevokedAt)
	var i AuthzAssumableRoleSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.AssumableRoleID,
		&i.SessionPolicy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAuthzDataScope = `-- name: UpdateAuthzDataScope :one
UPDATE authz_data_scopes
SET code = $3,
    name = $4,
    scope_type = $5,
    params = $6::jsonb
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, code, name, scope_type, params, created_at
`

type UpdateAuthzDataScopeParams struct {
	TenantID  string `json:"tenant_id"`
	ID        string `json:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	ScopeType string `json:"scope_type"`
	Column6   []byte `json:"column_6"`
}

func (q *Queries) UpdateAuthzDataScope(ctx context.Context, arg UpdateAuthzDataScopeParams) (AuthzDataScope, error) {
	row := q.db.QueryRow(ctx, updateAuthzDataScope,
		arg.TenantID,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.ScopeType,
		arg.Column6,
	)
	var i AuthzDataScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ScopeType,
		&i.Params,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAuthzDataScope = `-- name: UpsertAuthzDataScope :one
INSERT INTO authz_data_scopes (
    id, tenant_id, code, name, scope_type, params, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6::jsonb, $7
)
ON CONFLICT (tenant_id, code) DO UPDATE SET
    name = EXCLUDED.name,
    scope_type = EXCLUDED.scope_type,
    params = EXCLUDED.params
RETURNING id, tenant_id, code, name, scope_type, params, created_at
`

type UpsertAuthzDataScopeParams struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	ScopeType string             `json:"scope_type"`
	Column6   []byte             `json:"column_6"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertAuthzDataScope(ctx context.Context, arg UpsertAuthzDataScopeParams) (AuthzDataScope, error) {
	row := q.db.QueryRow(ctx, upsertAuthzDataScope,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.ScopeType,
		arg.Column6,
		arg.CreatedAt,
	)
	var i AuthzDataScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ScopeType,
		&i.Params,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAuthzFieldPolicy = `-- name: UpsertAuthzFieldPolicy :one
INSERT INTO authz_field_policies (
    id, tenant_id, application_code, resource_type, field_name,
    effect, mask_strategy, permission_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id) DO UPDATE SET
    application_code = EXCLUDED.application_code,
    resource_type = EXCLUDED.resource_type,
    field_name = EXCLUDED.field_name,
    effect = EXCLUDED.effect,
    mask_strategy = EXCLUDED.mask_strategy,
    permission_id = EXCLUDED.permission_id
RETURNING id, tenant_id, application_code, resource_type, field_name, effect, mask_strategy, permission_id, created_at
`

type UpsertAuthzFieldPolicyParams struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	ApplicationCode string             `json:"application_code"`
	ResourceType    string             `json:"resource_type"`
	FieldName       string             `json:"field_name"`
	Effect          string             `json:"effect"`
	MaskStrategy    string             `json:"mask_strategy"`
	PermissionID    string             `json:"permission_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertAuthzFieldPolicy(ctx context.Context, arg UpsertAuthzFieldPolicyParams) (AuthzFieldPolicy, error) {
	row := q.db.QueryRow(ctx, upsertAuthzFieldPolicy,
		arg.ID,
		arg.TenantID,
		arg.ApplicationCode,
		arg.ResourceType,
		arg.FieldName,
		arg.Effect,
		arg.MaskStrategy,
		arg.PermissionID,
		arg.CreatedAt,
	)
	var i AuthzFieldPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationCode,
		&i.ResourceType,
		&i.FieldName,
		&i.Effect,
		&i.MaskStrategy,
		&i.PermissionID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAuthzPermissionSetAssignment = `-- name: UpsertAuthzPermissionSetAssignment :one
INSERT INTO authz_permission_set_assignments (
    id, tenant_id, principal_type, principal_id, permission_set_id,
    effect, data_scope_id, condition_id, starts_at, expires_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    principal_type = EXCLUDED.principal_type,
    principal_id = EXCLUDED.principal_id,
    permission_set_id = EXCLUDED.permission_set_id,
    effect = EXCLUDED.effect,
    data_scope_id = EXCLUDED.data_scope_id,
    condition_id = EXCLUDED.condition_id,
    starts_at = EXCLUDED.starts_at,
    expires_at = EXCLUDED.expires_at,
    created_at = EXCLUDED.created_at
RETURNING id, tenant_id, principal_type, principal_id, permission_set_id, effect, data_scope_id, condition_id, starts_at, expires_at, created_at
`

type UpsertAuthzPermissionSetAssignmentParams struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	PrincipalType   string             `json:"principal_type"`
	PrincipalID     string             `json:"principal_id"`
	PermissionSetID string             `json:"permission_set_id"`
	Effect          string             `json:"effect"`
	DataScopeID     string             `json:"data_scope_id"`
	ConditionID     string             `json:"condition_id"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertAuthzPermissionSetAssignment(ctx context.Context, arg UpsertAuthzPermissionSetAssignmentParams) (AuthzPermissionSetAssignment, error) {
	row := q.db.QueryRow(ctx, upsertAuthzPermissionSetAssignment,
		arg.ID,
		arg.TenantID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.PermissionSetID,
		arg.Effect,
		arg.DataScopeID,
		arg.ConditionID,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AuthzPermissionSetAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.PermissionSetID,
		&i.Effect,
		&i.DataScopeID,
		&i.ConditionID,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAuthzRelationshipTuple = `-- name: UpsertAuthzRelationshipTuple :one
INSERT INTO authz_relationship_tuples (
    id, tenant_id, object_type, object_id, relation,
    subject_type, subject_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (tenant_id, object_type, object_id, relation, subject_type, subject_id) DO UPDATE SET
    created_at = EXCLUDED.created_at
RETURNING id, tenant_id, object_type, object_id, relation, subject_type, subject_id, created_at
`

type UpsertAuthzRelationshipTupleParams struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	ObjectType  string             `json:"object_type"`
	ObjectID    string             `json:"object_id"`
	Relation    string             `json:"relation"`
	SubjectType string             `json:"subject_type"`
	SubjectID   string             `json:"subject_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertAuthzRelationshipTuple(ctx context.Context, arg UpsertAuthzRelationshipTupleParams) (AuthzRelationshipTuple, error) {
	row := q.db.QueryRow(ctx, upsertAuthzRelationshipTuple,
		arg.ID,
		arg.TenantID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.CreatedAt,
	)
	var i AuthzRelationshipTuple
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ObjectType,
		&i.ObjectID,
		&i.Relation,
		&i.SubjectType,
		&i.SubjectID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserIdentity = `-- name: UpsertUserIdentity :one
INSERT INTO user_identities (
    id, tenant_id, account_id, provider, subject, email, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (tenant_id, provider, subject) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    account_id = EXCLUDED.account_id,
    email = EXCLUDED.email
RETURNING id, tenant_id, account_id, provider, subject, email, created_at
`

type UpsertUserIdentityParams struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	AccountID string             `json:"account_id"`
	Provider  string             `json:"provider"`
	Subject   string             `json:"subject"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertUserIdentity(ctx context.Context, arg UpsertUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, upsertUserIdentity,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.Provider,
		arg.Subject,
		arg.Email,
		arg.CreatedAt,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
