// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: form_instance_files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFormInstanceFilesByField = `-- name: CountFormInstanceFilesByField :one
SELECT COUNT(*)::bigint AS count
FROM form_instance_files
WHERE tenant_id = $1
  AND form_instance_id = $2
  AND field_id = $3
`

type CountFormInstanceFilesByFieldParams struct {
	TenantID       string `json:"tenant_id"`
	FormInstanceID string `json:"form_instance_id"`
	FieldID        string `json:"field_id"`
}

func (q *Queries) CountFormInstanceFilesByField(ctx context.Context, arg CountFormInstanceFilesByFieldParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFormInstanceFilesByField, arg.TenantID, arg.FormInstanceID, arg.FieldID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDraftFormInstanceFile = `-- name: DeleteDraftFormInstanceFile :one
DELETE FROM form_instance_files
WHERE tenant_id = $1
  AND form_instance_id = $2
  AND file_id = $3
  AND state = 'draft'
RETURNING file_id
`

type DeleteDraftFormInstanceFileParams struct {
	TenantID       string `json:"tenant_id"`
	FormInstanceID string `json:"form_instance_id"`
	FileID         string `json:"file_id"`
}

func (q *Queries) DeleteDraftFormInstanceFile(ctx context.Context, arg DeleteDraftFormInstanceFileParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteDraftFormInstanceFile, arg.TenantID, arg.FormInstanceID, arg.FileID)
	var file_id string
	err := row.Scan(&file_id)
	return file_id, err
}

const getFormInstanceFile = `-- name: GetFormInstanceFile :one
SELECT
    assets.id, assets.tenant_id, form_files.form_instance_id, form_files.field_id,
    assets.created_by_account_id, assets.original_filename,
    assets.object_provider, assets.object_bucket, assets.object_key,
    assets.content_type, assets.size_bytes, assets.sha256,
    assets.scan_status, assets.parse_status, assets.retention_class,
    form_files.state, assets.expires_at, assets.created_at, assets.updated_at
FROM form_instance_files form_files
JOIN file_assets assets
  ON assets.tenant_id = form_files.tenant_id
 AND assets.id = form_files.file_id
WHERE form_files.tenant_id = $1
  AND form_files.form_instance_id = $2
  AND form_files.file_id = $3
  AND assets.deleted_at IS NULL
`

type GetFormInstanceFileParams struct {
	TenantID       string `json:"tenant_id"`
	FormInstanceID string `json:"form_instance_id"`
	FileID         string `json:"file_id"`
}

type GetFormInstanceFileRow struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	FormInstanceID     string             `json:"form_instance_id"`
	FieldID            string             `json:"field_id"`
	CreatedByAccountID string             `json:"created_by_account_id"`
	OriginalFilename   string             `json:"original_filename"`
	ObjectProvider     string             `json:"object_provider"`
	ObjectBucket       string             `json:"object_bucket"`
	ObjectKey          string             `json:"object_key"`
	ContentType        string             `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	Sha256             string             `json:"sha256"`
	ScanStatus         string             `json:"scan_status"`
	ParseStatus        string             `json:"parse_status"`
	RetentionClass     string             `json:"retention_class"`
	State              string             `json:"state"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFormInstanceFile(ctx context.Context, arg GetFormInstanceFileParams) (GetFormInstanceFileRow, error) {
	row := q.db.QueryRow(ctx, getFormInstanceFile, arg.TenantID, arg.FormInstanceID, arg.FileID)
	var i GetFormInstanceFileRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FormInstanceID,
		&i.FieldID,
		&i.CreatedByAccountID,
		&i.OriginalFilename,
		&i.ObjectProvider,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.ScanStatus,
		&i.ParseStatus,
		&i.RetentionClass,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFormInstanceFile = `-- name: InsertFormInstanceFile :one
INSERT INTO form_instance_files (
    tenant_id, form_instance_id, file_id, field_id, state, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
RETURNING tenant_id, form_instance_id, file_id, field_id, state, created_at, updated_at
`

type InsertFormInstanceFileParams struct {
	TenantID       string             `json:"tenant_id"`
	FormInstanceID string             `json:"form_instance_id"`
	FileID         string             `json:"file_id"`
	FieldID        string             `json:"field_id"`
	State          string             `json:"state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertFormInstanceFile(ctx context.Context, arg InsertFormInstanceFileParams) (FormInstanceFile, error) {
	row := q.db.QueryRow(ctx, insertFormInstanceFile,
		arg.TenantID,
		arg.FormInstanceID,
		arg.FileID,
		arg.FieldID,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FormInstanceFile
	err := row.Scan(
		&i.TenantID,
		&i.FormInstanceID,
		&i.FileID,
		&i.FieldID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFormInstanceFiles = `-- name: ListFormInstanceFiles :many
SELECT
    assets.id, assets.tenant_id, form_files.form_instance_id, form_files.field_id,
    assets.created_by_account_id, assets.original_filename,
    assets.object_provider, assets.object_bucket, assets.object_key,
    assets.content_type, assets.size_bytes, assets.sha256,
    assets.scan_status, assets.parse_status, assets.retention_class,
    form_files.state, assets.expires_at, assets.created_at, assets.updated_at
FROM form_instance_files form_files
JOIN file_assets assets
  ON assets.tenant_id = form_files.tenant_id
 AND assets.id = form_files.file_id
WHERE form_files.tenant_id = $1
  AND form_files.form_instance_id = $2
  AND assets.deleted_at IS NULL
ORDER BY form_files.created_at ASC, assets.id ASC
`

type ListFormInstanceFilesParams struct {
	TenantID       string `json:"tenant_id"`
	FormInstanceID string `json:"form_instance_id"`
}

type ListFormInstanceFilesRow struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	FormInstanceID     string             `json:"form_instance_id"`
	FieldID            string             `json:"field_id"`
	CreatedByAccountID string             `json:"created_by_account_id"`
	OriginalFilename   string             `json:"original_filename"`
	ObjectProvider     string             `json:"object_provider"`
	ObjectBucket       string             `json:"object_bucket"`
	ObjectKey          string             `json:"object_key"`
	ContentType        string             `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	Sha256             string             `json:"sha256"`
	ScanStatus         string             `json:"scan_status"`
	ParseStatus        string             `json:"parse_status"`
	RetentionClass     string             `json:"retention_class"`
	State              string             `json:"state"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListFormInstanceFiles(ctx context.Context, arg ListFormInstanceFilesParams) ([]ListFormInstanceFilesRow, error) {
	rows, err := q.db.Query(ctx, listFormInstanceFiles, arg.TenantID, arg.FormInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormInstanceFilesRow
	for rows.Next() {
		var i ListFormInstanceFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FormInstanceID,
			&i.FieldID,
			&i.CreatedByAccountID,
			&i.OriginalFilename,
			&i.ObjectProvider,
			&i.ObjectBucket,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.ScanStatus,
			&i.ParseStatus,
			&i.RetentionClass,
			&i.State,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormInstanceFilesByField = `-- name: ListFormInstanceFilesByField :many
SELECT
    assets.id, assets.tenant_id, form_files.form_instance_id, form_files.field_id,
    assets.created_by_account_id, assets.original_filename,
    assets.object_provider, assets.object_bucket, assets.object_key,
    assets.content_type, assets.size_bytes, assets.sha256,
    assets.scan_status, assets.parse_status, assets.retention_class,
    form_files.state, assets.expires_at, assets.created_at, assets.updated_at
FROM form_instance_files form_files
JOIN file_assets assets
  ON assets.tenant_id = form_files.tenant_id
 AND assets.id = form_files.file_id
WHERE form_files.tenant_id = $1
  AND form_files.form_instance_id = $2
  AND form_files.field_id = $3
  AND assets.deleted_at IS NULL
ORDER BY form_files.created_at ASC, assets.id ASC
`

type ListFormInstanceFilesByFieldParams struct {
	TenantID       string `json:"tenant_id"`
	FormInstanceID string `json:"form_instance_id"`
	FieldID        string `json:"field_id"`
}

type ListFormInstanceFilesByFieldRow struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	FormInstanceID     string             `json:"form_instance_id"`
	FieldID            string             `json:"field_id"`
	CreatedByAccountID string             `json:"created_by_account_id"`
	OriginalFilename   string             `json:"original_filename"`
	ObjectProvider     string             `json:"object_provider"`
	ObjectBucket       string             `json:"object_bucket"`
	ObjectKey          string             `json:"object_key"`
	ContentType        string             `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	Sha256             string             `json:"sha256"`
	ScanStatus         string             `json:"scan_status"`
	ParseStatus        string             `json:"parse_status"`
	RetentionClass     string             `json:"retention_class"`
	State              string             `json:"state"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListFormInstanceFilesByField(ctx context.Context, arg ListFormInstanceFilesByFieldParams) ([]ListFormInstanceFilesByFieldRow, error) {
	rows, err := q.db.Query(ctx, listFormInstanceFilesByField, arg.TenantID, arg.FormInstanceID, arg.FieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormInstanceFilesByFieldRow
	for rows.Next() {
		var i ListFormInstanceFilesByFieldRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FormInstanceID,
			&i.FieldID,
			&i.CreatedByAccountID,
			&i.OriginalFilename,
			&i.ObjectProvider,
			&i.ObjectBucket,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.ScanStatus,
			&i.ParseStatus,
			&i.RetentionClass,
			&i.State,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFormInstanceFileAttached = `-- name: MarkFormInstanceFileAttached :one
UPDATE form_instance_files
SET state = 'attached', updated_at = $1
WHERE tenant_id = $2
  AND form_instance_id = $3
  AND file_id = $4
RETURNING tenant_id, form_instance_id, file_id, field_id, state, created_at, updated_at
`

type MarkFormInstanceFileAttachedParams struct {
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TenantID       string             `json:"tenant_id"`
	FormInstanceID string             `json:"form_instance_id"`
	FileID         string             `json:"file_id"`
}

func (q *Queries) MarkFormInstanceFileAttached(ctx context.Context, arg MarkFormInstanceFileAttachedParams) (FormInstanceFile, error) {
	row := q.db.QueryRow(ctx, markFormInstanceFileAttached,
		arg.UpdatedAt,
		arg.TenantID,
		arg.FormInstanceID,
		arg.FileID,
	)
	var i FormInstanceFile
	err := row.Scan(
		&i.TenantID,
		&i.FormInstanceID,
		&i.FileID,
		&i.FieldID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFormInstanceFilesAttached = `-- name: MarkFormInstanceFilesAttached :exec
UPDATE form_instance_files
SET state = 'attached', updated_at = $1
WHERE tenant_id = $2
  AND form_instance_id = $3
  AND state = 'draft'
`

type MarkFormInstanceFilesAttachedParams struct {
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TenantID       string             `json:"tenant_id"`
	FormInstanceID string             `json:"form_instance_id"`
}

func (q *Queries) MarkFormInstanceFilesAttached(ctx context.Context, arg MarkFormInstanceFilesAttachedParams) error {
	_, err := q.db.Exec(ctx, markFormInstanceFilesAttached, arg.UpdatedAt, arg.TenantID, arg.FormInstanceID)
	return err
}
