// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_contracts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmploymentContract = `-- name: GetEmploymentContract :one
SELECT id, tenant_id, employee_id, contract_type, contract_no, start_date, end_date, status, attachment_object_key, notes, version, created_at, updated_at FROM employment_contracts
WHERE tenant_id = $1 AND id = $2
`

type GetEmploymentContractParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetEmploymentContract(ctx context.Context, arg GetEmploymentContractParams) (EmploymentContract, error) {
	row := q.db.QueryRow(ctx, getEmploymentContract, arg.TenantID, arg.ID)
	var i EmploymentContract
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.ContractType,
		&i.ContractNo,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AttachmentObjectKey,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmploymentContracts = `-- name: ListEmploymentContracts :many
SELECT id, tenant_id, employee_id, contract_type, contract_no, start_date, end_date, status, attachment_object_key, notes, version, created_at, updated_at FROM employment_contracts
WHERE tenant_id = $1
ORDER BY start_date DESC, created_at DESC, id ASC
`

func (q *Queries) ListEmploymentContracts(ctx context.Context, tenantID string) ([]EmploymentContract, error) {
	rows, err := q.db.Query(ctx, listEmploymentContracts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmploymentContract
	for rows.Next() {
		var i EmploymentContract
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.ContractType,
			&i.ContractNo,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AttachmentObjectKey,
			&i.Notes,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmploymentContractsByEmployee = `-- name: ListEmploymentContractsByEmployee :many
SELECT id, tenant_id, employee_id, contract_type, contract_no, start_date, end_date, status, attachment_object_key, notes, version, created_at, updated_at FROM employment_contracts
WHERE tenant_id = $1 AND employee_id = $2
ORDER BY start_date DESC, created_at DESC, id ASC
`

type ListEmploymentContractsByEmployeeParams struct {
	TenantID   string `json:"tenant_id"`
	EmployeeID string `json:"employee_id"`
}

func (q *Queries) ListEmploymentContractsByEmployee(ctx context.Context, arg ListEmploymentContractsByEmployeeParams) ([]EmploymentContract, error) {
	rows, err := q.db.Query(ctx, listEmploymentContractsByEmployee, arg.TenantID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmploymentContract
	for rows.Next() {
		var i EmploymentContract
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.ContractType,
			&i.ContractNo,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AttachmentObjectKey,
			&i.Notes,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmploymentContract = `-- name: UpsertEmploymentContract :one
INSERT INTO employment_contracts (
    id, tenant_id, employee_id, contract_type, contract_no, start_date, end_date,
    status, attachment_object_key, notes, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    employee_id = EXCLUDED.employee_id,
    contract_type = EXCLUDED.contract_type,
    contract_no = EXCLUDED.contract_no,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    status = EXCLUDED.status,
    attachment_object_key = EXCLUDED.attachment_object_key,
    notes = EXCLUDED.notes,
    version = EXCLUDED.version,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, tenant_id, employee_id, contract_type, contract_no, start_date, end_date, status, attachment_object_key, notes, version, created_at, updated_at
`

type UpsertEmploymentContractParams struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	EmployeeID          string             `json:"employee_id"`
	ContractType        string             `json:"contract_type"`
	ContractNo          string             `json:"contract_no"`
	StartDate           pgtype.Timestamptz `json:"start_date"`
	EndDate             pgtype.Timestamptz `json:"end_date"`
	Status              string             `json:"status"`
	AttachmentObjectKey string             `json:"attachment_object_key"`
	Notes               string             `json:"notes"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertEmploymentContract(ctx context.Context, arg UpsertEmploymentContractParams) (EmploymentContract, error) {
	row := q.db.QueryRow(ctx, upsertEmploymentContract,
		arg.ID,
		arg.TenantID,
		arg.EmployeeID,
		arg.ContractType,
		arg.ContractNo,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.AttachmentObjectKey,
		arg.Notes,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EmploymentContract
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.ContractType,
		&i.ContractNo,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AttachmentObjectKey,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
