// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_positions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPosition = `-- name: GetPosition :one
SELECT id, tenant_id, code, name, org_unit_id, level, status, description, created_at, updated_at FROM positions
WHERE tenant_id = $1 AND id = $2
`

type GetPositionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, arg.TenantID, arg.ID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.OrgUnitID,
		&i.Level,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPositionByCode = `-- name: GetPositionByCode :one
SELECT id, tenant_id, code, name, org_unit_id, level, status, description, created_at, updated_at FROM positions
WHERE tenant_id = $1 AND lower(code) = lower($2)
`

type GetPositionByCodeParams struct {
	TenantID string `json:"tenant_id"`
	Lower    string `json:"lower"`
}

func (q *Queries) GetPositionByCode(ctx context.Context, arg GetPositionByCodeParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPositionByCode, arg.TenantID, arg.Lower)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.OrgUnitID,
		&i.Level,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPositionByName = `-- name: GetPositionByName :one
SELECT id, tenant_id, code, name, org_unit_id, level, status, description, created_at, updated_at FROM positions
WHERE tenant_id = $1 AND lower(name) = lower($2)
`

type GetPositionByNameParams struct {
	TenantID string `json:"tenant_id"`
	Lower    string `json:"lower"`
}

func (q *Queries) GetPositionByName(ctx context.Context, arg GetPositionByNameParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPositionByName, arg.TenantID, arg.Lower)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.OrgUnitID,
		&i.Level,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPositions = `-- name: ListPositions :many
SELECT id, tenant_id, code, name, org_unit_id, level, status, description, created_at, updated_at FROM positions
WHERE tenant_id = $1
ORDER BY
  CASE WHEN status = 'active' THEN 0 ELSE 1 END,
  name ASC,
  created_at ASC,
  id ASC
`

func (q *Queries) ListPositions(ctx context.Context, tenantID string) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.OrgUnitID,
			&i.Level,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPosition = `-- name: UpsertPosition :one
INSERT INTO positions (
    id, tenant_id, code, name, org_unit_id, level, status, description, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    org_unit_id = EXCLUDED.org_unit_id,
    level = EXCLUDED.level,
    status = EXCLUDED.status,
    description = EXCLUDED.description,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, tenant_id, code, name, org_unit_id, level, status, description, created_at, updated_at
`

type UpsertPositionParams struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	OrgUnitID   string             `json:"org_unit_id"`
	Level       string             `json:"level"`
	Status      string             `json:"status"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, upsertPosition,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.OrgUnitID,
		arg.Level,
		arg.Status,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.OrgUnitID,
		&i.Level,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
