// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_provisioning.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendIdentityProvisioningOutboxEvent = `-- name: AppendIdentityProvisioningOutboxEvent :one
INSERT INTO identity_provisioning_outbox (
    id, tenant_id, account_id, employee_id, employee_no, email,
    display_name, enabled, send_invite, status, retry_count,
    last_error, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, tenant_id, account_id, employee_id, employee_no, email, display_name, enabled, send_invite, status, retry_count, last_error, created_at, updated_at
`

type AppendIdentityProvisioningOutboxEventParams struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	AccountID   string             `json:"account_id"`
	EmployeeID  string             `json:"employee_id"`
	EmployeeNo  string             `json:"employee_no"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Enabled     bool               `json:"enabled"`
	SendInvite  bool               `json:"send_invite"`
	Status      string             `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	LastError   string             `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AppendIdentityProvisioningOutboxEvent(ctx context.Context, arg AppendIdentityProvisioningOutboxEventParams) (IdentityProvisioningOutbox, error) {
	row := q.db.QueryRow(ctx, appendIdentityProvisioningOutboxEvent,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.EmployeeID,
		arg.EmployeeNo,
		arg.Email,
		arg.DisplayName,
		arg.Enabled,
		arg.SendInvite,
		arg.Status,
		arg.RetryCount,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i IdentityProvisioningOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.EmployeeID,
		&i.EmployeeNo,
		&i.Email,
		&i.DisplayName,
		&i.Enabled,
		&i.SendInvite,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingIdentityProvisioningOutboxEvents = `-- name: ListPendingIdentityProvisioningOutboxEvents :many
SELECT id, tenant_id, account_id, employee_id, employee_no, email, display_name, enabled, send_invite, status, retry_count, last_error, created_at, updated_at FROM identity_provisioning_outbox
WHERE tenant_id = $1 AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingIdentityProvisioningOutboxEvents(ctx context.Context, tenantID string) ([]IdentityProvisioningOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingIdentityProvisioningOutboxEvents, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityProvisioningOutbox
	for rows.Next() {
		var i IdentityProvisioningOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.EmployeeID,
			&i.EmployeeNo,
			&i.Email,
			&i.DisplayName,
			&i.Enabled,
			&i.SendInvite,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIdentityProvisioningOutboxEvent = `-- name: UpdateIdentityProvisioningOutboxEvent :one
UPDATE identity_provisioning_outbox
SET status = $3,
    retry_count = $4,
    last_error = $5,
    updated_at = $6
WHERE tenant_id = $1
  AND id = $2
RETURNING id, tenant_id, account_id, employee_id, employee_no, email, display_name, enabled, send_invite, status, retry_count, last_error, created_at, updated_at
`

type UpdateIdentityProvisioningOutboxEventParams struct {
	TenantID   string             `json:"tenant_id"`
	ID         string             `json:"id"`
	Status     string             `json:"status"`
	RetryCount int32              `json:"retry_count"`
	LastError  string             `json:"last_error"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateIdentityProvisioningOutboxEvent(ctx context.Context, arg UpdateIdentityProvisioningOutboxEventParams) (IdentityProvisioningOutbox, error) {
	row := q.db.QueryRow(ctx, updateIdentityProvisioningOutboxEvent,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.RetryCount,
		arg.LastError,
		arg.UpdatedAt,
	)
	var i IdentityProvisioningOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.EmployeeID,
		&i.EmployeeNo,
		&i.Email,
		&i.DisplayName,
		&i.Enabled,
		&i.SendInvite,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
