// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const countKnowledgeBases = `-- name: CountKnowledgeBases :one
SELECT count(*) FROM knowledge_bases
WHERE tenant_id = $1
`

func (q *Queries) CountKnowledgeBases(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledgeBases, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKnowledgeDocuments = `-- name: CountKnowledgeDocuments :one
SELECT count(*) FROM knowledge_documents
WHERE tenant_id = $1
  AND knowledge_base_id = $2
`

type CountKnowledgeDocumentsParams struct {
	TenantID        string `json:"tenant_id"`
	KnowledgeBaseID string `json:"knowledge_base_id"`
}

func (q *Queries) CountKnowledgeDocuments(ctx context.Context, arg CountKnowledgeDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledgeDocuments, arg.TenantID, arg.KnowledgeBaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKnowledgeDocumentsByBase = `-- name: CountKnowledgeDocumentsByBase :many
SELECT knowledge_base_id, count(*)::int AS document_count
FROM knowledge_documents
WHERE tenant_id = $1
  AND knowledge_base_id = ANY($2::text[])
GROUP BY knowledge_base_id
`

type CountKnowledgeDocumentsByBaseParams struct {
	TenantID         string   `json:"tenant_id"`
	KnowledgeBaseIds []string `json:"knowledge_base_ids"`
}

type CountKnowledgeDocumentsByBaseRow struct {
	KnowledgeBaseID string `json:"knowledge_base_id"`
	DocumentCount   int32  `json:"document_count"`
}

func (q *Queries) CountKnowledgeDocumentsByBase(ctx context.Context, arg CountKnowledgeDocumentsByBaseParams) ([]CountKnowledgeDocumentsByBaseRow, error) {
	rows, err := q.db.Query(ctx, countKnowledgeDocumentsByBase, arg.TenantID, arg.KnowledgeBaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountKnowledgeDocumentsByBaseRow
	for rows.Next() {
		var i CountKnowledgeDocumentsByBaseRow
		if err := rows.Scan(&i.KnowledgeBaseID, &i.DocumentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createKnowledgeDocumentChunk = `-- name: CreateKnowledgeDocumentChunk :exec
INSERT INTO knowledge_document_chunks (
    id, tenant_id, knowledge_base_id, document_id, ordinal, content,
    embedding_model, embedding_dimensions, embedding, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9::vector,
    $10
)
`

type CreateKnowledgeDocumentChunkParams struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	KnowledgeBaseID     string             `json:"knowledge_base_id"`
	DocumentID          string             `json:"document_id"`
	Ordinal             int32              `json:"ordinal"`
	Content             string             `json:"content"`
	EmbeddingModel      string             `json:"embedding_model"`
	EmbeddingDimensions int32              `json:"embedding_dimensions"`
	Embedding           pgvector.Vector    `json:"embedding"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateKnowledgeDocumentChunk(ctx context.Context, arg CreateKnowledgeDocumentChunkParams) error {
	_, err := q.db.Exec(ctx, createKnowledgeDocumentChunk,
		arg.ID,
		arg.TenantID,
		arg.KnowledgeBaseID,
		arg.DocumentID,
		arg.Ordinal,
		arg.Content,
		arg.EmbeddingModel,
		arg.EmbeddingDimensions,
		arg.Embedding,
		arg.CreatedAt,
	)
	return err
}

const deleteKnowledgeBase = `-- name: DeleteKnowledgeBase :one
DELETE FROM knowledge_bases
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, name, description, chunk_mode, chunk_size, chunk_overlap, created_by_account_id, updated_by_account_id, created_at, updated_at
`

type DeleteKnowledgeBaseParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteKnowledgeBase(ctx context.Context, arg DeleteKnowledgeBaseParams) (KnowledgeBasis, error) {
	row := q.db.QueryRow(ctx, deleteKnowledgeBase, arg.TenantID, arg.ID)
	var i KnowledgeBasis
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ChunkMode,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKnowledgeDocument = `-- name: DeleteKnowledgeDocument :one
DELETE FROM knowledge_documents
WHERE tenant_id = $1
  AND knowledge_base_id = $2
  AND id = $3
RETURNING id, tenant_id, knowledge_base_id, title, content, source_type, original_filename, content_type, size_bytes, sha256, object_provider, object_bucket, object_key, parse_status, parse_error, created_by_account_id, updated_by_account_id, created_at, updated_at
`

type DeleteKnowledgeDocumentParams struct {
	TenantID        string `json:"tenant_id"`
	KnowledgeBaseID string `json:"knowledge_base_id"`
	ID              string `json:"id"`
}

func (q *Queries) DeleteKnowledgeDocument(ctx context.Context, arg DeleteKnowledgeDocumentParams) (KnowledgeDocument, error) {
	row := q.db.QueryRow(ctx, deleteKnowledgeDocument, arg.TenantID, arg.KnowledgeBaseID, arg.ID)
	var i KnowledgeDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KnowledgeBaseID,
		&i.Title,
		&i.Content,
		&i.SourceType,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.ObjectProvider,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ParseStatus,
		&i.ParseError,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKnowledgeDocumentChunks = `-- name: DeleteKnowledgeDocumentChunks :exec
DELETE FROM knowledge_document_chunks
WHERE tenant_id = $1
  AND document_id = $2
`

type DeleteKnowledgeDocumentChunksParams struct {
	TenantID   string `json:"tenant_id"`
	DocumentID string `json:"document_id"`
}

func (q *Queries) DeleteKnowledgeDocumentChunks(ctx context.Context, arg DeleteKnowledgeDocumentChunksParams) error {
	_, err := q.db.Exec(ctx, deleteKnowledgeDocumentChunks, arg.TenantID, arg.DocumentID)
	return err
}

const getKnowledgeBase = `-- name: GetKnowledgeBase :one
SELECT id, tenant_id, name, description, chunk_mode, chunk_size, chunk_overlap, created_by_account_id, updated_by_account_id, created_at, updated_at FROM knowledge_bases
WHERE tenant_id = $1 AND id = $2
`

type GetKnowledgeBaseParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetKnowledgeBase(ctx context.Context, arg GetKnowledgeBaseParams) (KnowledgeBasis, error) {
	row := q.db.QueryRow(ctx, getKnowledgeBase, arg.TenantID, arg.ID)
	var i KnowledgeBasis
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ChunkMode,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKnowledgeDocument = `-- name: GetKnowledgeDocument :one
SELECT id, tenant_id, knowledge_base_id, title, content, source_type, original_filename, content_type, size_bytes, sha256, object_provider, object_bucket, object_key, parse_status, parse_error, created_by_account_id, updated_by_account_id, created_at, updated_at FROM knowledge_documents
WHERE tenant_id = $1
  AND knowledge_base_id = $2
  AND id = $3
`

type GetKnowledgeDocumentParams struct {
	TenantID        string `json:"tenant_id"`
	KnowledgeBaseID string `json:"knowledge_base_id"`
	ID              string `json:"id"`
}

func (q *Queries) GetKnowledgeDocument(ctx context.Context, arg GetKnowledgeDocumentParams) (KnowledgeDocument, error) {
	row := q.db.QueryRow(ctx, getKnowledgeDocument, arg.TenantID, arg.KnowledgeBaseID, arg.ID)
	var i KnowledgeDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KnowledgeBaseID,
		&i.Title,
		&i.Content,
		&i.SourceType,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.ObjectProvider,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ParseStatus,
		&i.ParseError,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKnowledgeBases = `-- name: ListKnowledgeBases :many
SELECT id, tenant_id, name, description, chunk_mode, chunk_size, chunk_overlap, created_by_account_id, updated_by_account_id, created_at, updated_at FROM knowledge_bases
WHERE tenant_id = $1
ORDER BY updated_at DESC, id ASC
`

func (q *Queries) ListKnowledgeBases(ctx context.Context, tenantID string) ([]KnowledgeBasis, error) {
	rows, err := q.db.Query(ctx, listKnowledgeBases, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeBasis
	for rows.Next() {
		var i KnowledgeBasis
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.ChunkMode,
			&i.ChunkSize,
			&i.ChunkOverlap,
			&i.CreatedByAccountID,
			&i.UpdatedByAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeBasesPage = `-- name: ListKnowledgeBasesPage :many
SELECT id, tenant_id, name, description, chunk_mode, chunk_size, chunk_overlap, created_by_account_id, updated_by_account_id, created_at, updated_at FROM knowledge_bases
WHERE tenant_id = $1
ORDER BY
  CASE WHEN $2::text = 'created_at_asc' THEN created_at END ASC,
  created_at DESC,
  id ASC
LIMIT $4::int
OFFSET $3::int
`

type ListKnowledgeBasesPageParams struct {
	TenantID    string `json:"tenant_id"`
	Sort        string `json:"sort"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

func (q *Queries) ListKnowledgeBasesPage(ctx context.Context, arg ListKnowledgeBasesPageParams) ([]KnowledgeBasis, error) {
	rows, err := q.db.Query(ctx, listKnowledgeBasesPage,
		arg.TenantID,
		arg.Sort,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeBasis
	for rows.Next() {
		var i KnowledgeBasis
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.ChunkMode,
			&i.ChunkSize,
			&i.ChunkOverlap,
			&i.CreatedByAccountID,
			&i.UpdatedByAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeDocuments = `-- name: ListKnowledgeDocuments :many
SELECT id, tenant_id, knowledge_base_id, title, content, source_type, original_filename, content_type, size_bytes, sha256, object_provider, object_bucket, object_key, parse_status, parse_error, created_by_account_id, updated_by_account_id, created_at, updated_at FROM knowledge_documents
WHERE tenant_id = $1
  AND knowledge_base_id = $2
ORDER BY updated_at DESC, id ASC
`

type ListKnowledgeDocumentsParams struct {
	TenantID        string `json:"tenant_id"`
	KnowledgeBaseID string `json:"knowledge_base_id"`
}

func (q *Queries) ListKnowledgeDocuments(ctx context.Context, arg ListKnowledgeDocumentsParams) ([]KnowledgeDocument, error) {
	rows, err := q.db.Query(ctx, listKnowledgeDocuments, arg.TenantID, arg.KnowledgeBaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeDocument
	for rows.Next() {
		var i KnowledgeDocument
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.KnowledgeBaseID,
			&i.Title,
			&i.Content,
			&i.SourceType,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.ObjectProvider,
			&i.ObjectBucket,
			&i.ObjectKey,
			&i.ParseStatus,
			&i.ParseError,
			&i.CreatedByAccountID,
			&i.UpdatedByAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeDocumentsPage = `-- name: ListKnowledgeDocumentsPage :many
SELECT id, tenant_id, knowledge_base_id, title, source_type, original_filename,
    content_type, size_bytes, sha256, object_provider, object_bucket, object_key,
    parse_status, parse_error, created_by_account_id, updated_by_account_id, created_at, updated_at
FROM knowledge_documents
WHERE tenant_id = $1
  AND knowledge_base_id = $2
ORDER BY
  CASE WHEN $3::text = 'created_at_asc' THEN created_at END ASC,
  created_at DESC,
  id ASC
LIMIT $5::int
OFFSET $4::int
`

type ListKnowledgeDocumentsPageParams struct {
	TenantID        string `json:"tenant_id"`
	KnowledgeBaseID string `json:"knowledge_base_id"`
	Sort            string `json:"sort"`
	OffsetCount     int32  `json:"offset_count"`
	LimitCount      int32  `json:"limit_count"`
}

type ListKnowledgeDocumentsPageRow struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	KnowledgeBaseID    string             `json:"knowledge_base_id"`
	Title              string             `json:"title"`
	SourceType         string             `json:"source_type"`
	OriginalFilename   string             `json:"original_filename"`
	ContentType        string             `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	Sha256             string             `json:"sha256"`
	ObjectProvider     string             `json:"object_provider"`
	ObjectBucket       string             `json:"object_bucket"`
	ObjectKey          string             `json:"object_key"`
	ParseStatus        string             `json:"parse_status"`
	ParseError         string             `json:"parse_error"`
	CreatedByAccountID pgtype.Text        `json:"created_by_account_id"`
	UpdatedByAccountID pgtype.Text        `json:"updated_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListKnowledgeDocumentsPage(ctx context.Context, arg ListKnowledgeDocumentsPageParams) ([]ListKnowledgeDocumentsPageRow, error) {
	rows, err := q.db.Query(ctx, listKnowledgeDocumentsPage,
		arg.TenantID,
		arg.KnowledgeBaseID,
		arg.Sort,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKnowledgeDocumentsPageRow
	for rows.Next() {
		var i ListKnowledgeDocumentsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.KnowledgeBaseID,
			&i.Title,
			&i.SourceType,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.ObjectProvider,
			&i.ObjectBucket,
			&i.ObjectKey,
			&i.ParseStatus,
			&i.ParseError,
			&i.CreatedByAccountID,
			&i.UpdatedByAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKnowledgeDocumentChunks = `-- name: SearchKnowledgeDocumentChunks :many
SELECT
    c.id,
    c.knowledge_base_id,
    b.name AS knowledge_base_name,
    c.document_id,
    d.title,
    c.ordinal,
    c.content,
    (1 - (c.embedding <=> $1::vector))::double precision AS score
FROM knowledge_document_chunks c
JOIN knowledge_bases b
  ON b.tenant_id = c.tenant_id AND b.id = c.knowledge_base_id
JOIN knowledge_documents d
  ON d.tenant_id = c.tenant_id AND d.id = c.document_id
WHERE c.tenant_id = $2
  AND c.knowledge_base_id = ANY($3::text[])
  AND c.embedding_model = $4
  AND c.embedding_dimensions = $5
ORDER BY c.embedding <=> $1::vector, c.id
LIMIT $6
`

type SearchKnowledgeDocumentChunksParams struct {
	QueryEmbedding      pgvector.Vector `json:"query_embedding"`
	TenantID            string          `json:"tenant_id"`
	KnowledgeBaseIds    []string        `json:"knowledge_base_ids"`
	EmbeddingModel      string          `json:"embedding_model"`
	EmbeddingDimensions int32           `json:"embedding_dimensions"`
	ResultLimit         int32           `json:"result_limit"`
}

type SearchKnowledgeDocumentChunksRow struct {
	ID                string  `json:"id"`
	KnowledgeBaseID   string  `json:"knowledge_base_id"`
	KnowledgeBaseName string  `json:"knowledge_base_name"`
	DocumentID        string  `json:"document_id"`
	Title             string  `json:"title"`
	Ordinal           int32   `json:"ordinal"`
	Content           string  `json:"content"`
	Score             float64 `json:"score"`
}

func (q *Queries) SearchKnowledgeDocumentChunks(ctx context.Context, arg SearchKnowledgeDocumentChunksParams) ([]SearchKnowledgeDocumentChunksRow, error) {
	rows, err := q.db.Query(ctx, searchKnowledgeDocumentChunks,
		arg.QueryEmbedding,
		arg.TenantID,
		arg.KnowledgeBaseIds,
		arg.EmbeddingModel,
		arg.EmbeddingDimensions,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchKnowledgeDocumentChunksRow
	for rows.Next() {
		var i SearchKnowledgeDocumentChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeBaseID,
			&i.KnowledgeBaseName,
			&i.DocumentID,
			&i.Title,
			&i.Ordinal,
			&i.Content,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertKnowledgeBase = `-- name: UpsertKnowledgeBase :one
INSERT INTO knowledge_bases (
    id, tenant_id, name, description, chunk_mode, chunk_size, chunk_overlap,
    created_by_account_id, updated_by_account_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    chunk_mode = EXCLUDED.chunk_mode,
    chunk_size = EXCLUDED.chunk_size,
    chunk_overlap = EXCLUDED.chunk_overlap,
    updated_by_account_id = EXCLUDED.updated_by_account_id,
    updated_at = EXCLUDED.updated_at
RETURNING id, tenant_id, name, description, chunk_mode, chunk_size, chunk_overlap, created_by_account_id, updated_by_account_id, created_at, updated_at
`

type UpsertKnowledgeBaseParams struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	ChunkMode          string             `json:"chunk_mode"`
	ChunkSize          int32              `json:"chunk_size"`
	ChunkOverlap       int32              `json:"chunk_overlap"`
	CreatedByAccountID pgtype.Text        `json:"created_by_account_id"`
	UpdatedByAccountID pgtype.Text        `json:"updated_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertKnowledgeBase(ctx context.Context, arg UpsertKnowledgeBaseParams) (KnowledgeBasis, error) {
	row := q.db.QueryRow(ctx, upsertKnowledgeBase,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.ChunkMode,
		arg.ChunkSize,
		arg.ChunkOverlap,
		arg.CreatedByAccountID,
		arg.UpdatedByAccountID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i KnowledgeBasis
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ChunkMode,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKnowledgeDocument = `-- name: UpsertKnowledgeDocument :one
INSERT INTO knowledge_documents (
    id, tenant_id, knowledge_base_id, title, content, source_type, original_filename,
    content_type, size_bytes, sha256, object_provider, object_bucket, object_key, parse_status, parse_error,
    created_by_account_id, updated_by_account_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    source_type = EXCLUDED.source_type,
    original_filename = EXCLUDED.original_filename,
    content_type = EXCLUDED.content_type,
    size_bytes = EXCLUDED.size_bytes,
    sha256 = EXCLUDED.sha256,
    object_provider = EXCLUDED.object_provider,
    object_bucket = EXCLUDED.object_bucket,
    object_key = EXCLUDED.object_key,
    parse_status = EXCLUDED.parse_status,
    parse_error = EXCLUDED.parse_error,
    updated_by_account_id = EXCLUDED.updated_by_account_id,
    updated_at = EXCLUDED.updated_at
RETURNING id, tenant_id, knowledge_base_id, title, content, source_type, original_filename, content_type, size_bytes, sha256, object_provider, object_bucket, object_key, parse_status, parse_error, created_by_account_id, updated_by_account_id, created_at, updated_at
`

type UpsertKnowledgeDocumentParams struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	KnowledgeBaseID    string             `json:"knowledge_base_id"`
	Title              string             `json:"title"`
	Content            string             `json:"content"`
	SourceType         string             `json:"source_type"`
	OriginalFilename   string             `json:"original_filename"`
	ContentType        string             `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	Sha256             string             `json:"sha256"`
	ObjectProvider     string             `json:"object_provider"`
	ObjectBucket       string             `json:"object_bucket"`
	ObjectKey          string             `json:"object_key"`
	ParseStatus        string             `json:"parse_status"`
	ParseError         string             `json:"parse_error"`
	CreatedByAccountID pgtype.Text        `json:"created_by_account_id"`
	UpdatedByAccountID pgtype.Text        `json:"updated_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertKnowledgeDocument(ctx context.Context, arg UpsertKnowledgeDocumentParams) (KnowledgeDocument, error) {
	row := q.db.QueryRow(ctx, upsertKnowledgeDocument,
		arg.ID,
		arg.TenantID,
		arg.KnowledgeBaseID,
		arg.Title,
		arg.Content,
		arg.SourceType,
		arg.OriginalFilename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.ObjectProvider,
		arg.ObjectBucket,
		arg.ObjectKey,
		arg.ParseStatus,
		arg.ParseError,
		arg.CreatedByAccountID,
		arg.UpdatedByAccountID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i KnowledgeDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KnowledgeBaseID,
		&i.Title,
		&i.Content,
		&i.SourceType,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.ObjectProvider,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ParseStatus,
		&i.ParseError,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
