// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Account struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	DisplayName            string             `json:"display_name"`
	Email                  string             `json:"email"`
	EmployeeID             string             `json:"employee_id"`
	Status                 string             `json:"status"`
	UserGroupIds           []string           `json:"user_group_ids"`
	DirectPermissionSetIds []string           `json:"direct_permission_set_ids"`
	ActiveAssumableRoleID  string             `json:"active_assumable_role_id"`
	PreferredLocale        string             `json:"preferred_locale"`
	Version                int64              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type AgentDefinition struct {
	ID                            string             `json:"id"`
	TenantID                      string             `json:"tenant_id"`
	Name                          string             `json:"name"`
	Description                   string             `json:"description"`
	Emoji                         string             `json:"emoji"`
	Category                      string             `json:"category"`
	ModelID                       string             `json:"model_id"`
	MainAgentRole                 string             `json:"main_agent_role"`
	SubAgents                     []byte             `json:"sub_agents"`
	SystemPrompt                  string             `json:"system_prompt"`
	WelcomeMessage                string             `json:"welcome_message"`
	SuggestedQuestions            []byte             `json:"suggested_questions"`
	SuggestedQuestionTranslations []byte             `json:"suggested_question_translations"`
	Tools                         []byte             `json:"tools"`
	KnowledgeBaseIds              []byte             `json:"knowledge_base_ids"`
	Status                        string             `json:"status"`
	Visibility                    string             `json:"visibility"`
	VisibilityTargets             []byte             `json:"visibility_targets"`
	TimeoutSeconds                int32              `json:"timeout_seconds"`
	Version                       int32              `json:"version"`
	PublishedVersion              int32              `json:"published_version"`
	UsageTotalRuns                int64              `json:"usage_total_runs"`
	UsageSuccessRuns              int64              `json:"usage_success_runs"`
	UsageFailedRuns               int64              `json:"usage_failed_runs"`
	UsageAvgLatencyMs             int32              `json:"usage_avg_latency_ms"`
	UsageLastRunAt                pgtype.Timestamptz `json:"usage_last_run_at"`
	UsageTopPrompts               []byte             `json:"usage_top_prompts"`
	CreatedByAccountID            pgtype.Text        `json:"created_by_account_id"`
	UpdatedByAccountID            pgtype.Text        `json:"updated_by_account_id"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
}

type AgentDefinitionVersion struct {
	ID                            string             `json:"id"`
	TenantID                      string             `json:"tenant_id"`
	AgentID                       string             `json:"agent_id"`
	Version                       int32              `json:"version"`
	MainAgentRole                 string             `json:"main_agent_role"`
	SubAgents                     []byte             `json:"sub_agents"`
	SystemPrompt                  string             `json:"system_prompt"`
	WelcomeMessage                string             `json:"welcome_message"`
	SuggestedQuestions            []byte             `json:"suggested_questions"`
	SuggestedQuestionTranslations []byte             `json:"suggested_question_translations"`
	Tools                         []byte             `json:"tools"`
	KnowledgeBaseIds              []byte             `json:"knowledge_base_ids"`
	ModelID                       string             `json:"model_id"`
	Note                          string             `json:"note"`
	CreatedByAccountID            pgtype.Text        `json:"created_by_account_id"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
}

type AgentExternalTool struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	Name                 string             `json:"name"`
	Description          string             `json:"description"`
	Kind                 string             `json:"kind"`
	Transport            string             `json:"transport"`
	EndpointUrl          string             `json:"endpoint_url"`
	AuthType             string             `json:"auth_type"`
	AuthHeaderName       string             `json:"auth_header_name"`
	AuthUsername         string             `json:"auth_username"`
	AuthSecretCiphertext string             `json:"auth_secret_ciphertext"`
	CreatedByAccountID   pgtype.Text        `json:"created_by_account_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type AgentMemory struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	AccountID  string             `json:"account_id"`
	AgentID    pgtype.Text        `json:"agent_id"`
	SessionID  pgtype.Text        `json:"session_id"`
	Key        string             `json:"key"`
	Content    string             `json:"content"`
	Source     string             `json:"source"`
	Importance int32              `json:"importance"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AgentMessageAttachment struct {
	TenantID  string             `json:"tenant_id"`
	MessageID string             `json:"message_id"`
	FileID    string             `json:"file_id"`
	Ordinal   int32              `json:"ordinal"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AgentModel struct {
	ID               string             `json:"id"`
	TenantID         string             `json:"tenant_id"`
	Name             string             `json:"name"`
	Provider         string             `json:"provider"`
	ModelName        string             `json:"model_name"`
	LitellmModel     string             `json:"litellm_model"`
	ApiBaseUrl       string             `json:"api_base_url"`
	ApiKeyCiphertext string             `json:"api_key_ciphertext"`
	ApiKeyPreview    string             `json:"api_key_preview"`
	RateLimitRpm     int32              `json:"rate_limit_rpm"`
	Status           string             `json:"status"`
	TimeoutSeconds   int32              `json:"timeout_seconds"`
	MonthlyQuota     int64              `json:"monthly_quota"`
	UsedQuota        int64              `json:"used_quota"`
	LastTestedAt     pgtype.Timestamptz `json:"last_tested_at"`
	LastTestStatus   string             `json:"last_test_status"`
	LastTestMessage  string             `json:"last_test_message"`
	SyncStatus       string             `json:"sync_status"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	LastSyncError    string             `json:"last_sync_error"`
	SyncedConfigHash string             `json:"synced_config_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AgentRun struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	AgentID        pgtype.Text        `json:"agent_id"`
	SessionID      pgtype.Text        `json:"session_id"`
	Mode           string             `json:"mode"`
	Prompt         string             `json:"prompt"`
	Answer         string             `json:"answer"`
	Status         string             `json:"status"`
	ReferenceItems []byte             `json:"reference_items"`
	LlmCallCount   int64              `json:"llm_call_count"`
	InputTokens    int64              `json:"input_tokens"`
	CachedTokens   int64              `json:"cached_tokens"`
	OutputTokens   int64              `json:"output_tokens"`
	TotalTokens    int64              `json:"total_tokens"`
	UsageComplete  bool               `json:"usage_complete"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AgentSession struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	AgentID        pgtype.Text        `json:"agent_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	ContextVersion int64              `json:"context_version"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AgentSessionFile struct {
	TenantID       string             `json:"tenant_id"`
	SessionID      string             `json:"session_id"`
	FileID         string             `json:"file_id"`
	ContextVersion int64              `json:"context_version"`
	State          string             `json:"state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AgentSessionMessage struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	SessionID      string             `json:"session_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	RunID          pgtype.Text        `json:"run_id"`
	ContextVersion int64              `json:"context_version"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AssumableRole struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	PermissionSetIds       []string           `json:"permission_set_ids"`
	Trusted                bool               `json:"trusted"`
	TrustPolicy            []byte             `json:"trust_policy"`
	PermissionBoundary     []byte             `json:"permission_boundary"`
	SessionDurationSeconds int32              `json:"session_duration_seconds"`
	SourceTemplateKey      string             `json:"source_template_key"`
	SourcePackageVersion   string             `json:"source_package_version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type AssumableRoleTemplate struct {
	ID          string `json:"id"`
	PackageID   string `json:"package_id"`
	TemplateKey string `json:"template_key"`
	Name        string `json:"name"`
	Content     []byte `json:"content"`
	Version     string `json:"version"`
}

type AttendanceClockRecord struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	EmployeeID          string             `json:"employee_id"`
	ShiftAssignmentID   pgtype.Text        `json:"shift_assignment_id"`
	ShiftID             pgtype.Text        `json:"shift_id"`
	WorksiteID          pgtype.Text        `json:"worksite_id"`
	WorkDate            string             `json:"work_date"`
	Direction           string             `json:"direction"`
	ClientEventID       string             `json:"client_event_id"`
	ClockedAt           pgtype.Timestamptz `json:"clocked_at"`
	Latitude            float64            `json:"latitude"`
	Longitude           float64            `json:"longitude"`
	AccuracyMeters      float64            `json:"accuracy_meters"`
	DistanceMeters      float64            `json:"distance_meters"`
	RecordStatus        string             `json:"record_status"`
	RejectionReason     string             `json:"rejection_reason"`
	Source              string             `json:"source"`
	DeviceID            string             `json:"device_id"`
	DeviceInfo          []byte             `json:"device_info"`
	CorrectionRequestID string             `json:"correction_request_id"`
	Voided              bool               `json:"voided"`
	VoidedAt            pgtype.Timestamptz `json:"voided_at"`
	VoidedByAccountID   string             `json:"voided_by_account_id"`
	VoidReason          string             `json:"void_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type AttendanceCorrectionRequest struct {
	ID                       string             `json:"id"`
	TenantID                 string             `json:"tenant_id"`
	EmployeeID               string             `json:"employee_id"`
	Direction                string             `json:"direction"`
	RequestedClockedAt       pgtype.Timestamptz `json:"requested_clocked_at"`
	WorkDate                 string             `json:"work_date"`
	CorrectionType           string             `json:"correction_type"`
	TargetClockRecordID      string             `json:"target_clock_record_id"`
	ReplacementClockRecordID string             `json:"replacement_clock_record_id"`
	Reason                   string             `json:"reason"`
	Status                   string             `json:"status"`
	FormInstanceID           string             `json:"form_instance_id"`
	ClockRecordID            string             `json:"clock_record_id"`
	ReviewedByAccountID      string             `json:"reviewed_by_account_id"`
	ReviewReason             string             `json:"review_reason"`
	ReviewedAt               pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceDailySummary struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	EmployeeID      string             `json:"employee_id"`
	WorkDate        string             `json:"work_date"`
	ShiftStart      string             `json:"shift_start"`
	ShiftEnd        string             `json:"shift_end"`
	ShiftHours      float64            `json:"shift_hours"`
	DailyHours      float64            `json:"daily_hours"`
	ClockHours      float64            `json:"clock_hours"`
	ClockStart      string             `json:"clock_start"`
	ClockEnd        string             `json:"clock_end"`
	AttendStart     string             `json:"attend_start"`
	AttendEnd       string             `json:"attend_end"`
	AttendHours     float64            `json:"attend_hours"`
	AttendCounted   bool               `json:"attend_counted"`
	LeaveType       string             `json:"leave_type"`
	LeaveStart      string             `json:"leave_start"`
	LeaveEnd        string             `json:"leave_end"`
	LeaveHours      float64            `json:"leave_hours"`
	LeaveCounted    bool               `json:"leave_counted"`
	Leave2Type      string             `json:"leave2_type"`
	Leave2Start     string             `json:"leave2_start"`
	Leave2End       string             `json:"leave2_end"`
	Leave2Hours     float64            `json:"leave2_hours"`
	Leave2Counted   bool               `json:"leave2_counted"`
	OvertimeStart   string             `json:"overtime_start"`
	OvertimeEnd     string             `json:"overtime_end"`
	OvertimeHours   float64            `json:"overtime_hours"`
	OvertimeCounted bool               `json:"overtime_counted"`
	Payload         []byte             `json:"payload"`
	Source          string             `json:"source"`
	ExternalRef     string             `json:"external_ref"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AttendancePolicy struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	WorkTime           []byte             `json:"work_time"`
	LeaveTypes         []byte             `json:"leave_types"`
	Version            int32              `json:"version"`
	EffectiveFrom      pgtype.Timestamptz `json:"effective_from"`
	UpdatedByAccountID string             `json:"updated_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AttendancePolicyVersion struct {
	TenantID           string             `json:"tenant_id"`
	Version            int32              `json:"version"`
	PolicyID           string             `json:"policy_id"`
	WorkTime           []byte             `json:"work_time"`
	LeaveTypes         []byte             `json:"leave_types"`
	EffectiveFrom      pgtype.Timestamptz `json:"effective_from"`
	UpdatedByAccountID string             `json:"updated_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type AttendanceShift struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	Name                   string             `json:"name"`
	ClockInStart           string             `json:"clock_in_start"`
	ClockInEnd             string             `json:"clock_in_end"`
	ClockOutStart          string             `json:"clock_out_start"`
	ClockOutEnd            string             `json:"clock_out_end"`
	LateGraceMinutes       int32              `json:"late_grace_minutes"`
	EarlyLeaveGraceMinutes int32              `json:"early_leave_grace_minutes"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceShiftAssignment struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	EmployeeID    string             `json:"employee_id"`
	ShiftID       string             `json:"shift_id"`
	WorksiteID    string             `json:"worksite_id"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceWorksite struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	Name         string             `json:"name"`
	Address      string             `json:"address"`
	Latitude     float64            `json:"latitude"`
	Longitude    float64            `json:"longitude"`
	RadiusMeters int32              `json:"radius_meters"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	ActorAccountID string             `json:"actor_account_id"`
	Action         string             `json:"action"`
	Resource       string             `json:"resource"`
	Target         string             `json:"target"`
	Result         string             `json:"result"`
	TraceID        string             `json:"trace_id"`
	Severity       string             `json:"severity"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuthzAssumableRoleSession struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	AssumableRoleID string             `json:"assumable_role_id"`
	SessionPolicy   []byte             `json:"session_policy"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzDataScope struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	ScopeType string             `json:"scope_type"`
	Params    []byte             `json:"params"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthzFieldPolicy struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	ApplicationCode string             `json:"application_code"`
	ResourceType    string             `json:"resource_type"`
	FieldName       string             `json:"field_name"`
	Effect          string             `json:"effect"`
	MaskStrategy    string             `json:"mask_strategy"`
	PermissionID    string             `json:"permission_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzGroupMembership struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	UserGroupID        string             `json:"user_group_id"`
	AccountID          string             `json:"account_id"`
	ValidFrom          pgtype.Timestamptz `json:"valid_from"`
	ValidUntil         pgtype.Timestamptz `json:"valid_until"`
	Source             string             `json:"source"`
	ApprovalInstanceID string             `json:"approval_instance_id"`
	CreatedBy          string             `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type AuthzPermissionSetAssignment struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	PrincipalType   string             `json:"principal_type"`
	PrincipalID     string             `json:"principal_id"`
	PermissionSetID string             `json:"permission_set_id"`
	Effect          string             `json:"effect"`
	DataScopeID     string             `json:"data_scope_id"`
	ConditionID     string             `json:"condition_id"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzPermissionVersion struct {
	TenantID  string             `json:"tenant_id"`
	Version   int64              `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuthzRelationshipTuple struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	ObjectType  string             `json:"object_type"`
	ObjectID    string             `json:"object_id"`
	Relation    string             `json:"relation"`
	SubjectType string             `json:"subject_type"`
	SubjectID   string             `json:"subject_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Employee struct {
	ID                    string             `json:"id"`
	TenantID              string             `json:"tenant_id"`
	EmployeeNo            string             `json:"employee_no"`
	Name                  string             `json:"name"`
	CompanyEmail          string             `json:"company_email"`
	PersonalEmail         string             `json:"personal_email"`
	Phone                 string             `json:"phone"`
	OrgUnitID             string             `json:"org_unit_id"`
	AccountID             string             `json:"account_id"`
	ManagerEmployeeID     pgtype.Text        `json:"manager_employee_id"`
	PositionID            string             `json:"position_id"`
	Position              string             `json:"position"`
	Category              string             `json:"category"`
	Status                string             `json:"status"`
	EmploymentStatus      string             `json:"employment_status"`
	ShowInOrgChart        bool               `json:"show_in_org_chart"`
	HireDate              pgtype.Timestamptz `json:"hire_date"`
	ResignDate            pgtype.Timestamptz `json:"resign_date"`
	BasicInfo             []byte             `json:"basic_info"`
	EmploymentInfo        []byte             `json:"employment_info"`
	EducationMilitaryInfo []byte             `json:"education_military_info"`
	ContactInfo           []byte             `json:"contact_info"`
	InsuranceInfo         []byte             `json:"insurance_info"`
	InternalExperiences   []byte             `json:"internal_experiences"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeImportSession struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	Filename             string             `json:"filename"`
	ObjectProvider       string             `json:"object_provider"`
	ObjectBucket         string             `json:"object_bucket"`
	ObjectKey            string             `json:"object_key"`
	ContentType          string             `json:"content_type"`
	SizeBytes            int64              `json:"size_bytes"`
	Sha256               string             `json:"sha256"`
	Status               string             `json:"status"`
	Rows                 []byte             `json:"rows"`
	Summary              []byte             `json:"summary"`
	CreatedByAccountID   string             `json:"created_by_account_id"`
	ConfirmedByAccountID string             `json:"confirmed_by_account_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	ConfirmedAt          pgtype.Timestamptz `json:"confirmed_at"`
}

type EmployeeNumberSequence struct {
	TenantID  string             `json:"tenant_id"`
	Prefix    string             `json:"prefix"`
	NextValue int32              `json:"next_value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type EmploymentContract struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	EmployeeID          string             `json:"employee_id"`
	ContractType        string             `json:"contract_type"`
	ContractNo          string             `json:"contract_no"`
	StartDate           pgtype.Timestamptz `json:"start_date"`
	EndDate             pgtype.Timestamptz `json:"end_date"`
	Status              string             `json:"status"`
	AttachmentObjectKey string             `json:"attachment_object_key"`
	Notes               string             `json:"notes"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type FileAsset struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	CreatedByAccountID string             `json:"created_by_account_id"`
	OriginalFilename   string             `json:"original_filename"`
	ObjectProvider     string             `json:"object_provider"`
	ObjectBucket       string             `json:"object_bucket"`
	ObjectKey          string             `json:"object_key"`
	ContentType        string             `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	Sha256             string             `json:"sha256"`
	ScanStatus         string             `json:"scan_status"`
	ParseStatus        string             `json:"parse_status"`
	RetentionClass     string             `json:"retention_class"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type FileChunk struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	FileID    string             `json:"file_id"`
	Ordinal   int32              `json:"ordinal"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FormDefinitionDraft struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	OwnerAccountID      string             `json:"owner_account_id"`
	BaseTemplateID      string             `json:"base_template_id"`
	SchemaVersion       int32              `json:"schema_version"`
	AuthoringSchema     []byte             `json:"authoring_schema"`
	CompiledSchema      []byte             `json:"compiled_schema"`
	Status              string             `json:"status"`
	Revision            int64              `json:"revision"`
	Source              string             `json:"source"`
	AgentID             string             `json:"agent_id"`
	AgentRunID          string             `json:"agent_run_id"`
	AgentSessionID      string             `json:"agent_session_id"`
	ToolCallID          string             `json:"tool_call_id"`
	ValidationResult    []byte             `json:"validation_result"`
	SubmittedAt         pgtype.Timestamptz `json:"submitted_at"`
	PublishedTemplateID string             `json:"published_template_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type FormInstance struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	TemplateID         string             `json:"template_id"`
	TemplateVersionID  string             `json:"template_version_id"`
	ApplicantAccountID string             `json:"applicant_account_id"`
	Status             string             `json:"status"`
	Payload            []byte             `json:"payload"`
	SubmittedAt        pgtype.Timestamptz `json:"submitted_at"`
	ApprovedBy         string             `json:"approved_by"`
	CurrentRunID       string             `json:"current_run_id"`
	Version            int64              `json:"version"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type FormInstanceFieldValue struct {
	TenantID          string             `json:"tenant_id"`
	FormInstanceID    string             `json:"form_instance_id"`
	TemplateID        string             `json:"template_id"`
	TemplateVersionID string             `json:"template_version_id"`
	FieldID           string             `json:"field_id"`
	ValueType         string             `json:"value_type"`
	ValueText         pgtype.Text        `json:"value_text"`
	ValueNumber       pgtype.Numeric     `json:"value_number"`
	ValueBoolean      pgtype.Bool        `json:"value_boolean"`
	ValueDate         pgtype.Date        `json:"value_date"`
	ValueTimestamp    pgtype.Timestamptz `json:"value_timestamp"`
	ValueJson         []byte             `json:"value_json"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type FormTemplate struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	Key            string             `json:"key"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	Schema         []byte             `json:"schema"`
	Status         string             `json:"status"`
	CurrentVersion int32              `json:"current_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type FormTemplateVersion struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	TemplateID  string             `json:"template_id"`
	Version     int32              `json:"version"`
	Schema      []byte             `json:"schema"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type IdentityProvisioningOutbox struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	EmployeeID     string             `json:"employee_id"`
	EmployeeNo     string             `json:"employee_no"`
	Email          string             `json:"email"`
	DisplayName    string             `json:"display_name"`
	Enabled        bool               `json:"enabled"`
	SendInvite     bool               `json:"send_invite"`
	Status         string             `json:"status"`
	RetryCount     int32              `json:"retry_count"`
	LastError      string             `json:"last_error"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	ClaimExpiresAt pgtype.Timestamptz `json:"claim_expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type KnowledgeBasis struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	ChunkMode          string             `json:"chunk_mode"`
	ChunkSize          int32              `json:"chunk_size"`
	ChunkOverlap       int32              `json:"chunk_overlap"`
	CreatedByAccountID pgtype.Text        `json:"created_by_account_id"`
	UpdatedByAccountID pgtype.Text        `json:"updated_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type KnowledgeDocument struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	KnowledgeBaseID    string             `json:"knowledge_base_id"`
	Title              string             `json:"title"`
	Content            string             `json:"content"`
	SourceType         string             `json:"source_type"`
	OriginalFilename   string             `json:"original_filename"`
	ContentType        string             `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	Sha256             string             `json:"sha256"`
	ObjectProvider     string             `json:"object_provider"`
	ObjectBucket       string             `json:"object_bucket"`
	ObjectKey          string             `json:"object_key"`
	ParseStatus        string             `json:"parse_status"`
	ParseError         string             `json:"parse_error"`
	CreatedByAccountID pgtype.Text        `json:"created_by_account_id"`
	UpdatedByAccountID pgtype.Text        `json:"updated_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type KnowledgeDocumentChunk struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	KnowledgeBaseID     string             `json:"knowledge_base_id"`
	DocumentID          string             `json:"document_id"`
	Ordinal             int32              `json:"ordinal"`
	Content             string             `json:"content"`
	EmbeddingModel      string             `json:"embedding_model"`
	EmbeddingDimensions int32              `json:"embedding_dimensions"`
	Embedding           pgvector.Vector    `json:"embedding"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type LeaveBalance struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	EmployeeID     string             `json:"employee_id"`
	LeaveType      string             `json:"leave_type"`
	LeaveTypeID    string             `json:"leave_type_id"`
	RemainingHours pgtype.Numeric     `json:"remaining_hours"`
	PeriodStart    pgtype.Date        `json:"period_start"`
	PeriodEnd      pgtype.Date        `json:"period_end"`
	GrantedHours   pgtype.Numeric     `json:"granted_hours"`
	UsedHours      pgtype.Numeric     `json:"used_hours"`
	Source         string             `json:"source"`
	PolicyVersion  int32              `json:"policy_version"`
	ProrateRatio   pgtype.Float8      `json:"prorate_ratio"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type LeaveBalanceLedger struct {
	ID             int64              `json:"id"`
	TenantID       string             `json:"tenant_id"`
	BalanceID      string             `json:"balance_id"`
	EmployeeID     string             `json:"employee_id"`
	LeaveType      string             `json:"leave_type"`
	PeriodStart    pgtype.Date        `json:"period_start"`
	PeriodEnd      pgtype.Date        `json:"period_end"`
	EventType      string             `json:"event_type"`
	DeltaHours     pgtype.Numeric     `json:"delta_hours"`
	RemainingHours pgtype.Numeric     `json:"remaining_hours"`
	GrantedHours   pgtype.Numeric     `json:"granted_hours"`
	UsedHours      pgtype.Numeric     `json:"used_hours"`
	Source         string             `json:"source"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

type LeaveRequest struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	EmployeeID         string             `json:"employee_id"`
	LeaveType          string             `json:"leave_type"`
	LeaveTypeID        string             `json:"leave_type_id"`
	PolicyVersion      int32              `json:"policy_version"`
	RuleSnapshot       []byte             `json:"rule_snapshot"`
	EvaluationSnapshot []byte             `json:"evaluation_snapshot"`
	StartAt            pgtype.Timestamptz `json:"start_at"`
	EndAt              pgtype.Timestamptz `json:"end_at"`
	Hours              float64            `json:"hours"`
	Reason             string             `json:"reason"`
	Status             string             `json:"status"`
	FormInstanceID     string             `json:"form_instance_id"`
	LeaveBalanceID     pgtype.Text        `json:"leave_balance_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type LeaveRequestAllocation struct {
	ID             int64              `json:"id"`
	TenantID       string             `json:"tenant_id"`
	LeaveRequestID string             `json:"leave_request_id"`
	LeaveBalanceID string             `json:"leave_balance_id"`
	ReservedHours  pgtype.Numeric     `json:"reserved_hours"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type LeaveType struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Category      string             `json:"category"`
	SourceOfTruth string             `json:"source_of_truth"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type LeaveTypeExternalMapping struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	Source        string             `json:"source"`
	ExternalCode  string             `json:"external_code"`
	LeaveTypeID   string             `json:"leave_type_id"`
	EffectiveFrom pgtype.Date        `json:"effective_from"`
	EffectiveTo   pgtype.Date        `json:"effective_to"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type LeaveTypeSyncIssue struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	Source       string             `json:"source"`
	ExternalCode string             `json:"external_code"`
	IssueCode    string             `json:"issue_code"`
	Message      string             `json:"message"`
	Occurrences  int32              `json:"occurrences"`
	Status       string             `json:"status"`
	FirstSeenAt  pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
}

type MenuItem struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Key       string             `json:"key"`
	Label     string             `json:"label"`
	Path      string             `json:"path"`
	Icon      string             `json:"icon"`
	ParentKey string             `json:"parent_key"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	Tone               string             `json:"tone"`
	Category           string             `json:"category"`
	Title              string             `json:"title"`
	Body               string             `json:"body"`
	StatusText         string             `json:"status_text"`
	LinkUrl            string             `json:"link_url"`
	SourceType         string             `json:"source_type"`
	SourceID           string             `json:"source_id"`
	CreatedByAccountID pgtype.Text        `json:"created_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

type NotificationRecipient struct {
	NotificationID string             `json:"notification_id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OrgUnit struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	NameEn         string             `json:"name_en"`
	ParentID       string             `json:"parent_id"`
	Path           []string           `json:"path"`
	Source         string             `json:"source"`
	Closed         bool               `json:"closed"`
	ShowInOrgChart bool               `json:"show_in_org_chart"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	LastError     string             `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
}

type OvertimeRequest struct {
	ID               string             `json:"id"`
	TenantID         string             `json:"tenant_id"`
	EmployeeID       string             `json:"employee_id"`
	WorkDate         string             `json:"work_date"`
	StartAt          pgtype.Timestamptz `json:"start_at"`
	EndAt            pgtype.Timestamptz `json:"end_at"`
	Hours            float64            `json:"hours"`
	OvertimeType     string             `json:"overtime_type"`
	CompensationType string             `json:"compensation_type"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	FormInstanceID   string             `json:"form_instance_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	Application    string             `json:"application"`
	Resource       string             `json:"resource"`
	Action         string             `json:"action"`
	PermissionType string             `json:"permission_type"`
	MenuKey        string             `json:"menu_key"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	HighRisk       bool               `json:"high_risk"`
	Severity       string             `json:"severity"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PermissionPackage struct {
	ID              string             `json:"id"`
	ApplicationCode string             `json:"application_code"`
	Version         string             `json:"version"`
	Status          string             `json:"status"`
	Content         []byte             `json:"content"`
	Checksum        string             `json:"checksum"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

type PermissionPackageImport struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	PackageID     string             `json:"package_id"`
	Version       string             `json:"version"`
	ImportedAt    pgtype.Timestamptz `json:"imported_at"`
	ImportedBy    string             `json:"imported_by"`
	ArtifactIDMap []byte             `json:"artifact_id_map"`
}

type PermissionSet struct {
	ID          string `json:"id"`
	TenantID    string `json:"tenant_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	// Authoring source for the permission set contract; service transactions rebuild permission_set_items after each write.
	Permissions          []byte             `json:"permissions"`
	SourceTemplateKey    string             `json:"source_template_key"`
	SourcePackageVersion string             `json:"source_package_version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

// Normalized query projection derived from permission_sets.permissions; do not write independently from application flows.
type PermissionSetItem struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	PermissionSetID string             `json:"permission_set_id"`
	PermissionID    string             `json:"permission_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PermissionSetTemplate struct {
	ID          string `json:"id"`
	PackageID   string `json:"package_id"`
	TemplateKey string `json:"template_key"`
	Name        string `json:"name"`
	Content     []byte `json:"content"`
	Version     string `json:"version"`
}

type PlatformTaskItem struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	AccountID string             `json:"account_id"`
	WorkDate  string             `json:"work_date"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Product   string             `json:"product"`
	Hours     float64            `json:"hours"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlatformTaskTodo struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	AccountID           string             `json:"account_id"`
	Text                string             `json:"text"`
	DueDate             string             `json:"due_date"`
	Status              string             `json:"status"`
	ConvertedTaskItemID string             `json:"converted_task_item_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Position struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	NameEn      string             `json:"name_en"`
	Level       string             `json:"level"`
	Status      string             `json:"status"`
	Description string             `json:"description"`
	Source      string             `json:"source"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserGroup struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	Name                 string             `json:"name"`
	Description          string             `json:"description"`
	MemberAccountIds     []string           `json:"member_account_ids"`
	PermissionSetIds     []string           `json:"permission_set_ids"`
	SourceTemplateKey    string             `json:"source_template_key"`
	SourcePackageVersion string             `json:"source_package_version"`
	Version              int64              `json:"version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type UserGroupTemplate struct {
	ID          string `json:"id"`
	PackageID   string `json:"package_id"`
	TemplateKey string `json:"template_key"`
	Name        string `json:"name"`
	Content     []byte `json:"content"`
	Version     string `json:"version"`
}

type UserIdentity struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	AccountID string             `json:"account_id"`
	Provider  string             `json:"provider"`
	Subject   string             `json:"subject"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkflowAction struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	RunID           string             `json:"run_id"`
	StageInstanceID string             `json:"stage_instance_id"`
	AccountID       string             `json:"account_id"`
	Action          string             `json:"action"`
	Comment         string             `json:"comment"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type WorkflowRun struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	FormInstanceID         string             `json:"form_instance_id"`
	TemplateID             string             `json:"template_id"`
	Version                int32              `json:"version"`
	Status                 string             `json:"status"`
	CurrentStageInstanceID pgtype.Text        `json:"current_stage_instance_id"`
	StageDefinitionsJson   []byte             `json:"stage_definitions_json"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowStageAssignee struct {
	TenantID        string `json:"tenant_id"`
	StageInstanceID string `json:"stage_instance_id"`
	AccountID       string `json:"account_id"`
	Status          string `json:"status"`
}

type WorkflowStageInstance struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	RunID       string             `json:"run_id"`
	StageID     string             `json:"stage_id"`
	StageType   string             `json:"stage_type"`
	Label       string             `json:"label"`
	Status      string             `json:"status"`
	Sequence    int32              `json:"sequence"`
	Result      []byte             `json:"result"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}
