// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	DisplayName            string             `json:"display_name"`
	Email                  string             `json:"email"`
	EmployeeID             string             `json:"employee_id"`
	Status                 string             `json:"status"`
	UserGroupIds           []string           `json:"user_group_ids"`
	DirectPermissionSetIds []string           `json:"direct_permission_set_ids"`
	ActiveAssumableRoleID  string             `json:"active_assumable_role_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type Agent struct {
	ID                 pgtype.UUID        `json:"id"`
	CompanyID          int32              `json:"company_id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Name               string             `json:"name"`
	AgentImage         string             `json:"agent_image"`
	AgentType          string             `json:"agent_type"`
	Opening            []byte             `json:"opening"`
	SuggestedQuestions []byte             `json:"suggested_questions"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AgentKnowledge struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   int32              `json:"company_id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	KnowledgeID pgtype.UUID        `json:"knowledge_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AgentPlatformFile struct {
	ID             pgtype.UUID        `json:"id"`
	CompanyID      int32              `json:"company_id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	FileID         pgtype.UUID        `json:"file_id"`
	Platform       string             `json:"platform"`
	PlatformFileID string             `json:"platform_file_id"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AgentRun struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	Mode           string             `json:"mode"`
	Prompt         string             `json:"prompt"`
	Answer         string             `json:"answer"`
	Status         string             `json:"status"`
	ReferenceItems []byte             `json:"reference_items"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AssumableRole struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	PermissionSetIds       []string           `json:"permission_set_ids"`
	Trusted                bool               `json:"trusted"`
	TrustPolicy            []byte             `json:"trust_policy"`
	PermissionBoundary     []byte             `json:"permission_boundary"`
	SessionDurationSeconds int32              `json:"session_duration_seconds"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	ActorAccountID string             `json:"actor_account_id"`
	Action         string             `json:"action"`
	Resource       string             `json:"resource"`
	Target         string             `json:"target"`
	Result         string             `json:"result"`
	TraceID        string             `json:"trace_id"`
	Severity       string             `json:"severity"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuthzApplication struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuthzAssumableRoleSession struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	AssumableRoleID string             `json:"assumable_role_id"`
	SessionPolicy   []byte             `json:"session_policy"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzDataScope struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	ScopeType string             `json:"scope_type"`
	Params    []byte             `json:"params"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthzFieldPolicy struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	ApplicationCode string             `json:"application_code"`
	ResourceType    string             `json:"resource_type"`
	FieldName       string             `json:"field_name"`
	Effect          string             `json:"effect"`
	MaskStrategy    string             `json:"mask_strategy"`
	PermissionID    string             `json:"permission_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzGroupMembership struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	GroupID   string             `json:"group_id"`
	AccountID string             `json:"account_id"`
	Source    string             `json:"source"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthzOutboxEvent struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	LastError   string             `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type AuthzPermission struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	ApplicationCode string             `json:"application_code"`
	ResourceType    string             `json:"resource_type"`
	Action          string             `json:"action"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	RiskLevel       string             `json:"risk_level"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzPermissionSetAssignment struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	PrincipalType   string             `json:"principal_type"`
	PrincipalID     string             `json:"principal_id"`
	PermissionSetID string             `json:"permission_set_id"`
	Effect          string             `json:"effect"`
	DataScopeID     string             `json:"data_scope_id"`
	ConditionID     string             `json:"condition_id"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzPermissionSetPermission struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	PermissionSetID string             `json:"permission_set_id"`
	PermissionID    string             `json:"permission_id"`
	Effect          string             `json:"effect"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzPermissionVersion struct {
	TenantID  string             `json:"tenant_id"`
	Version   int64              `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuthzPolicyCondition struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	Name       string             `json:"name"`
	Expression []byte             `json:"expression"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthzRelationshipTuple struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	ObjectType  string             `json:"object_type"`
	ObjectID    string             `json:"object_id"`
	Relation    string             `json:"relation"`
	SubjectType string             `json:"subject_type"`
	SubjectID   string             `json:"subject_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Company struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CompanyPlan struct {
	ID            pgtype.UUID        `json:"id"`
	CompanyID     int32              `json:"company_id"`
	PricingPlanID pgtype.UUID        `json:"pricing_plan_id"`
	Status        string             `json:"status"`
	QuotaSnapshot []byte             `json:"quota_snapshot"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CompanyStorageConfig struct {
	ID        pgtype.UUID        `json:"id"`
	CompanyID int32              `json:"company_id"`
	Provider  string             `json:"provider"`
	Bucket    string             `json:"bucket"`
	BasePath  string             `json:"base_path"`
	Config    []byte             `json:"config"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Employee struct {
	ID                    string             `json:"id"`
	TenantID              string             `json:"tenant_id"`
	EmployeeNo            string             `json:"employee_no"`
	Name                  string             `json:"name"`
	CompanyEmail          string             `json:"company_email"`
	PersonalEmail         string             `json:"personal_email"`
	Phone                 string             `json:"phone"`
	OrgUnitID             string             `json:"org_unit_id"`
	AccountID             string             `json:"account_id"`
	ManagerEmployeeID     pgtype.Text        `json:"manager_employee_id"`
	Position              string             `json:"position"`
	Category              string             `json:"category"`
	Status                string             `json:"status"`
	EmploymentStatus      string             `json:"employment_status"`
	HireDate              pgtype.Timestamptz `json:"hire_date"`
	ResignDate            pgtype.Timestamptz `json:"resign_date"`
	BasicInfo             []byte             `json:"basic_info"`
	EmploymentInfo        []byte             `json:"employment_info"`
	EducationMilitaryInfo []byte             `json:"education_military_info"`
	ContactInfo           []byte             `json:"contact_info"`
	InsuranceInfo         []byte             `json:"insurance_info"`
	InternalExperiences   []byte             `json:"internal_experiences"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeImportSession struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Filename    string             `json:"filename"`
	ObjectKey   string             `json:"object_key"`
	Status      string             `json:"status"`
	Rows        []byte             `json:"rows"`
	Summary     []byte             `json:"summary"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
}

type EmployeeNumberSequence struct {
	TenantID  string             `json:"tenant_id"`
	Prefix    string             `json:"prefix"`
	NextValue int32              `json:"next_value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type File struct {
	ID              pgtype.UUID        `json:"id"`
	CompanyID       int32              `json:"company_id"`
	KnowledgeID     pgtype.UUID        `json:"knowledge_id"`
	StorageConfigID pgtype.UUID        `json:"storage_config_id"`
	FileName        string             `json:"file_name"`
	MimeType        string             `json:"mime_type"`
	SizeBytes       int64              `json:"size_bytes"`
	StoragePath     string             `json:"storage_path"`
	Checksum        string             `json:"checksum"`
	Status          string             `json:"status"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type FileProcessTask struct {
	ID           pgtype.UUID        `json:"id"`
	CompanyID    int32              `json:"company_id"`
	FileID       pgtype.UUID        `json:"file_id"`
	TaskType     string             `json:"task_type"`
	Status       string             `json:"status"`
	QueueName    string             `json:"queue_name"`
	Payload      []byte             `json:"payload"`
	Result       []byte             `json:"result"`
	ErrorMessage string             `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type FormInstance struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	TemplateID         string             `json:"template_id"`
	ApplicantAccountID string             `json:"applicant_account_id"`
	Status             string             `json:"status"`
	Payload            []byte             `json:"payload"`
	SubmittedAt        pgtype.Timestamptz `json:"submitted_at"`
	ApprovedBy         string             `json:"approved_by"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type FormTemplate struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Schema      []byte             `json:"schema"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Knowledge struct {
	ID                 pgtype.UUID        `json:"id"`
	CompanyID          int32              `json:"company_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	MilvusCollectionID string             `json:"milvus_collection_id"`
	Config             []byte             `json:"config"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type KnowledgeArticle struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type KnowledgeUserPermission struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   int32              `json:"company_id"`
	KnowledgeID pgtype.UUID        `json:"knowledge_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Permission  string             `json:"permission"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LeaveBalance struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	EmployeeID     string             `json:"employee_id"`
	LeaveType      string             `json:"leave_type"`
	RemainingHours float64            `json:"remaining_hours"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type LeaveRequest struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	EmployeeID     string             `json:"employee_id"`
	LeaveType      string             `json:"leave_type"`
	StartAt        pgtype.Timestamptz `json:"start_at"`
	EndAt          pgtype.Timestamptz `json:"end_at"`
	Hours          float64            `json:"hours"`
	Reason         string             `json:"reason"`
	Status         string             `json:"status"`
	FormInstanceID string             `json:"form_instance_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type License struct {
	ID            pgtype.UUID        `json:"id"`
	CompanyID     int32              `json:"company_id"`
	LicenseKey    string             `json:"license_key"`
	Status        string             `json:"status"`
	QuotaSnapshot []byte             `json:"quota_snapshot"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type OrgUnit struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	ParentID  string             `json:"parent_id"`
	Path      []string           `json:"path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PermissionSet struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Permissions []byte             `json:"permissions"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PricingPlan struct {
	ID                pgtype.UUID        `json:"id"`
	Code              string             `json:"code"`
	Name              string             `json:"name"`
	MessageLimit      int32              `json:"message_limit"`
	UserLimit         int32              `json:"user_limit"`
	StorageLimitBytes int64              `json:"storage_limit_bytes"`
	Features          []byte             `json:"features"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   int32              `json:"company_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Permissions []byte             `json:"permissions"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	CompanyID    int32              `json:"company_id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	IsSuperAdmin bool               `json:"is_super_admin"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserGroup struct {
	ID               string             `json:"id"`
	TenantID         string             `json:"tenant_id"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	MemberAccountIds []string           `json:"member_account_ids"`
	PermissionSetIds []string           `json:"permission_set_ids"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type UserIdentity struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	AccountID string             `json:"account_id"`
	Provider  string             `json:"provider"`
	Subject   string             `json:"subject"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	CompanyID int32              `json:"company_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceUser struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   int32              `json:"company_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RoleID      pgtype.UUID        `json:"role_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
