// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	DisplayName            string             `json:"display_name"`
	Email                  string             `json:"email"`
	EmployeeID             string             `json:"employee_id"`
	Status                 string             `json:"status"`
	UserGroupIds           []string           `json:"user_group_ids"`
	DirectPermissionSetIds []string           `json:"direct_permission_set_ids"`
	ActiveAssumableRoleID  string             `json:"active_assumable_role_id"`
	Version                int64              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type AgentRun struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	Mode           string             `json:"mode"`
	Prompt         string             `json:"prompt"`
	Answer         string             `json:"answer"`
	Status         string             `json:"status"`
	ReferenceItems []byte             `json:"reference_items"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AssumableRole struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	PermissionSetIds       []string           `json:"permission_set_ids"`
	Trusted                bool               `json:"trusted"`
	TrustPolicy            []byte             `json:"trust_policy"`
	PermissionBoundary     []byte             `json:"permission_boundary"`
	SessionDurationSeconds int32              `json:"session_duration_seconds"`
	SourceTemplateKey      string             `json:"source_template_key"`
	SourcePackageVersion   string             `json:"source_package_version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type AssumableRoleTemplate struct {
	ID          string `json:"id"`
	PackageID   string `json:"package_id"`
	TemplateKey string `json:"template_key"`
	Name        string `json:"name"`
	Content     []byte `json:"content"`
	Version     string `json:"version"`
}

type AttendanceClockRecord struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	EmployeeID          string             `json:"employee_id"`
	ShiftAssignmentID   string             `json:"shift_assignment_id"`
	ShiftID             string             `json:"shift_id"`
	WorksiteID          string             `json:"worksite_id"`
	WorkDate            string             `json:"work_date"`
	Direction           string             `json:"direction"`
	ClockedAt           pgtype.Timestamptz `json:"clocked_at"`
	Latitude            float64            `json:"latitude"`
	Longitude           float64            `json:"longitude"`
	AccuracyMeters      float64            `json:"accuracy_meters"`
	DistanceMeters      float64            `json:"distance_meters"`
	RecordStatus        string             `json:"record_status"`
	RejectionReason     string             `json:"rejection_reason"`
	Source              string             `json:"source"`
	DeviceID            string             `json:"device_id"`
	DeviceInfo          []byte             `json:"device_info"`
	CorrectionRequestID string             `json:"correction_request_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type AttendanceCorrectionRequest struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	EmployeeID          string             `json:"employee_id"`
	Direction           string             `json:"direction"`
	RequestedClockedAt  pgtype.Timestamptz `json:"requested_clocked_at"`
	WorkDate            string             `json:"work_date"`
	Reason              string             `json:"reason"`
	Status              string             `json:"status"`
	FormInstanceID      string             `json:"form_instance_id"`
	ClockRecordID       string             `json:"clock_record_id"`
	ReviewedByAccountID string             `json:"reviewed_by_account_id"`
	ReviewReason        string             `json:"review_reason"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceDailySummary struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	EmployeeID  string             `json:"employee_id"`
	WorkDate    string             `json:"work_date"`
	ShiftStart  string             `json:"shift_start"`
	ShiftEnd    string             `json:"shift_end"`
	ShiftHours  float64            `json:"shift_hours"`
	DailyHours  float64            `json:"daily_hours"`
	ClockHours  float64            `json:"clock_hours"`
	Source      string             `json:"source"`
	ExternalRef string             `json:"external_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AttendancePolicy struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	WorkTime           []byte             `json:"work_time"`
	LeaveTypes         []byte             `json:"leave_types"`
	UpdatedByAccountID string             `json:"updated_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceShift struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	Name                   string             `json:"name"`
	ClockInStart           string             `json:"clock_in_start"`
	ClockInEnd             string             `json:"clock_in_end"`
	ClockOutStart          string             `json:"clock_out_start"`
	ClockOutEnd            string             `json:"clock_out_end"`
	LateGraceMinutes       int32              `json:"late_grace_minutes"`
	EarlyLeaveGraceMinutes int32              `json:"early_leave_grace_minutes"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceShiftAssignment struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	EmployeeID    string             `json:"employee_id"`
	ShiftID       string             `json:"shift_id"`
	WorksiteID    string             `json:"worksite_id"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceWorksite struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	Name         string             `json:"name"`
	Address      string             `json:"address"`
	Latitude     float64            `json:"latitude"`
	Longitude    float64            `json:"longitude"`
	RadiusMeters int32              `json:"radius_meters"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	ActorAccountID string             `json:"actor_account_id"`
	Action         string             `json:"action"`
	Resource       string             `json:"resource"`
	Target         string             `json:"target"`
	Result         string             `json:"result"`
	TraceID        string             `json:"trace_id"`
	Severity       string             `json:"severity"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuthzAssumableRoleSession struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	AssumableRoleID string             `json:"assumable_role_id"`
	SessionPolicy   []byte             `json:"session_policy"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzDataScope struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	ScopeType string             `json:"scope_type"`
	Params    []byte             `json:"params"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthzFieldPolicy struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	ApplicationCode string             `json:"application_code"`
	ResourceType    string             `json:"resource_type"`
	FieldName       string             `json:"field_name"`
	Effect          string             `json:"effect"`
	MaskStrategy    string             `json:"mask_strategy"`
	PermissionID    string             `json:"permission_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzGroupMembership struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	UserGroupID        string             `json:"user_group_id"`
	AccountID          string             `json:"account_id"`
	ValidFrom          pgtype.Timestamptz `json:"valid_from"`
	ValidUntil         pgtype.Timestamptz `json:"valid_until"`
	Source             string             `json:"source"`
	ApprovalInstanceID string             `json:"approval_instance_id"`
	CreatedBy          string             `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type AuthzPermissionSetAssignment struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	PrincipalType   string             `json:"principal_type"`
	PrincipalID     string             `json:"principal_id"`
	PermissionSetID string             `json:"permission_set_id"`
	Effect          string             `json:"effect"`
	DataScopeID     string             `json:"data_scope_id"`
	ConditionID     string             `json:"condition_id"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuthzPermissionVersion struct {
	TenantID  string             `json:"tenant_id"`
	Version   int64              `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuthzRelationshipTuple struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	ObjectType  string             `json:"object_type"`
	ObjectID    string             `json:"object_id"`
	Relation    string             `json:"relation"`
	SubjectType string             `json:"subject_type"`
	SubjectID   string             `json:"subject_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Employee struct {
	ID                    string             `json:"id"`
	TenantID              string             `json:"tenant_id"`
	EmployeeNo            string             `json:"employee_no"`
	Name                  string             `json:"name"`
	CompanyEmail          string             `json:"company_email"`
	PersonalEmail         string             `json:"personal_email"`
	Phone                 string             `json:"phone"`
	OrgUnitID             string             `json:"org_unit_id"`
	AccountID             string             `json:"account_id"`
	ManagerEmployeeID     pgtype.Text        `json:"manager_employee_id"`
	PositionID            string             `json:"position_id"`
	Position              string             `json:"position"`
	Category              string             `json:"category"`
	Status                string             `json:"status"`
	EmploymentStatus      string             `json:"employment_status"`
	HireDate              pgtype.Timestamptz `json:"hire_date"`
	ResignDate            pgtype.Timestamptz `json:"resign_date"`
	BasicInfo             []byte             `json:"basic_info"`
	EmploymentInfo        []byte             `json:"employment_info"`
	EducationMilitaryInfo []byte             `json:"education_military_info"`
	ContactInfo           []byte             `json:"contact_info"`
	InsuranceInfo         []byte             `json:"insurance_info"`
	InternalExperiences   []byte             `json:"internal_experiences"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeImportSession struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	Filename             string             `json:"filename"`
	ObjectProvider       string             `json:"object_provider"`
	ObjectBucket         string             `json:"object_bucket"`
	ObjectKey            string             `json:"object_key"`
	ContentType          string             `json:"content_type"`
	SizeBytes            int64              `json:"size_bytes"`
	Sha256               string             `json:"sha256"`
	Status               string             `json:"status"`
	Rows                 []byte             `json:"rows"`
	Summary              []byte             `json:"summary"`
	CreatedByAccountID   string             `json:"created_by_account_id"`
	ConfirmedByAccountID string             `json:"confirmed_by_account_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	ConfirmedAt          pgtype.Timestamptz `json:"confirmed_at"`
}

type EmployeeNumberSequence struct {
	TenantID  string             `json:"tenant_id"`
	Prefix    string             `json:"prefix"`
	NextValue int32              `json:"next_value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type EmploymentContract struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	EmployeeID          string             `json:"employee_id"`
	ContractType        string             `json:"contract_type"`
	ContractNo          string             `json:"contract_no"`
	StartDate           pgtype.Timestamptz `json:"start_date"`
	EndDate             pgtype.Timestamptz `json:"end_date"`
	Status              string             `json:"status"`
	AttachmentObjectKey string             `json:"attachment_object_key"`
	Notes               string             `json:"notes"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type FormInstance struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	TemplateID         string             `json:"template_id"`
	ApplicantAccountID string             `json:"applicant_account_id"`
	Status             string             `json:"status"`
	Payload            []byte             `json:"payload"`
	SubmittedAt        pgtype.Timestamptz `json:"submitted_at"`
	ApprovedBy         string             `json:"approved_by"`
	CurrentRunID       string             `json:"current_run_id"`
	Version            int64              `json:"version"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type FormTemplate struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Schema      []byte             `json:"schema"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type IdentityProvisioningOutbox struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	AccountID   string             `json:"account_id"`
	EmployeeID  string             `json:"employee_id"`
	EmployeeNo  string             `json:"employee_no"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Enabled     bool               `json:"enabled"`
	SendInvite  bool               `json:"send_invite"`
	Status      string             `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	LastError   string             `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type LeaveBalance struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	EmployeeID     string             `json:"employee_id"`
	LeaveType      string             `json:"leave_type"`
	RemainingHours float64            `json:"remaining_hours"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type LeaveRequest struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	EmployeeID     string             `json:"employee_id"`
	LeaveType      string             `json:"leave_type"`
	StartAt        pgtype.Timestamptz `json:"start_at"`
	EndAt          pgtype.Timestamptz `json:"end_at"`
	Hours          float64            `json:"hours"`
	Reason         string             `json:"reason"`
	Status         string             `json:"status"`
	FormInstanceID string             `json:"form_instance_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MenuItem struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Key       string             `json:"key"`
	Label     string             `json:"label"`
	Path      string             `json:"path"`
	Icon      string             `json:"icon"`
	ParentKey string             `json:"parent_key"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	Tone               string             `json:"tone"`
	Category           string             `json:"category"`
	Title              string             `json:"title"`
	Body               string             `json:"body"`
	StatusText         string             `json:"status_text"`
	LinkUrl            string             `json:"link_url"`
	SourceType         string             `json:"source_type"`
	SourceID           string             `json:"source_id"`
	CreatedByAccountID pgtype.Text        `json:"created_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

type NotificationRecipient struct {
	NotificationID string             `json:"notification_id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OrgUnit struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	ParentID  string             `json:"parent_id"`
	Path      []string           `json:"path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	LastError     string             `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
}

type OvertimeRequest struct {
	ID               string             `json:"id"`
	TenantID         string             `json:"tenant_id"`
	EmployeeID       string             `json:"employee_id"`
	WorkDate         string             `json:"work_date"`
	StartAt          pgtype.Timestamptz `json:"start_at"`
	EndAt            pgtype.Timestamptz `json:"end_at"`
	Hours            float64            `json:"hours"`
	OvertimeType     string             `json:"overtime_type"`
	CompensationType string             `json:"compensation_type"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	FormInstanceID   string             `json:"form_instance_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	Application    string             `json:"application"`
	Resource       string             `json:"resource"`
	Action         string             `json:"action"`
	PermissionType string             `json:"permission_type"`
	MenuKey        string             `json:"menu_key"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	HighRisk       bool               `json:"high_risk"`
	Severity       string             `json:"severity"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PermissionPackage struct {
	ID              string             `json:"id"`
	ApplicationCode string             `json:"application_code"`
	Version         string             `json:"version"`
	Status          string             `json:"status"`
	Content         []byte             `json:"content"`
	Checksum        string             `json:"checksum"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

type PermissionPackageImport struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	PackageID     string             `json:"package_id"`
	Version       string             `json:"version"`
	ImportedAt    pgtype.Timestamptz `json:"imported_at"`
	ImportedBy    string             `json:"imported_by"`
	ArtifactIDMap []byte             `json:"artifact_id_map"`
}

type PermissionSet struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	Name                 string             `json:"name"`
	Description          string             `json:"description"`
	Permissions          []byte             `json:"permissions"`
	SourceTemplateKey    string             `json:"source_template_key"`
	SourcePackageVersion string             `json:"source_package_version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type PermissionSetItem struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	PermissionSetID string             `json:"permission_set_id"`
	PermissionID    string             `json:"permission_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PermissionSetTemplate struct {
	ID          string `json:"id"`
	PackageID   string `json:"package_id"`
	TemplateKey string `json:"template_key"`
	Name        string `json:"name"`
	Content     []byte `json:"content"`
	Version     string `json:"version"`
}

type PlatformTaskItem struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	AccountID string             `json:"account_id"`
	WorkDate  string             `json:"work_date"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Product   string             `json:"product"`
	Hours     float64            `json:"hours"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlatformTaskTodo struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	AccountID           string             `json:"account_id"`
	Text                string             `json:"text"`
	DueDate             string             `json:"due_date"`
	Status              string             `json:"status"`
	ConvertedTaskItemID string             `json:"converted_task_item_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Position struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	OrgUnitID   string             `json:"org_unit_id"`
	Level       string             `json:"level"`
	Status      string             `json:"status"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserGroup struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	Name                 string             `json:"name"`
	Description          string             `json:"description"`
	MemberAccountIds     []string           `json:"member_account_ids"`
	PermissionSetIds     []string           `json:"permission_set_ids"`
	SourceTemplateKey    string             `json:"source_template_key"`
	SourcePackageVersion string             `json:"source_package_version"`
	Version              int64              `json:"version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type UserGroupTemplate struct {
	ID          string `json:"id"`
	PackageID   string `json:"package_id"`
	TemplateKey string `json:"template_key"`
	Name        string `json:"name"`
	Content     []byte `json:"content"`
	Version     string `json:"version"`
}

type UserIdentity struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	AccountID string             `json:"account_id"`
	Provider  string             `json:"provider"`
	Subject   string             `json:"subject"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkflowAction struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	RunID           string             `json:"run_id"`
	StageInstanceID string             `json:"stage_instance_id"`
	AccountID       string             `json:"account_id"`
	Action          string             `json:"action"`
	Comment         string             `json:"comment"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type WorkflowRun struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	FormInstanceID         string             `json:"form_instance_id"`
	TemplateID             string             `json:"template_id"`
	Version                int32              `json:"version"`
	Status                 string             `json:"status"`
	CurrentStageInstanceID string             `json:"current_stage_instance_id"`
	StageDefinitionsJson   string             `json:"stage_definitions_json"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowStageAssignee struct {
	TenantID        string `json:"tenant_id"`
	StageInstanceID string `json:"stage_instance_id"`
	AccountID       string `json:"account_id"`
	Status          string `json:"status"`
}

type WorkflowStageInstance struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	RunID       string             `json:"run_id"`
	StageID     string             `json:"stage_id"`
	StageType   string             `json:"stage_type"`
	Label       string             `json:"label"`
	Status      string             `json:"status"`
	Sequence    int32              `json:"sequence"`
	Result      []byte             `json:"result"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}
