// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationTones = `-- name: CountNotificationTones :one
SELECT
    count(*)::int AS all_count,
    count(*) FILTER (WHERE n.tone = 'success')::int AS success_count,
    count(*) FILTER (WHERE n.tone = 'info')::int AS info_count,
    count(*) FILTER (WHERE n.tone = 'warning')::int AS warning_count
FROM notification_recipients nr
JOIN notifications n ON n.tenant_id = nr.tenant_id AND n.id = nr.notification_id
WHERE nr.tenant_id = $1
  AND nr.account_id = $2
  AND nr.deleted_at IS NULL
  AND (n.expires_at IS NULL OR n.expires_at > now())
`

type CountNotificationTonesParams struct {
	TenantID  string `json:"tenant_id"`
	AccountID string `json:"account_id"`
}

type CountNotificationTonesRow struct {
	AllCount     int32 `json:"all_count"`
	SuccessCount int32 `json:"success_count"`
	InfoCount    int32 `json:"info_count"`
	WarningCount int32 `json:"warning_count"`
}

func (q *Queries) CountNotificationTones(ctx context.Context, arg CountNotificationTonesParams) (CountNotificationTonesRow, error) {
	row := q.db.QueryRow(ctx, countNotificationTones, arg.TenantID, arg.AccountID)
	var i CountNotificationTonesRow
	err := row.Scan(
		&i.AllCount,
		&i.SuccessCount,
		&i.InfoCount,
		&i.WarningCount,
	)
	return i, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::int
FROM notification_recipients nr
JOIN notifications n ON n.tenant_id = nr.tenant_id AND n.id = nr.notification_id
WHERE nr.tenant_id = $1
  AND nr.account_id = $2
  AND nr.deleted_at IS NULL
  AND nr.read_at IS NULL
  AND (n.expires_at IS NULL OR n.expires_at > now())
`

type CountUnreadNotificationsParams struct {
	TenantID  string `json:"tenant_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.TenantID, arg.AccountID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listNotificationItems = `-- name: ListNotificationItems :many
SELECT
    n.id,
    n.tone,
    n.category,
    n.title,
    n.body,
    n.status_text,
    n.link_url,
    nr.read_at,
    n.created_at
FROM notification_recipients nr
JOIN notifications n ON n.tenant_id = nr.tenant_id AND n.id = nr.notification_id
WHERE nr.tenant_id = $1
  AND nr.account_id = $2
  AND nr.deleted_at IS NULL
  AND (n.expires_at IS NULL OR n.expires_at > now())
  AND ($3::text = '' OR n.tone = $3)
  AND (NOT $4::boolean OR nr.read_at IS NULL)
  AND (
    NOT $5::boolean
    OR n.created_at < $6::timestamptz
    OR (n.created_at = $6::timestamptz AND n.id < $7)
  )
ORDER BY n.created_at DESC, n.id DESC
LIMIT $8::int
`

type ListNotificationItemsParams struct {
	TenantID        string             `json:"tenant_id"`
	AccountID       string             `json:"account_id"`
	Tone            string             `json:"tone"`
	UnreadOnly      bool               `json:"unread_only"`
	HasCursor       bool               `json:"has_cursor"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	LimitCount      int32              `json:"limit_count"`
}

type ListNotificationItemsRow struct {
	ID         string             `json:"id"`
	Tone       string             `json:"tone"`
	Category   string             `json:"category"`
	Title      string             `json:"title"`
	Body       string             `json:"body"`
	StatusText string             `json:"status_text"`
	LinkUrl    string             `json:"link_url"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListNotificationItems(ctx context.Context, arg ListNotificationItemsParams) ([]ListNotificationItemsRow, error) {
	rows, err := q.db.Query(ctx, listNotificationItems,
		arg.TenantID,
		arg.AccountID,
		arg.Tone,
		arg.UnreadOnly,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationItemsRow
	for rows.Next() {
		var i ListNotificationItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Tone,
			&i.Category,
			&i.Title,
			&i.Body,
			&i.StatusText,
			&i.LinkUrl,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :one
WITH updated AS (
    UPDATE notification_recipients nr
    SET read_at = $1::timestamptz
    FROM notifications n
    WHERE n.tenant_id = nr.tenant_id
      AND n.id = nr.notification_id
      AND nr.tenant_id = $2
      AND nr.account_id = $3
      AND nr.deleted_at IS NULL
      AND nr.read_at IS NULL
      AND (n.expires_at IS NULL OR n.expires_at > now())
    RETURNING nr.notification_id
)
SELECT count(*)::int AS updated_count FROM updated
`

type MarkAllNotificationsReadParams struct {
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	TenantID  string             `json:"tenant_id"`
	AccountID string             `json:"account_id"`
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) (int32, error) {
	row := q.db.QueryRow(ctx, markAllNotificationsRead, arg.ReadAt, arg.TenantID, arg.AccountID)
	var updated_count int32
	err := row.Scan(&updated_count)
	return updated_count, err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
WITH updated AS (
    UPDATE notification_recipients nr
    SET read_at = COALESCE(nr.read_at, $1::timestamptz)
    WHERE nr.tenant_id = $2
      AND nr.account_id = $3
      AND nr.notification_id = $4
      AND nr.deleted_at IS NULL
    RETURNING notification_id, tenant_id, account_id, read_at
)
SELECT
    n.id,
    n.tone,
    n.category,
    n.title,
    n.body,
    n.status_text,
    n.link_url,
    updated.read_at,
    n.created_at
FROM updated
JOIN notifications n ON n.tenant_id = updated.tenant_id AND n.id = updated.notification_id
WHERE n.expires_at IS NULL OR n.expires_at > now()
`

type MarkNotificationReadParams struct {
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	NotificationID string             `json:"notification_id"`
}

type MarkNotificationReadRow struct {
	ID         string             `json:"id"`
	Tone       string             `json:"tone"`
	Category   string             `json:"category"`
	Title      string             `json:"title"`
	Body       string             `json:"body"`
	StatusText string             `json:"status_text"`
	LinkUrl    string             `json:"link_url"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (MarkNotificationReadRow, error) {
	row := q.db.QueryRow(ctx, markNotificationRead,
		arg.ReadAt,
		arg.TenantID,
		arg.AccountID,
		arg.NotificationID,
	)
	var i MarkNotificationReadRow
	err := row.Scan(
		&i.ID,
		&i.Tone,
		&i.Category,
		&i.Title,
		&i.Body,
		&i.StatusText,
		&i.LinkUrl,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertNotification = `-- name: UpsertNotification :one
INSERT INTO notifications (
    id, tenant_id, tone, category, title, body, status_text,
    link_url, source_type, source_id, created_by_account_id, created_at, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13
)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    tone = EXCLUDED.tone,
    category = EXCLUDED.category,
    title = EXCLUDED.title,
    body = EXCLUDED.body,
    status_text = EXCLUDED.status_text,
    link_url = EXCLUDED.link_url,
    source_type = EXCLUDED.source_type,
    source_id = EXCLUDED.source_id,
    created_by_account_id = EXCLUDED.created_by_account_id,
    created_at = EXCLUDED.created_at,
    expires_at = EXCLUDED.expires_at
RETURNING id, tenant_id, tone, category, title, body, status_text, link_url, source_type, source_id, created_by_account_id, created_at, expires_at
`

type UpsertNotificationParams struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	Tone               string             `json:"tone"`
	Category           string             `json:"category"`
	Title              string             `json:"title"`
	Body               string             `json:"body"`
	StatusText         string             `json:"status_text"`
	LinkUrl            string             `json:"link_url"`
	SourceType         string             `json:"source_type"`
	SourceID           string             `json:"source_id"`
	CreatedByAccountID pgtype.Text        `json:"created_by_account_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertNotification(ctx context.Context, arg UpsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, upsertNotification,
		arg.ID,
		arg.TenantID,
		arg.Tone,
		arg.Category,
		arg.Title,
		arg.Body,
		arg.StatusText,
		arg.LinkUrl,
		arg.SourceType,
		arg.SourceID,
		arg.CreatedByAccountID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Tone,
		&i.Category,
		&i.Title,
		&i.Body,
		&i.StatusText,
		&i.LinkUrl,
		&i.SourceType,
		&i.SourceID,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertNotificationRecipient = `-- name: UpsertNotificationRecipient :one
INSERT INTO notification_recipients (
    notification_id, tenant_id, account_id, read_at, deleted_at, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (notification_id, account_id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    read_at = EXCLUDED.read_at,
    deleted_at = EXCLUDED.deleted_at,
    created_at = EXCLUDED.created_at
RETURNING notification_id, tenant_id, account_id, read_at, deleted_at, created_at
`

type UpsertNotificationRecipientParams struct {
	NotificationID string             `json:"notification_id"`
	TenantID       string             `json:"tenant_id"`
	AccountID      string             `json:"account_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertNotificationRecipient(ctx context.Context, arg UpsertNotificationRecipientParams) (NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, upsertNotificationRecipient,
		arg.NotificationID,
		arg.TenantID,
		arg.AccountID,
		arg.ReadAt,
		arg.DeletedAt,
		arg.CreatedAt,
	)
	var i NotificationRecipient
	err := row.Scan(
		&i.NotificationID,
		&i.TenantID,
		&i.AccountID,
		&i.ReadAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}
