// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission_catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items
WHERE tenant_id = $1 AND id = $2
`

type DeleteMenuItemParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteMenuItem(ctx context.Context, arg DeleteMenuItemParams) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, arg.TenantID, arg.ID)
	return err
}

const deletePermissionCatalogItem = `-- name: DeletePermissionCatalogItem :exec
DELETE FROM permissions
WHERE tenant_id = $1 AND id = $2
`

type DeletePermissionCatalogItemParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeletePermissionCatalogItem(ctx context.Context, arg DeletePermissionCatalogItemParams) error {
	_, err := q.db.Exec(ctx, deletePermissionCatalogItem, arg.TenantID, arg.ID)
	return err
}

const deletePermissionSetItemsForSet = `-- name: DeletePermissionSetItemsForSet :exec
DELETE FROM permission_set_items
WHERE tenant_id = $1 AND permission_set_id = $2
`

type DeletePermissionSetItemsForSetParams struct {
	TenantID        string `json:"tenant_id"`
	PermissionSetID string `json:"permission_set_id"`
}

func (q *Queries) DeletePermissionSetItemsForSet(ctx context.Context, arg DeletePermissionSetItemsForSetParams) error {
	_, err := q.db.Exec(ctx, deletePermissionSetItemsForSet, arg.TenantID, arg.PermissionSetID)
	return err
}

const getPermissionCatalogItemByKey = `-- name: GetPermissionCatalogItemByKey :one
SELECT id, tenant_id, application, resource, action, permission_type, menu_key, name, description, high_risk, severity, created_at FROM permissions
WHERE tenant_id = $1
  AND application = $2
  AND resource = $3
  AND action = $4
  AND permission_type = $5
`

type GetPermissionCatalogItemByKeyParams struct {
	TenantID       string `json:"tenant_id"`
	Application    string `json:"application"`
	Resource       string `json:"resource"`
	Action         string `json:"action"`
	PermissionType string `json:"permission_type"`
}

func (q *Queries) GetPermissionCatalogItemByKey(ctx context.Context, arg GetPermissionCatalogItemByKeyParams) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionCatalogItemByKey,
		arg.TenantID,
		arg.Application,
		arg.Resource,
		arg.Action,
		arg.PermissionType,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Application,
		&i.Resource,
		&i.Action,
		&i.PermissionType,
		&i.MenuKey,
		&i.Name,
		&i.Description,
		&i.HighRisk,
		&i.Severity,
		&i.CreatedAt,
	)
	return i, err
}

const listMenuItems = `-- name: ListMenuItems :many
SELECT id, tenant_id, key, label, path, icon, parent_key, sort_order, created_at FROM menu_items
WHERE tenant_id = $1
ORDER BY parent_key ASC, sort_order ASC, key ASC
`

func (q *Queries) ListMenuItems(ctx context.Context, tenantID string) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItems, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Key,
			&i.Label,
			&i.Path,
			&i.Icon,
			&i.ParentKey,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionCatalogItems = `-- name: ListPermissionCatalogItems :many
SELECT id, tenant_id, application, resource, action, permission_type, menu_key, name, description, high_risk, severity, created_at FROM permissions
WHERE tenant_id = $1
ORDER BY application ASC, resource ASC, action ASC, permission_type ASC
`

func (q *Queries) ListPermissionCatalogItems(ctx context.Context, tenantID string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionCatalogItems, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Application,
			&i.Resource,
			&i.Action,
			&i.PermissionType,
			&i.MenuKey,
			&i.Name,
			&i.Description,
			&i.HighRisk,
			&i.Severity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionSetItems = `-- name: ListPermissionSetItems :many
SELECT id, tenant_id, permission_set_id, permission_id, created_at FROM permission_set_items
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPermissionSetItems(ctx context.Context, tenantID string) ([]PermissionSetItem, error) {
	rows, err := q.db.Query(ctx, listPermissionSetItems, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionSetItem
	for rows.Next() {
		var i PermissionSetItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PermissionSetID,
			&i.PermissionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionSetItemsForSet = `-- name: ListPermissionSetItemsForSet :many
SELECT id, tenant_id, permission_set_id, permission_id, created_at FROM permission_set_items
WHERE tenant_id = $1 AND permission_set_id = $2
ORDER BY created_at ASC
`

type ListPermissionSetItemsForSetParams struct {
	TenantID        string `json:"tenant_id"`
	PermissionSetID string `json:"permission_set_id"`
}

func (q *Queries) ListPermissionSetItemsForSet(ctx context.Context, arg ListPermissionSetItemsForSetParams) ([]PermissionSetItem, error) {
	rows, err := q.db.Query(ctx, listPermissionSetItemsForSet, arg.TenantID, arg.PermissionSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionSetItem
	for rows.Next() {
		var i PermissionSetItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PermissionSetID,
			&i.PermissionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMenuItem = `-- name: UpsertMenuItem :one
INSERT INTO menu_items (
    id, tenant_id, key, label, path, icon, parent_key, sort_order, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
ON CONFLICT (tenant_id, key) DO UPDATE SET
    label = EXCLUDED.label,
    path = EXCLUDED.path,
    icon = EXCLUDED.icon,
    parent_key = EXCLUDED.parent_key,
    sort_order = EXCLUDED.sort_order
RETURNING id, tenant_id, key, label, path, icon, parent_key, sort_order, created_at
`

type UpsertMenuItemParams struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Key       string             `json:"key"`
	Label     string             `json:"label"`
	Path      string             `json:"path"`
	Icon      string             `json:"icon"`
	ParentKey string             `json:"parent_key"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertMenuItem(ctx context.Context, arg UpsertMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, upsertMenuItem,
		arg.ID,
		arg.TenantID,
		arg.Key,
		arg.Label,
		arg.Path,
		arg.Icon,
		arg.ParentKey,
		arg.SortOrder,
		arg.CreatedAt,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Label,
		&i.Path,
		&i.Icon,
		&i.ParentKey,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPermissionCatalogItem = `-- name: UpsertPermissionCatalogItem :one
INSERT INTO permissions (
    id, tenant_id, application, resource, action, permission_type,
    menu_key, name, description, high_risk, severity, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
ON CONFLICT (tenant_id, application, resource, action, permission_type) DO UPDATE SET
    menu_key = EXCLUDED.menu_key,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    high_risk = EXCLUDED.high_risk,
    severity = EXCLUDED.severity
RETURNING id, tenant_id, application, resource, action, permission_type, menu_key, name, description, high_risk, severity, created_at
`

type UpsertPermissionCatalogItemParams struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	Application    string             `json:"application"`
	Resource       string             `json:"resource"`
	Action         string             `json:"action"`
	PermissionType string             `json:"permission_type"`
	MenuKey        string             `json:"menu_key"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	HighRisk       bool               `json:"high_risk"`
	Severity       string             `json:"severity"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertPermissionCatalogItem(ctx context.Context, arg UpsertPermissionCatalogItemParams) (Permission, error) {
	row := q.db.QueryRow(ctx, upsertPermissionCatalogItem,
		arg.ID,
		arg.TenantID,
		arg.Application,
		arg.Resource,
		arg.Action,
		arg.PermissionType,
		arg.MenuKey,
		arg.Name,
		arg.Description,
		arg.HighRisk,
		arg.Severity,
		arg.CreatedAt,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Application,
		&i.Resource,
		&i.Action,
		&i.PermissionType,
		&i.MenuKey,
		&i.Name,
		&i.Description,
		&i.HighRisk,
		&i.Severity,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPermissionSetItem = `-- name: UpsertPermissionSetItem :one
INSERT INTO permission_set_items (
    id, tenant_id, permission_set_id, permission_id, created_at
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (tenant_id, permission_set_id, permission_id) DO UPDATE SET
    created_at = permission_set_items.created_at
RETURNING id, tenant_id, permission_set_id, permission_id, created_at
`

type UpsertPermissionSetItemParams struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	PermissionSetID string             `json:"permission_set_id"`
	PermissionID    string             `json:"permission_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertPermissionSetItem(ctx context.Context, arg UpsertPermissionSetItemParams) (PermissionSetItem, error) {
	row := q.db.QueryRow(ctx, upsertPermissionSetItem,
		arg.ID,
		arg.TenantID,
		arg.PermissionSetID,
		arg.PermissionID,
		arg.CreatedAt,
	)
	var i PermissionSetItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PermissionSetID,
		&i.PermissionID,
		&i.CreatedAt,
	)
	return i, err
}
