// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission_packages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPermissionPackage = `-- name: GetPermissionPackage :one
SELECT id, application_code, version, status, content, checksum, created_at, published_at FROM permission_packages
WHERE id = $1
`

func (q *Queries) GetPermissionPackage(ctx context.Context, id string) (PermissionPackage, error) {
	row := q.db.QueryRow(ctx, getPermissionPackage, id)
	var i PermissionPackage
	err := row.Scan(
		&i.ID,
		&i.ApplicationCode,
		&i.Version,
		&i.Status,
		&i.Content,
		&i.Checksum,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getPermissionPackageByApplicationVersion = `-- name: GetPermissionPackageByApplicationVersion :one
SELECT id, application_code, version, status, content, checksum, created_at, published_at FROM permission_packages
WHERE application_code = $1 AND version = $2
`

type GetPermissionPackageByApplicationVersionParams struct {
	ApplicationCode string `json:"application_code"`
	Version         string `json:"version"`
}

func (q *Queries) GetPermissionPackageByApplicationVersion(ctx context.Context, arg GetPermissionPackageByApplicationVersionParams) (PermissionPackage, error) {
	row := q.db.QueryRow(ctx, getPermissionPackageByApplicationVersion, arg.ApplicationCode, arg.Version)
	var i PermissionPackage
	err := row.Scan(
		&i.ID,
		&i.ApplicationCode,
		&i.Version,
		&i.Status,
		&i.Content,
		&i.Checksum,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getPermissionPackageImport = `-- name: GetPermissionPackageImport :one
SELECT id, tenant_id, package_id, version, imported_at, imported_by, artifact_id_map FROM permission_package_imports
WHERE tenant_id = $1 AND package_id = $2 AND version = $3
`

type GetPermissionPackageImportParams struct {
	TenantID  string `json:"tenant_id"`
	PackageID string `json:"package_id"`
	Version   string `json:"version"`
}

func (q *Queries) GetPermissionPackageImport(ctx context.Context, arg GetPermissionPackageImportParams) (PermissionPackageImport, error) {
	row := q.db.QueryRow(ctx, getPermissionPackageImport, arg.TenantID, arg.PackageID, arg.Version)
	var i PermissionPackageImport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.Version,
		&i.ImportedAt,
		&i.ImportedBy,
		&i.ArtifactIDMap,
	)
	return i, err
}

const listAssumableRoleTemplates = `-- name: ListAssumableRoleTemplates :many
SELECT id, package_id, template_key, name, content, version FROM assumable_role_templates
WHERE package_id = $1
ORDER BY template_key ASC
`

func (q *Queries) ListAssumableRoleTemplates(ctx context.Context, packageID string) ([]AssumableRoleTemplate, error) {
	rows, err := q.db.Query(ctx, listAssumableRoleTemplates, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssumableRoleTemplate
	for rows.Next() {
		var i AssumableRoleTemplate
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.TemplateKey,
			&i.Name,
			&i.Content,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionPackageImports = `-- name: ListPermissionPackageImports :many
SELECT id, tenant_id, package_id, version, imported_at, imported_by, artifact_id_map FROM permission_package_imports
WHERE tenant_id = $1
ORDER BY imported_at ASC
`

func (q *Queries) ListPermissionPackageImports(ctx context.Context, tenantID string) ([]PermissionPackageImport, error) {
	rows, err := q.db.Query(ctx, listPermissionPackageImports, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionPackageImport
	for rows.Next() {
		var i PermissionPackageImport
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PackageID,
			&i.Version,
			&i.ImportedAt,
			&i.ImportedBy,
			&i.ArtifactIDMap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionPackages = `-- name: ListPermissionPackages :many
SELECT id, application_code, version, status, content, checksum, created_at, published_at FROM permission_packages
ORDER BY application_code ASC, version ASC
`

func (q *Queries) ListPermissionPackages(ctx context.Context) ([]PermissionPackage, error) {
	rows, err := q.db.Query(ctx, listPermissionPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionPackage
	for rows.Next() {
		var i PermissionPackage
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationCode,
			&i.Version,
			&i.Status,
			&i.Content,
			&i.Checksum,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionSetTemplates = `-- name: ListPermissionSetTemplates :many
SELECT id, package_id, template_key, name, content, version FROM permission_set_templates
WHERE package_id = $1
ORDER BY template_key ASC
`

func (q *Queries) ListPermissionSetTemplates(ctx context.Context, packageID string) ([]PermissionSetTemplate, error) {
	rows, err := q.db.Query(ctx, listPermissionSetTemplates, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionSetTemplate
	for rows.Next() {
		var i PermissionSetTemplate
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.TemplateKey,
			&i.Name,
			&i.Content,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroupTemplates = `-- name: ListUserGroupTemplates :many
SELECT id, package_id, template_key, name, content, version FROM user_group_templates
WHERE package_id = $1
ORDER BY template_key ASC
`

func (q *Queries) ListUserGroupTemplates(ctx context.Context, packageID string) ([]UserGroupTemplate, error) {
	rows, err := q.db.Query(ctx, listUserGroupTemplates, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroupTemplate
	for rows.Next() {
		var i UserGroupTemplate
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.TemplateKey,
			&i.Name,
			&i.Content,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermissionPackageStatus = `-- name: UpdatePermissionPackageStatus :one
UPDATE permission_packages
SET status = $2,
    published_at = $3
WHERE id = $1
RETURNING id, application_code, version, status, content, checksum, created_at, published_at
`

type UpdatePermissionPackageStatusParams struct {
	ID          string             `json:"id"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpdatePermissionPackageStatus(ctx context.Context, arg UpdatePermissionPackageStatusParams) (PermissionPackage, error) {
	row := q.db.QueryRow(ctx, updatePermissionPackageStatus, arg.ID, arg.Status, arg.PublishedAt)
	var i PermissionPackage
	err := row.Scan(
		&i.ID,
		&i.ApplicationCode,
		&i.Version,
		&i.Status,
		&i.Content,
		&i.Checksum,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const upsertAssumableRoleTemplate = `-- name: UpsertAssumableRoleTemplate :one
INSERT INTO assumable_role_templates (
    id, package_id, template_key, name, content, version
) VALUES (
    $1, $2, $3, $4, $5::jsonb, $6
)
ON CONFLICT (package_id, template_key) DO UPDATE SET
    name = EXCLUDED.name,
    content = EXCLUDED.content,
    version = EXCLUDED.version
RETURNING id, package_id, template_key, name, content, version
`

type UpsertAssumableRoleTemplateParams struct {
	ID          string `json:"id"`
	PackageID   string `json:"package_id"`
	TemplateKey string `json:"template_key"`
	Name        string `json:"name"`
	Content     []byte `json:"content"`
	Version     string `json:"version"`
}

func (q *Queries) UpsertAssumableRoleTemplate(ctx context.Context, arg UpsertAssumableRoleTemplateParams) (AssumableRoleTemplate, error) {
	row := q.db.QueryRow(ctx, upsertAssumableRoleTemplate,
		arg.ID,
		arg.PackageID,
		arg.TemplateKey,
		arg.Name,
		arg.Content,
		arg.Version,
	)
	var i AssumableRoleTemplate
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.TemplateKey,
		&i.Name,
		&i.Content,
		&i.Version,
	)
	return i, err
}

const upsertPermissionPackage = `-- name: UpsertPermissionPackage :one
INSERT INTO permission_packages (
    id, application_code, version, status, content, checksum, created_at, published_at
) VALUES (
    $1, $2, $3, $4,
    $5::jsonb, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE SET
    application_code = EXCLUDED.application_code,
    version = EXCLUDED.version,
    status = EXCLUDED.status,
    content = EXCLUDED.content,
    checksum = EXCLUDED.checksum,
    created_at = EXCLUDED.created_at,
    published_at = EXCLUDED.published_at
RETURNING id, application_code, version, status, content, checksum, created_at, published_at
`

type UpsertPermissionPackageParams struct {
	ID              string             `json:"id"`
	ApplicationCode string             `json:"application_code"`
	Version         string             `json:"version"`
	Status          string             `json:"status"`
	Content         []byte             `json:"content"`
	Checksum        string             `json:"checksum"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpsertPermissionPackage(ctx context.Context, arg UpsertPermissionPackageParams) (PermissionPackage, error) {
	row := q.db.QueryRow(ctx, upsertPermissionPackage,
		arg.ID,
		arg.ApplicationCode,
		arg.Version,
		arg.Status,
		arg.Content,
		arg.Checksum,
		arg.CreatedAt,
		arg.PublishedAt,
	)
	var i PermissionPackage
	err := row.Scan(
		&i.ID,
		&i.ApplicationCode,
		&i.Version,
		&i.Status,
		&i.Content,
		&i.Checksum,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const upsertPermissionPackageImport = `-- name: UpsertPermissionPackageImport :one
INSERT INTO permission_package_imports (
    id, tenant_id, package_id, version, imported_at, imported_by, artifact_id_map
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7::jsonb
)
ON CONFLICT (tenant_id, package_id, version) DO UPDATE SET
    artifact_id_map = permission_package_imports.artifact_id_map
RETURNING id, tenant_id, package_id, version, imported_at, imported_by, artifact_id_map
`

type UpsertPermissionPackageImportParams struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	PackageID     string             `json:"package_id"`
	Version       string             `json:"version"`
	ImportedAt    pgtype.Timestamptz `json:"imported_at"`
	ImportedBy    string             `json:"imported_by"`
	ArtifactIDMap []byte             `json:"artifact_id_map"`
}

func (q *Queries) UpsertPermissionPackageImport(ctx context.Context, arg UpsertPermissionPackageImportParams) (PermissionPackageImport, error) {
	row := q.db.QueryRow(ctx, upsertPermissionPackageImport,
		arg.ID,
		arg.TenantID,
		arg.PackageID,
		arg.Version,
		arg.ImportedAt,
		arg.ImportedBy,
		arg.ArtifactIDMap,
	)
	var i PermissionPackageImport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.Version,
		&i.ImportedAt,
		&i.ImportedBy,
		&i.ArtifactIDMap,
	)
	return i, err
}

const upsertPermissionSetTemplate = `-- name: UpsertPermissionSetTemplate :one
INSERT INTO permission_set_templates (
    id, package_id, template_key, name, content, version
) VALUES (
    $1, $2, $3, $4, $5::jsonb, $6
)
ON CONFLICT (package_id, template_key) DO UPDATE SET
    name = EXCLUDED.name,
    content = EXCLUDED.content,
    version = EXCLUDED.version
RETURNING id, package_id, template_key, name, content, version
`

type UpsertPermissionSetTemplateParams struct {
	ID          string `json:"id"`
	PackageID   string `json:"package_id"`
	TemplateKey string `json:"template_key"`
	Name        string `json:"name"`
	Content     []byte `json:"content"`
	Version     string `json:"version"`
}

func (q *Queries) UpsertPermissionSetTemplate(ctx context.Context, arg UpsertPermissionSetTemplateParams) (PermissionSetTemplate, error) {
	row := q.db.QueryRow(ctx, upsertPermissionSetTemplate,
		arg.ID,
		arg.PackageID,
		arg.TemplateKey,
		arg.Name,
		arg.Content,
		arg.Version,
	)
	var i PermissionSetTemplate
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.TemplateKey,
		&i.Name,
		&i.Content,
		&i.Version,
	)
	return i, err
}

const upsertUserGroupTemplate = `-- name: UpsertUserGroupTemplate :one
INSERT INTO user_group_templates (
    id, package_id, template_key, name, content, version
) VALUES (
    $1, $2, $3, $4, $5::jsonb, $6
)
ON CONFLICT (package_id, template_key) DO UPDATE SET
    name = EXCLUDED.name,
    content = EXCLUDED.content,
    version = EXCLUDED.version
RETURNING id, package_id, template_key, name, content, version
`

type UpsertUserGroupTemplateParams struct {
	ID          string `json:"id"`
	PackageID   string `json:"package_id"`
	TemplateKey string `json:"template_key"`
	Name        string `json:"name"`
	Content     []byte `json:"content"`
	Version     string `json:"version"`
}

func (q *Queries) UpsertUserGroupTemplate(ctx context.Context, arg UpsertUserGroupTemplateParams) (UserGroupTemplate, error) {
	row := q.db.QueryRow(ctx, upsertUserGroupTemplate,
		arg.ID,
		arg.PackageID,
		arg.TemplateKey,
		arg.Name,
		arg.Content,
		arg.Version,
	)
	var i UserGroupTemplate
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.TemplateKey,
		&i.Name,
		&i.Content,
		&i.Version,
	)
	return i, err
}
