package authz

var DefaultRoutePolicies = []RoutePolicy{
	{Name: "me.read", Method: "GET", Path: "/v1/me", ApplicationCode: "platform", ResourceType: "me", Action: "read"},
	{Name: "me.menus", Method: "GET", Path: "/v1/me/menus", ApplicationCode: "platform", ResourceType: "me", Action: "read"},
	{Name: "authz.check", Method: "POST", Path: "/v1/authz/check", ApplicationCode: "iam", ResourceType: "authz", Action: "check"},
	{Name: "authz.batch_check", Method: "POST", Path: "/v1/authz/batch-check", ApplicationCode: "iam", ResourceType: "authz", Action: "check"},
	{Name: "authz.explain", Method: "POST", Path: "/v1/authz/explain", ApplicationCode: "iam", ResourceType: "authz", Action: "explain"},
	{Name: "authz.simulate", Method: "POST", Path: "/v1/authz/simulate", ApplicationCode: "iam", ResourceType: "authz", Action: "simulate", RiskLevel: RiskHigh},
	{Name: "iam.permission.read", Method: "GET", Path: "/v1/iam/permissions", ApplicationCode: "iam", ResourceType: "permission", Action: "read"},
	{Name: "iam.user_group.read", Method: "GET", Path: "/v1/iam/user-groups", ApplicationCode: "iam", ResourceType: "user_group", Action: "read"},
	{Name: "iam.user_group.create", Method: "POST", Path: "/v1/iam/user-groups", ApplicationCode: "iam", ResourceType: "user_group", Action: "create", RiskLevel: RiskHigh},
	{Name: "iam.permission_set.read", Method: "GET", Path: "/v1/iam/permission-sets", ApplicationCode: "iam", ResourceType: "permission_set", Action: "read"},
	{Name: "iam.permission_set.create", Method: "POST", Path: "/v1/iam/permission-sets", ApplicationCode: "iam", ResourceType: "permission_set", Action: "create", RiskLevel: RiskHigh},
	{Name: "iam.permission_assignment.read", Method: "GET", Path: "/v1/iam/permission-set-assignments", ApplicationCode: "iam", ResourceType: "permission_set_assignment", Action: "read"},
	{Name: "iam.permission_assignment.create", Method: "POST", Path: "/v1/iam/permission-set-assignments", ApplicationCode: "iam", ResourceType: "permission_set_assignment", Action: "create", RiskLevel: RiskHigh},
	{Name: "iam.data_scope.read", Method: "GET", Path: "/v1/iam/data-scopes", ApplicationCode: "iam", ResourceType: "data_scope", Action: "read"},
	{Name: "iam.data_scope.create", Method: "POST", Path: "/v1/iam/data-scopes", ApplicationCode: "iam", ResourceType: "data_scope", Action: "create", RiskLevel: RiskHigh},
	{Name: "iam.field_policy.read", Method: "GET", Path: "/v1/iam/field-policies", ApplicationCode: "iam", ResourceType: "field_policy", Action: "read"},
	{Name: "iam.field_policy.create", Method: "POST", Path: "/v1/iam/field-policies", ApplicationCode: "iam", ResourceType: "field_policy", Action: "create", RiskLevel: RiskHigh},
	{Name: "iam.assumable_role.read", Method: "GET", Path: "/v1/iam/assumable-roles", ApplicationCode: "iam", ResourceType: "assumable_role", Action: "read"},
	{Name: "iam.assumable_role.create", Method: "POST", Path: "/v1/iam/assumable-roles", ApplicationCode: "iam", ResourceType: "assumable_role", Action: "create", RiskLevel: RiskHigh},
	{Name: "iam.assumable_role.assume", Method: "POST", Path: "/v1/iam/assumable-roles/:id/assume", ApplicationCode: "iam", ResourceType: "assumable_role", Action: "assume", RiskLevel: RiskHigh},
	{Name: "hr.employee.read", Method: "GET", Path: "/v1/hr/employees", ApplicationCode: "hr", ResourceType: "employee", Action: "read"},
	{Name: "hr.employee.detail", Method: "GET", Path: "/v1/hr/employees/:id", ApplicationCode: "hr", ResourceType: "employee", Action: "read"},
	{Name: "hr.employee.create", Method: "POST", Path: "/v1/hr/employees", ApplicationCode: "hr", ResourceType: "employee", Action: "create"},
	{Name: "hr.employee.preview_create", Method: "POST", Path: "/v1/hr/employees/preview", ApplicationCode: "hr", ResourceType: "employee", Action: "create"},
	{Name: "hr.employee.update", Method: "PATCH", Path: "/v1/hr/employees/:id", ApplicationCode: "hr", ResourceType: "employee", Action: "update"},
	{Name: "hr.employee.preview_update", Method: "POST", Path: "/v1/hr/employees/:id/preview", ApplicationCode: "hr", ResourceType: "employee", Action: "update"},
	{Name: "hr.employee.avatar_update", Method: "POST", Path: "/v1/hr/employees/:id/avatar", ApplicationCode: "hr", ResourceType: "employee", Action: "update"},
	{Name: "hr.employee.avatar_delete", Method: "DELETE", Path: "/v1/hr/employees/:id/avatar", ApplicationCode: "hr", ResourceType: "employee", Action: "update"},
	{Name: "hr.employee.stats", Method: "GET", Path: "/v1/hr/employees/stats", ApplicationCode: "hr", ResourceType: "employee", Action: "read"},
	{Name: "hr.employee.options", Method: "GET", Path: "/v1/hr/employee-options", ApplicationCode: "hr", ResourceType: "employee", Action: "read"},
	{Name: "hr.employee.import_template", Method: "GET", Path: "/v1/hr/employees/import/template", ApplicationCode: "hr", ResourceType: "employee", Action: "read"},
	{Name: "hr.employee.import_preview", Method: "POST", Path: "/v1/hr/employees/import/preview", ApplicationCode: "hr", ResourceType: "employee", Action: "import", RiskLevel: RiskHigh},
	{Name: "hr.employee.import_confirm", Method: "POST", Path: "/v1/hr/employees/import/:id/confirm", ApplicationCode: "hr", ResourceType: "employee", Action: "import", RiskLevel: RiskHigh},
	{Name: "hr.employee.export_download", Method: "GET", Path: "/v1/hr/employees/export", ApplicationCode: "hr", ResourceType: "employee", Action: "export", RiskLevel: RiskHigh},
	{Name: "hr.employee.export", Method: "POST", Path: "/v1/hr/employees/export", ApplicationCode: "hr", ResourceType: "employee", Action: "export", RiskLevel: RiskHigh},
	{Name: "hr.employee.batch_delete", Method: "POST", Path: "/v1/hr/employees/batch-delete", ApplicationCode: "hr", ResourceType: "employee", Action: "delete", RiskLevel: RiskHigh},
	{Name: "hr.employee.delete", Method: "DELETE", Path: "/v1/hr/employees/:id", ApplicationCode: "hr", ResourceType: "employee", Action: "delete", RiskLevel: RiskHigh},
	{Name: "hr.employee.update_status", Method: "PATCH", Path: "/v1/hr/employees/:id/status", ApplicationCode: "hr", ResourceType: "employee", Action: "update_status", RiskLevel: RiskHigh},
	{Name: "hr.employee.invite", Method: "POST", Path: "/v1/hr/employees/:id/invite", ApplicationCode: "hr", ResourceType: "employee", Action: "invite", RiskLevel: RiskHigh},
	{Name: "hr.employee.status_transition", Method: "POST", Path: "/v1/hr/employees/:id/status-transition", ApplicationCode: "hr", ResourceType: "employee", Action: "status_transition", RiskLevel: RiskHigh},
	{Name: "hr.org_unit.read", Method: "GET", Path: "/v1/org/units", ApplicationCode: "hr", ResourceType: "org_unit", Action: "read"},
	{Name: "hr.org_unit.create", Method: "POST", Path: "/v1/org/units", ApplicationCode: "hr", ResourceType: "org_unit", Action: "create"},
	{Name: "attendance.leave.read_balance", Method: "GET", Path: "/v1/attendance/leave-balances", ApplicationCode: "attendance", ResourceType: "leave", Action: "read"},
	{Name: "attendance.leave.read_request", Method: "GET", Path: "/v1/attendance/leave-requests", ApplicationCode: "attendance", ResourceType: "leave", Action: "read"},
	{Name: "attendance.leave.create", Method: "POST", Path: "/v1/attendance/leave-requests", ApplicationCode: "attendance", ResourceType: "leave", Action: "create"},
	{Name: "workflow.form_template.read", Method: "GET", Path: "/v1/forms/templates", ApplicationCode: "workflow", ResourceType: "form_template", Action: "read"},
	{Name: "workflow.form_template.create", Method: "POST", Path: "/v1/forms/templates", ApplicationCode: "workflow", ResourceType: "form_template", Action: "create"},
	{Name: "workflow.form_instance.submit", Method: "POST", Path: "/v1/workflows/forms/:id/submit", ApplicationCode: "workflow", ResourceType: "form_instance", Action: "submit"},
	{Name: "workflow.form_instance.approve", Method: "POST", Path: "/v1/workflows/forms/:id/approve", ApplicationCode: "workflow", ResourceType: "form_instance", Action: "approve"},
	{Name: "agent.run.read", Method: "GET", Path: "/v1/agents/runs", ApplicationCode: "agent", ResourceType: "run", Action: "read"},
	{Name: "agent.run.create", Method: "POST", Path: "/v1/agents/runs", ApplicationCode: "agent", ResourceType: "run", Action: "create", RiskLevel: RiskHigh},
	{Name: "agent.tool.call", Method: "POST", Path: "/internal/agent/tools/:id/call", ApplicationCode: "agent", ResourceType: "tool", Action: "call"},
	{Name: "audit.log.read", Method: "GET", Path: "/v1/audit-logs", ApplicationCode: "audit", ResourceType: "audit_log", Action: "read", RiskLevel: RiskHigh},
}
